// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

// Command 是所有 redisson 命令的元数据接口,由 cmd_gen_<class>.go 中的
// commandXxx 类型实现。所有 commandXxx 的具体值为单一全局零值 (var CommandXxx commandXxx),
// 通过类型方法暴露 metadata,无运行时分配。
type Command interface {
	String() string
	Class() string
	RequireVersion() string
	Forbid() bool
	WarnVersion() string
	Warning() string
	WarningOnce() bool
	Instead() string
	ETC() string
}

const (
	commandClusterSlavesWarning              = "As of Redis version 5.0.0, this command is regarded as deprecated.It can be replaced by CLUSTER REPLICAS when migrating or writing new code."
	commandClusterSlotsWarning               = "As of Redis version 7.0.0, this command is regarded as deprecated.It can be replaced by CLUSTER SHARDS when migrating or writing new code."
	commandGeoRadiusByMemberROWarning        = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by GEOSEARCH and GEOSEARCHSTORE with the BYRADIUS and FROMMEMBER arguments when migrating or writing new code."
	commandGeoRadiusByMemberStoreWarning     = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by GEOSEARCH with the BYRADIUS and FROMMEMBER arguments when migrating or writing new code."
	commandGeoRadiusROWarning                = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by GEOSEARCH with the BYRADIUS argument when migrating or writing new code."
	commandGeoRadiusStoreWarning             = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by GEOSEARCH and GEOSEARCHSTORE with the BYRADIUS argument when migrating or writing new code."
	commandGetSetWarning                     = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by SET with the GET argument when migrating or writing new code."
	commandHMSetWarning                      = "As of Redis version 4.0.0, this command is regarded as deprecated.It can be replaced by HSET with multiple field-value pairs when migrating or writing new code."
	commandKeysWarning                       = "consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets."
	commandMGetWarning                       = "This command is regarded as unsafe in cluster mode."
	commandQuitWarning                       = "As of Redis version 7.2.0, this command is regarded as deprecated.It can be replaced by just closing the connection when migrating or writing new code."
	commandRPopLPushWarning                  = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by LMOVE with the RIGHT and LEFT arguments when migrating or writing new code."
	commandSetBitWarning                     = "When setting the last possible bit (offset equal to 2^32 -1) and the string value stored at key does not yet hold a string value, or holds a small string value, Redis needs to allocate all intermediate memory which can block the server for some time. On a 2010 MacBook Pro, setting bit number 2^32 -1 (512MB allocation) takes ~300ms, setting bit number 2^30 -1 (128MB allocation) takes ~80ms, setting bit number 2^28 -1 (32MB allocation) takes ~30ms and setting bit number 2^26 -1 (8MB allocation) takes ~8ms. Note that once this first allocation is done, subsequent calls to SETBIT for the same key will not have the allocation overhead."
	commandSetEXWarning                      = "As of Redis version 2.6.12, this command is regarded as deprecated.It can be replaced by SET with the EX argument when migrating or writing new code."
	commandSetNXWarning                      = "As of Redis version 2.6.12, this command is regarded as deprecated.It can be replaced by SET with the NX argument when migrating or writing new code."
	commandZRangeByLexWarning                = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the BYLEX argument when migrating or writing new code."
	commandZRangeByScoreWarning              = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the BYSCORE argument when migrating or writing new code."
	commandZRangeByScoreWithScoresWarning    = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the BYSCORE argument when migrating or writing new code."
	commandZRevRangeByLexWarning             = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the REV and BYLEX arguments when migrating or writing new code."
	commandZRevRangeByScoreWarning           = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the REV and BYSCORE arguments when migrating or writing new code."
	commandZRevRangeByScoreWithScoresWarning = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the REV and BYSCORE arguments when migrating or writing new code."
	commandZRevRangeWarning                  = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the REV argument when migrating or writing new code."
	commandZRevRangeWithScoresWarning        = "As of Redis version 6.2.0, this command is regarded as deprecated.It can be replaced by ZRANGE with the REV argument when migrating or writing new code."
)
