// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandClusterAddSlots commandClusterAddSlots

type commandClusterAddSlots string

func (commandClusterAddSlots) String() string         { return "CLUSTER ADDSLOTS" }
func (commandClusterAddSlots) Class() string          { return "Cluster" }
func (commandClusterAddSlots) RequireVersion() string { return "3.0.0" }
func (commandClusterAddSlots) Forbid() bool           { return true }
func (commandClusterAddSlots) WarningOnce() bool      { return false }
func (commandClusterAddSlots) WarnVersion() string    { return "" }
func (commandClusterAddSlots) Warning() string        { return "" }
func (commandClusterAddSlots) Instead() string        { return "" }
func (commandClusterAddSlots) ETC() string            { return "" }

var CommandClusterAddSlotsRange commandClusterAddSlotsRange

type commandClusterAddSlotsRange string

func (commandClusterAddSlotsRange) String() string         { return "CLUSTER ADDSLOTSRANGE" }
func (commandClusterAddSlotsRange) Class() string          { return "Cluster" }
func (commandClusterAddSlotsRange) RequireVersion() string { return "7.0.0" }
func (commandClusterAddSlotsRange) Forbid() bool           { return true }
func (commandClusterAddSlotsRange) WarningOnce() bool      { return false }
func (commandClusterAddSlotsRange) WarnVersion() string    { return "" }
func (commandClusterAddSlotsRange) Warning() string        { return "" }
func (commandClusterAddSlotsRange) Instead() string        { return "" }
func (commandClusterAddSlotsRange) ETC() string            { return "" }

var CommandClusterCountFailureReports commandClusterCountFailureReports

type commandClusterCountFailureReports string

func (commandClusterCountFailureReports) String() string         { return "CLUSTER COUNT-FAILURE-REPORTS" }
func (commandClusterCountFailureReports) Class() string          { return "Cluster" }
func (commandClusterCountFailureReports) RequireVersion() string { return "3.0.0" }
func (commandClusterCountFailureReports) Forbid() bool           { return true }
func (commandClusterCountFailureReports) WarningOnce() bool      { return false }
func (commandClusterCountFailureReports) WarnVersion() string    { return "" }
func (commandClusterCountFailureReports) Warning() string        { return "" }
func (commandClusterCountFailureReports) Instead() string        { return "" }
func (commandClusterCountFailureReports) ETC() string            { return "" }

var CommandClusterCountKeysInSlot commandClusterCountKeysInSlot

type commandClusterCountKeysInSlot string

func (commandClusterCountKeysInSlot) String() string         { return "CLUSTER COUNTKEYSINSLOT" }
func (commandClusterCountKeysInSlot) Class() string          { return "Cluster" }
func (commandClusterCountKeysInSlot) RequireVersion() string { return "3.0.0" }
func (commandClusterCountKeysInSlot) Forbid() bool           { return false }
func (commandClusterCountKeysInSlot) WarningOnce() bool      { return false }
func (commandClusterCountKeysInSlot) WarnVersion() string    { return "" }
func (commandClusterCountKeysInSlot) Warning() string        { return "" }
func (commandClusterCountKeysInSlot) Instead() string        { return "" }
func (commandClusterCountKeysInSlot) ETC() string            { return "" }

var CommandClusterDelSlots commandClusterDelSlots

type commandClusterDelSlots string

func (commandClusterDelSlots) String() string         { return "CLUSTER DELSLOTS" }
func (commandClusterDelSlots) Class() string          { return "Cluster" }
func (commandClusterDelSlots) RequireVersion() string { return "3.0.0" }
func (commandClusterDelSlots) Forbid() bool           { return true }
func (commandClusterDelSlots) WarningOnce() bool      { return false }
func (commandClusterDelSlots) WarnVersion() string    { return "" }
func (commandClusterDelSlots) Warning() string        { return "" }
func (commandClusterDelSlots) Instead() string        { return "" }
func (commandClusterDelSlots) ETC() string            { return "" }

var CommandClusterDelSlotsRange commandClusterDelSlotsRange

type commandClusterDelSlotsRange string

func (commandClusterDelSlotsRange) String() string         { return "CLUSTER DELSLOTSRANGE" }
func (commandClusterDelSlotsRange) Class() string          { return "Cluster" }
func (commandClusterDelSlotsRange) RequireVersion() string { return "7.0.0" }
func (commandClusterDelSlotsRange) Forbid() bool           { return true }
func (commandClusterDelSlotsRange) WarningOnce() bool      { return false }
func (commandClusterDelSlotsRange) WarnVersion() string    { return "" }
func (commandClusterDelSlotsRange) Warning() string        { return "" }
func (commandClusterDelSlotsRange) Instead() string        { return "" }
func (commandClusterDelSlotsRange) ETC() string            { return "" }

var CommandClusterFailover commandClusterFailover

type commandClusterFailover string

func (commandClusterFailover) String() string         { return "CLUSTER FAILOVER" }
func (commandClusterFailover) Class() string          { return "Cluster" }
func (commandClusterFailover) RequireVersion() string { return "3.0.0" }
func (commandClusterFailover) Forbid() bool           { return true }
func (commandClusterFailover) WarningOnce() bool      { return false }
func (commandClusterFailover) WarnVersion() string    { return "" }
func (commandClusterFailover) Warning() string        { return "" }
func (commandClusterFailover) Instead() string        { return "" }
func (commandClusterFailover) ETC() string            { return "" }

var CommandClusterForget commandClusterForget

type commandClusterForget string

func (commandClusterForget) String() string         { return "CLUSTER FORGET" }
func (commandClusterForget) Class() string          { return "Cluster" }
func (commandClusterForget) RequireVersion() string { return "3.0.0" }
func (commandClusterForget) Forbid() bool           { return true }
func (commandClusterForget) WarningOnce() bool      { return false }
func (commandClusterForget) WarnVersion() string    { return "" }
func (commandClusterForget) Warning() string        { return "" }
func (commandClusterForget) Instead() string        { return "" }
func (commandClusterForget) ETC() string            { return "" }

var CommandClusterGetKeysInSlot commandClusterGetKeysInSlot

type commandClusterGetKeysInSlot string

func (commandClusterGetKeysInSlot) String() string         { return "CLUSTER GETKEYSINSLOT" }
func (commandClusterGetKeysInSlot) Class() string          { return "Cluster" }
func (commandClusterGetKeysInSlot) RequireVersion() string { return "3.0.0" }
func (commandClusterGetKeysInSlot) Forbid() bool           { return false }
func (commandClusterGetKeysInSlot) WarningOnce() bool      { return false }
func (commandClusterGetKeysInSlot) WarnVersion() string    { return "" }
func (commandClusterGetKeysInSlot) Warning() string        { return "" }
func (commandClusterGetKeysInSlot) Instead() string        { return "" }
func (commandClusterGetKeysInSlot) ETC() string            { return "" }

var CommandClusterInfo commandClusterInfo

type commandClusterInfo string

func (commandClusterInfo) String() string         { return "CLUSTER INFO" }
func (commandClusterInfo) Class() string          { return "Cluster" }
func (commandClusterInfo) RequireVersion() string { return "3.0.0" }
func (commandClusterInfo) Forbid() bool           { return false }
func (commandClusterInfo) WarningOnce() bool      { return false }
func (commandClusterInfo) WarnVersion() string    { return "" }
func (commandClusterInfo) Warning() string        { return "" }
func (commandClusterInfo) Instead() string        { return "" }
func (commandClusterInfo) ETC() string            { return "" }

var CommandClusterKeySlot commandClusterKeySlot

type commandClusterKeySlot string

func (commandClusterKeySlot) String() string         { return "CLUSTERKEYSLOT" }
func (commandClusterKeySlot) Class() string          { return "Cluster" }
func (commandClusterKeySlot) RequireVersion() string { return "3.0.0" }
func (commandClusterKeySlot) Forbid() bool           { return false }
func (commandClusterKeySlot) WarningOnce() bool      { return false }
func (commandClusterKeySlot) WarnVersion() string    { return "" }
func (commandClusterKeySlot) Warning() string        { return "" }
func (commandClusterKeySlot) Instead() string        { return "" }
func (commandClusterKeySlot) ETC() string            { return "" }

var CommandClusterMeet commandClusterMeet

type commandClusterMeet string

func (commandClusterMeet) String() string         { return "CLUSTER MEET" }
func (commandClusterMeet) Class() string          { return "Cluster" }
func (commandClusterMeet) RequireVersion() string { return "3.0.0" }
func (commandClusterMeet) Forbid() bool           { return true }
func (commandClusterMeet) WarningOnce() bool      { return false }
func (commandClusterMeet) WarnVersion() string    { return "" }
func (commandClusterMeet) Warning() string        { return "" }
func (commandClusterMeet) Instead() string        { return "" }
func (commandClusterMeet) ETC() string            { return "" }

var CommandClusterNodes commandClusterNodes

type commandClusterNodes string

func (commandClusterNodes) String() string         { return "CLUSTER NODES" }
func (commandClusterNodes) Class() string          { return "Cluster" }
func (commandClusterNodes) RequireVersion() string { return "3.0.0" }
func (commandClusterNodes) Forbid() bool           { return false }
func (commandClusterNodes) WarningOnce() bool      { return false }
func (commandClusterNodes) WarnVersion() string    { return "" }
func (commandClusterNodes) Warning() string        { return "" }
func (commandClusterNodes) Instead() string        { return "" }
func (commandClusterNodes) ETC() string            { return "" }

var CommandClusterReplicas commandClusterReplicas

type commandClusterReplicas string

func (commandClusterReplicas) String() string         { return "CLUSTERREPLICAS" }
func (commandClusterReplicas) Class() string          { return "Cluster" }
func (commandClusterReplicas) RequireVersion() string { return "5.0.0" }
func (commandClusterReplicas) Forbid() bool           { return true }
func (commandClusterReplicas) WarningOnce() bool      { return false }
func (commandClusterReplicas) WarnVersion() string    { return "" }
func (commandClusterReplicas) Warning() string        { return "" }
func (commandClusterReplicas) Instead() string        { return "" }
func (commandClusterReplicas) ETC() string            { return "" }

var CommandClusterReplicate commandClusterReplicate

type commandClusterReplicate string

func (commandClusterReplicate) String() string         { return "CLUSTERREPLICATE" }
func (commandClusterReplicate) Class() string          { return "Cluster" }
func (commandClusterReplicate) RequireVersion() string { return "3.0.0" }
func (commandClusterReplicate) Forbid() bool           { return true }
func (commandClusterReplicate) WarningOnce() bool      { return false }
func (commandClusterReplicate) WarnVersion() string    { return "" }
func (commandClusterReplicate) Warning() string        { return "" }
func (commandClusterReplicate) Instead() string        { return "" }
func (commandClusterReplicate) ETC() string            { return "" }

var CommandClusterResetHard commandClusterResetHard

type commandClusterResetHard string

func (commandClusterResetHard) String() string         { return "CLUSTER RESET HARD" }
func (commandClusterResetHard) Class() string          { return "Cluster" }
func (commandClusterResetHard) RequireVersion() string { return "3.0.0" }
func (commandClusterResetHard) Forbid() bool           { return true }
func (commandClusterResetHard) WarningOnce() bool      { return false }
func (commandClusterResetHard) WarnVersion() string    { return "" }
func (commandClusterResetHard) Warning() string        { return "" }
func (commandClusterResetHard) Instead() string        { return "" }
func (commandClusterResetHard) ETC() string            { return "" }

var CommandClusterResetSoft commandClusterResetSoft

type commandClusterResetSoft string

func (commandClusterResetSoft) String() string         { return "CLUSTER RESET SOFT" }
func (commandClusterResetSoft) Class() string          { return "Cluster" }
func (commandClusterResetSoft) RequireVersion() string { return "3.0.0" }
func (commandClusterResetSoft) Forbid() bool           { return true }
func (commandClusterResetSoft) WarningOnce() bool      { return false }
func (commandClusterResetSoft) WarnVersion() string    { return "" }
func (commandClusterResetSoft) Warning() string        { return "" }
func (commandClusterResetSoft) Instead() string        { return "" }
func (commandClusterResetSoft) ETC() string            { return "" }

var CommandClusterSaveConfig commandClusterSaveConfig

type commandClusterSaveConfig string

func (commandClusterSaveConfig) String() string         { return "CLUSTERSAVECONFIG" }
func (commandClusterSaveConfig) Class() string          { return "Cluster" }
func (commandClusterSaveConfig) RequireVersion() string { return "3.0.0" }
func (commandClusterSaveConfig) Forbid() bool           { return true }
func (commandClusterSaveConfig) WarningOnce() bool      { return false }
func (commandClusterSaveConfig) WarnVersion() string    { return "" }
func (commandClusterSaveConfig) Warning() string        { return "" }
func (commandClusterSaveConfig) Instead() string        { return "" }
func (commandClusterSaveConfig) ETC() string            { return "" }

var CommandClusterShards commandClusterShards

type commandClusterShards string

func (commandClusterShards) String() string         { return "CLUSTER SHARDS" }
func (commandClusterShards) Class() string          { return "Cluster" }
func (commandClusterShards) RequireVersion() string { return "7.0.0" }
func (commandClusterShards) Forbid() bool           { return false }
func (commandClusterShards) WarningOnce() bool      { return false }
func (commandClusterShards) WarnVersion() string    { return "" }
func (commandClusterShards) Warning() string        { return "" }
func (commandClusterShards) Instead() string        { return "" }
func (commandClusterShards) ETC() string            { return "" }

var CommandClusterSlaves commandClusterSlaves

type commandClusterSlaves string

func (commandClusterSlaves) String() string         { return "CLUSTER SLAVES" }
func (commandClusterSlaves) Class() string          { return "Cluster" }
func (commandClusterSlaves) RequireVersion() string { return "3.0.0" }
func (commandClusterSlaves) Forbid() bool           { return true }
func (commandClusterSlaves) WarningOnce() bool      { return false }
func (commandClusterSlaves) WarnVersion() string    { return "5.0.0" }
func (commandClusterSlaves) Warning() string        { return commandClusterSlavesWarning }
func (commandClusterSlaves) Instead() string        { return "ClusterReplicas" }
func (commandClusterSlaves) ETC() string            { return "client.ClusterReplicas(ctx, nodeID)" }

var CommandClusterSlots commandClusterSlots

type commandClusterSlots string

func (commandClusterSlots) String() string         { return "CLUSTER SLOTS" }
func (commandClusterSlots) Class() string          { return "Cluster" }
func (commandClusterSlots) RequireVersion() string { return "3.0.0" }
func (commandClusterSlots) Forbid() bool           { return false }
func (commandClusterSlots) WarningOnce() bool      { return false }
func (commandClusterSlots) WarnVersion() string    { return "7.0.0" }
func (commandClusterSlots) Warning() string        { return commandClusterSlotsWarning }
func (commandClusterSlots) Instead() string        { return "ClusterShards" }
func (commandClusterSlots) ETC() string            { return "client.ClusterShards(ctx)" }

var CommandReadOnly commandReadOnly

type commandReadOnly string

func (commandReadOnly) String() string         { return "READONLY" }
func (commandReadOnly) Class() string          { return "Cluster" }
func (commandReadOnly) RequireVersion() string { return "3.0.0" }
func (commandReadOnly) Forbid() bool           { return false }
func (commandReadOnly) WarningOnce() bool      { return false }
func (commandReadOnly) WarnVersion() string    { return "" }
func (commandReadOnly) Warning() string        { return "" }
func (commandReadOnly) Instead() string        { return "" }
func (commandReadOnly) ETC() string            { return "" }

var CommandReadWrite commandReadWrite

type commandReadWrite string

func (commandReadWrite) String() string         { return "READWRITE" }
func (commandReadWrite) Class() string          { return "Cluster" }
func (commandReadWrite) RequireVersion() string { return "3.0.0" }
func (commandReadWrite) Forbid() bool           { return false }
func (commandReadWrite) WarningOnce() bool      { return false }
func (commandReadWrite) WarnVersion() string    { return "" }
func (commandReadWrite) Warning() string        { return "" }
func (commandReadWrite) Instead() string        { return "" }
func (commandReadWrite) ETC() string            { return "" }
