// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

import (
	"time"
)

var CommandAppend commandAppend

type commandAppend string
type commandAppendP struct{ p Pipeliner }

func (commandAppend) String() string               { return "APPEND" }
func (commandAppend) Class() string                { return "String" }
func (commandAppend) RequireVersion() string       { return "2.0.0" }
func (commandAppend) Forbid() bool                 { return false }
func (commandAppend) WarningOnce() bool            { return false }
func (commandAppend) WarnVersion() string          { return "" }
func (commandAppend) Warning() string              { return "" }
func (commandAppend) Instead() string              { return "" }
func (commandAppend) ETC() string                  { return "" }
func (commandAppend) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandAppend) P(p Pipeliner) commandAppendP { return commandAppendP{p} }
func (b commandAppendP) Cmd(key string, value string) {
	b.p.cmd(b.p.builder().AppendCompleted(key, value), &intCmd{})
}

var CommandDecr commandDecr

type commandDecr string
type commandDecrP struct{ p Pipeliner }

func (commandDecr) String() string             { return "DECR" }
func (commandDecr) Class() string              { return "String" }
func (commandDecr) RequireVersion() string     { return "1.0.0" }
func (commandDecr) Forbid() bool               { return false }
func (commandDecr) WarningOnce() bool          { return false }
func (commandDecr) WarnVersion() string        { return "" }
func (commandDecr) Warning() string            { return "" }
func (commandDecr) Instead() string            { return "" }
func (commandDecr) ETC() string                { return "" }
func (commandDecr) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandDecr) P(p Pipeliner) commandDecrP { return commandDecrP{p} }
func (b commandDecrP) Cmd(key string) {
	b.p.cmd(b.p.builder().DecrCompleted(key), &intCmd{})
}

var CommandDecrBy commandDecrBy

type commandDecrBy string
type commandDecrByP struct{ p Pipeliner }

func (commandDecrBy) String() string               { return "DECRBY" }
func (commandDecrBy) Class() string                { return "String" }
func (commandDecrBy) RequireVersion() string       { return "1.0.0" }
func (commandDecrBy) Forbid() bool                 { return false }
func (commandDecrBy) WarningOnce() bool            { return false }
func (commandDecrBy) WarnVersion() string          { return "" }
func (commandDecrBy) Warning() string              { return "" }
func (commandDecrBy) Instead() string              { return "" }
func (commandDecrBy) ETC() string                  { return "" }
func (commandDecrBy) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandDecrBy) P(p Pipeliner) commandDecrByP { return commandDecrByP{p} }
func (b commandDecrByP) Cmd(key string, decrement int64) {
	b.p.cmd(b.p.builder().DecrByCompleted(key, decrement), &intCmd{})
}

var CommandGet commandGet

type commandGet string
type commandGetP struct{ p Pipeliner }

func (commandGet) String() string            { return "GET" }
func (commandGet) Class() string             { return "String" }
func (commandGet) RequireVersion() string    { return "1.0.0" }
func (commandGet) Forbid() bool              { return false }
func (commandGet) WarningOnce() bool         { return false }
func (commandGet) WarnVersion() string       { return "" }
func (commandGet) Warning() string           { return "" }
func (commandGet) Instead() string           { return "" }
func (commandGet) ETC() string               { return "" }
func (commandGet) PR(b BaseCmd) StringCmd    { return b.(StringCmd) }
func (commandGet) P(p Pipeliner) commandGetP { return commandGetP{p} }
func (b commandGetP) Cmd(key string) {
	b.p.cmd(b.p.builder().GetCompleted(key), &stringCmd{})
}

var CommandGetDel commandGetDel

type commandGetDel string
type commandGetDelP struct{ p Pipeliner }

func (commandGetDel) String() string               { return "GETDEL" }
func (commandGetDel) Class() string                { return "String" }
func (commandGetDel) RequireVersion() string       { return "6.2.0" }
func (commandGetDel) Forbid() bool                 { return false }
func (commandGetDel) WarningOnce() bool            { return false }
func (commandGetDel) WarnVersion() string          { return "" }
func (commandGetDel) Warning() string              { return "" }
func (commandGetDel) Instead() string              { return "" }
func (commandGetDel) ETC() string                  { return "" }
func (commandGetDel) PR(b BaseCmd) StringCmd       { return b.(StringCmd) }
func (commandGetDel) P(p Pipeliner) commandGetDelP { return commandGetDelP{p} }
func (b commandGetDelP) Cmd(key string) {
	b.p.cmd(b.p.builder().GetDelCompleted(key), &stringCmd{})
}

var CommandGetEx commandGetEx

type commandGetEx string
type commandGetExP struct{ p Pipeliner }

func (commandGetEx) String() string              { return "GETEX" }
func (commandGetEx) Class() string               { return "String" }
func (commandGetEx) RequireVersion() string      { return "6.2.0" }
func (commandGetEx) Forbid() bool                { return false }
func (commandGetEx) WarningOnce() bool           { return false }
func (commandGetEx) WarnVersion() string         { return "" }
func (commandGetEx) Warning() string             { return "" }
func (commandGetEx) Instead() string             { return "" }
func (commandGetEx) ETC() string                 { return "" }
func (commandGetEx) PR(b BaseCmd) StringCmd      { return b.(StringCmd) }
func (commandGetEx) P(p Pipeliner) commandGetExP { return commandGetExP{p} }
func (b commandGetExP) Cmd(key string, expiration time.Duration) {
	b.p.cmd(b.p.builder().GetExCompleted(key, expiration), &stringCmd{})
}

var CommandGetRange commandGetRange

type commandGetRange string
type commandGetRangeP struct{ p Pipeliner }

func (commandGetRange) String() string                 { return "GETRANGE" }
func (commandGetRange) Class() string                  { return "String" }
func (commandGetRange) RequireVersion() string         { return "2.4.0" }
func (commandGetRange) Forbid() bool                   { return false }
func (commandGetRange) WarningOnce() bool              { return false }
func (commandGetRange) WarnVersion() string            { return "" }
func (commandGetRange) Warning() string                { return "" }
func (commandGetRange) Instead() string                { return "" }
func (commandGetRange) ETC() string                    { return "" }
func (commandGetRange) PR(b BaseCmd) StringCmd         { return b.(StringCmd) }
func (commandGetRange) P(p Pipeliner) commandGetRangeP { return commandGetRangeP{p} }
func (b commandGetRangeP) Cmd(key string, start int64, end int64) {
	b.p.cmd(b.p.builder().GetRangeCompleted(key, start, end), &stringCmd{})
}

var CommandGetSet commandGetSet

type commandGetSet string
type commandGetSetP struct{ p Pipeliner }

func (commandGetSet) String() string         { return "GETSET" }
func (commandGetSet) Class() string          { return "String" }
func (commandGetSet) RequireVersion() string { return "1.0.0" }
func (commandGetSet) Forbid() bool           { return false }
func (commandGetSet) WarningOnce() bool      { return false }
func (commandGetSet) WarnVersion() string    { return "6.2.0" }
func (commandGetSet) Warning() string        { return commandGetSetWarning }
func (commandGetSet) Instead() string        { return "SetArgs" }
func (commandGetSet) ETC() string {
	return "client.SetArgs(ctx, key, value, redisson.SetArgs{Get: true})"
}
func (commandGetSet) PR(b BaseCmd) StringCmd       { return b.(StringCmd) }
func (commandGetSet) P(p Pipeliner) commandGetSetP { return commandGetSetP{p} }
func (b commandGetSetP) Cmd(key string, value any) {
	b.p.cmd(b.p.builder().GetSetCompleted(key, value), &stringCmd{})
}

var CommandIncr commandIncr

type commandIncr string
type commandIncrP struct{ p Pipeliner }

func (commandIncr) String() string             { return "INCR" }
func (commandIncr) Class() string              { return "String" }
func (commandIncr) RequireVersion() string     { return "1.0.0" }
func (commandIncr) Forbid() bool               { return false }
func (commandIncr) WarningOnce() bool          { return false }
func (commandIncr) WarnVersion() string        { return "" }
func (commandIncr) Warning() string            { return "" }
func (commandIncr) Instead() string            { return "" }
func (commandIncr) ETC() string                { return "" }
func (commandIncr) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandIncr) P(p Pipeliner) commandIncrP { return commandIncrP{p} }
func (b commandIncrP) Cmd(key string) {
	b.p.cmd(b.p.builder().IncrCompleted(key), &intCmd{})
}

var CommandIncrBy commandIncrBy

type commandIncrBy string
type commandIncrByP struct{ p Pipeliner }

func (commandIncrBy) String() string               { return "INCRBY" }
func (commandIncrBy) Class() string                { return "String" }
func (commandIncrBy) RequireVersion() string       { return "1.0.0" }
func (commandIncrBy) Forbid() bool                 { return false }
func (commandIncrBy) WarningOnce() bool            { return false }
func (commandIncrBy) WarnVersion() string          { return "" }
func (commandIncrBy) Warning() string              { return "" }
func (commandIncrBy) Instead() string              { return "" }
func (commandIncrBy) ETC() string                  { return "" }
func (commandIncrBy) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandIncrBy) P(p Pipeliner) commandIncrByP { return commandIncrByP{p} }
func (b commandIncrByP) Cmd(key string, value int64) {
	b.p.cmd(b.p.builder().IncrByCompleted(key, value), &intCmd{})
}

var CommandIncrByFloat commandIncrByFloat

type commandIncrByFloat string
type commandIncrByFloatP struct{ p Pipeliner }

func (commandIncrByFloat) String() string                    { return "INCRBYFLOAT" }
func (commandIncrByFloat) Class() string                     { return "String" }
func (commandIncrByFloat) RequireVersion() string            { return "2.6.0" }
func (commandIncrByFloat) Forbid() bool                      { return false }
func (commandIncrByFloat) WarningOnce() bool                 { return false }
func (commandIncrByFloat) WarnVersion() string               { return "" }
func (commandIncrByFloat) Warning() string                   { return "" }
func (commandIncrByFloat) Instead() string                   { return "" }
func (commandIncrByFloat) ETC() string                       { return "" }
func (commandIncrByFloat) PR(b BaseCmd) FloatCmd             { return b.(FloatCmd) }
func (commandIncrByFloat) P(p Pipeliner) commandIncrByFloatP { return commandIncrByFloatP{p} }
func (b commandIncrByFloatP) Cmd(key string, value float64) {
	b.p.cmd(b.p.builder().IncrByFloatCompleted(key, value), &floatCmd{})
}

var CommandMGet commandMGet

type commandMGet string
type commandMGetP struct{ p Pipeliner }

func (commandMGet) String() string             { return "MGET" }
func (commandMGet) Class() string              { return "String" }
func (commandMGet) RequireVersion() string     { return "1.0.0" }
func (commandMGet) Forbid() bool               { return false }
func (commandMGet) WarningOnce() bool          { return false }
func (commandMGet) WarnVersion() string        { return "0.0.0" }
func (commandMGet) Warning() string            { return commandMGetWarning }
func (commandMGet) Instead() string            { return "SafeMGet" }
func (commandMGet) ETC() string                { return "client.SafeMGet(ctx, keys ...)" }
func (commandMGet) PR(b BaseCmd) SliceCmd      { return b.(SliceCmd) }
func (commandMGet) P(p Pipeliner) commandMGetP { return commandMGetP{p} }
func (b commandMGetP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().MGetCompleted(keys...), &sliceCmd{})
}

var CommandMSet commandMSet

type commandMSet string
type commandMSetP struct{ p Pipeliner }

func (commandMSet) String() string             { return "MSET" }
func (commandMSet) Class() string              { return "String" }
func (commandMSet) RequireVersion() string     { return "1.0.1" }
func (commandMSet) Forbid() bool               { return false }
func (commandMSet) WarningOnce() bool          { return false }
func (commandMSet) WarnVersion() string        { return "" }
func (commandMSet) Warning() string            { return "" }
func (commandMSet) Instead() string            { return "" }
func (commandMSet) ETC() string                { return "" }
func (commandMSet) PR(b BaseCmd) StatusCmd     { return b.(StatusCmd) }
func (commandMSet) P(p Pipeliner) commandMSetP { return commandMSetP{p} }
func (b commandMSetP) Cmd(values ...any) {
	b.p.cmd(b.p.builder().MSetCompleted(values...), &statusCmd{})
}

var CommandMSetNX commandMSetNX

type commandMSetNX string
type commandMSetNXP struct{ p Pipeliner }

func (commandMSetNX) String() string               { return "MSETNX" }
func (commandMSetNX) Class() string                { return "String" }
func (commandMSetNX) RequireVersion() string       { return "1.0.1" }
func (commandMSetNX) Forbid() bool                 { return false }
func (commandMSetNX) WarningOnce() bool            { return false }
func (commandMSetNX) WarnVersion() string          { return "" }
func (commandMSetNX) Warning() string              { return "" }
func (commandMSetNX) Instead() string              { return "" }
func (commandMSetNX) ETC() string                  { return "" }
func (commandMSetNX) PR(b BaseCmd) BoolCmd         { return b.(BoolCmd) }
func (commandMSetNX) P(p Pipeliner) commandMSetNXP { return commandMSetNXP{p} }
func (b commandMSetNXP) Cmd(values ...any) {
	b.p.cmd(b.p.builder().MSetNXCompleted(values...), &boolCmd{})
}

var CommandSet commandSet

type commandSet string
type commandSetP struct{ p Pipeliner }

func (commandSet) String() string            { return "SET" }
func (commandSet) Class() string             { return "String" }
func (commandSet) RequireVersion() string    { return "1.0.0" }
func (commandSet) Forbid() bool              { return false }
func (commandSet) WarningOnce() bool         { return false }
func (commandSet) WarnVersion() string       { return "" }
func (commandSet) Warning() string           { return "" }
func (commandSet) Instead() string           { return "" }
func (commandSet) ETC() string               { return "" }
func (commandSet) PR(b BaseCmd) StatusCmd    { return b.(StatusCmd) }
func (commandSet) P(p Pipeliner) commandSetP { return commandSetP{p} }
func (b commandSetP) Cmd(key string, value any, expiration time.Duration) {
	b.p.cmd(b.p.builder().SetCompleted(key, value, expiration), &statusCmd{})
}

var CommandSetArgsEX commandSetArgsEX

type commandSetArgsEX string
type commandSetArgsEXP struct{ p Pipeliner }

func (commandSetArgsEX) String() string                  { return "SET" }
func (commandSetArgsEX) Class() string                   { return "String" }
func (commandSetArgsEX) RequireVersion() string          { return "2.0.0" }
func (commandSetArgsEX) Forbid() bool                    { return false }
func (commandSetArgsEX) WarningOnce() bool               { return false }
func (commandSetArgsEX) WarnVersion() string             { return "" }
func (commandSetArgsEX) Warning() string                 { return "" }
func (commandSetArgsEX) Instead() string                 { return "" }
func (commandSetArgsEX) ETC() string                     { return "" }
func (commandSetArgsEX) PR(b BaseCmd) StatusCmd          { return b.(StatusCmd) }
func (commandSetArgsEX) P(p Pipeliner) commandSetArgsEXP { return commandSetArgsEXP{p} }
func (b commandSetArgsEXP) Cmd(key string, value any, a SetArgs) {
	b.p.cmd(b.p.builder().SetArgsCompleted(key, value, a), &statusCmd{})
}

var CommandSetArgsNX commandSetArgsNX

type commandSetArgsNX string
type commandSetArgsNXP struct{ p Pipeliner }

func (commandSetArgsNX) String() string                  { return "SET" }
func (commandSetArgsNX) Class() string                   { return "String" }
func (commandSetArgsNX) RequireVersion() string          { return "1.0.0" }
func (commandSetArgsNX) Forbid() bool                    { return false }
func (commandSetArgsNX) WarningOnce() bool               { return false }
func (commandSetArgsNX) WarnVersion() string             { return "" }
func (commandSetArgsNX) Warning() string                 { return "" }
func (commandSetArgsNX) Instead() string                 { return "" }
func (commandSetArgsNX) ETC() string                     { return "" }
func (commandSetArgsNX) PR(b BaseCmd) StatusCmd          { return b.(StatusCmd) }
func (commandSetArgsNX) P(p Pipeliner) commandSetArgsNXP { return commandSetArgsNXP{p} }
func (b commandSetArgsNXP) Cmd(key string, value any, a SetArgs) {
	b.p.cmd(b.p.builder().SetArgsCompleted(key, value, a), &statusCmd{})
}

var CommandSetEX commandSetEX

type commandSetEX string
type commandSetEXP struct{ p Pipeliner }

func (commandSetEX) String() string         { return "SETEX" }
func (commandSetEX) Class() string          { return "String" }
func (commandSetEX) RequireVersion() string { return "2.0.0" }
func (commandSetEX) Forbid() bool           { return false }
func (commandSetEX) WarningOnce() bool      { return false }
func (commandSetEX) WarnVersion() string    { return "2.6.12" }
func (commandSetEX) Warning() string        { return commandSetEXWarning }
func (commandSetEX) Instead() string        { return "SetArgs" }
func (commandSetEX) ETC() string {
	return "client.SetArgs(ctx, key, value, redisson.SetArgs{Mode: redisson.EX})"
}
func (commandSetEX) PR(b BaseCmd) StatusCmd      { return b.(StatusCmd) }
func (commandSetEX) P(p Pipeliner) commandSetEXP { return commandSetEXP{p} }
func (b commandSetEXP) Cmd(key string, value any, expiration time.Duration) {
	b.p.cmd(b.p.builder().SetEXCompleted(key, value, expiration), &statusCmd{})
}

var CommandSetGet commandSetGet

type commandSetGet string
type commandSetGetP struct{ p Pipeliner }

func (commandSetGet) String() string               { return "SET" }
func (commandSetGet) Class() string                { return "String" }
func (commandSetGet) RequireVersion() string       { return "6.2.0" }
func (commandSetGet) Forbid() bool                 { return false }
func (commandSetGet) WarningOnce() bool            { return false }
func (commandSetGet) WarnVersion() string          { return "" }
func (commandSetGet) Warning() string              { return "" }
func (commandSetGet) Instead() string              { return "" }
func (commandSetGet) ETC() string                  { return "" }
func (commandSetGet) PR(b BaseCmd) StatusCmd       { return b.(StatusCmd) }
func (commandSetGet) P(p Pipeliner) commandSetGetP { return commandSetGetP{p} }
func (b commandSetGetP) Cmd(key string, value any, a SetArgs) {
	b.p.cmd(b.p.builder().SetArgsCompleted(key, value, a), &statusCmd{})
}

var CommandSetKeepTTL commandSetKeepTTL

type commandSetKeepTTL string
type commandSetKeepTTLP struct{ p Pipeliner }

func (commandSetKeepTTL) String() string                   { return "SET" }
func (commandSetKeepTTL) Class() string                    { return "String" }
func (commandSetKeepTTL) RequireVersion() string           { return "6.0.0" }
func (commandSetKeepTTL) Forbid() bool                     { return false }
func (commandSetKeepTTL) WarningOnce() bool                { return false }
func (commandSetKeepTTL) WarnVersion() string              { return "" }
func (commandSetKeepTTL) Warning() string                  { return "" }
func (commandSetKeepTTL) Instead() string                  { return "" }
func (commandSetKeepTTL) ETC() string                      { return "" }
func (commandSetKeepTTL) PR(b BaseCmd) StatusCmd           { return b.(StatusCmd) }
func (commandSetKeepTTL) P(p Pipeliner) commandSetKeepTTLP { return commandSetKeepTTLP{p} }
func (b commandSetKeepTTLP) Cmd(key string, value any) {
	b.p.cmd(b.p.builder().SetKeepTTLCompleted(key, value), &statusCmd{})
}

var CommandSetNX commandSetNX

type commandSetNX string
type commandSetNXP struct{ p Pipeliner }

func (commandSetNX) String() string         { return "SETNX" }
func (commandSetNX) Class() string          { return "String" }
func (commandSetNX) RequireVersion() string { return "1.0.0" }
func (commandSetNX) Forbid() bool           { return false }
func (commandSetNX) WarningOnce() bool      { return false }
func (commandSetNX) WarnVersion() string    { return "2.6.12" }
func (commandSetNX) Warning() string        { return commandSetNXWarning }
func (commandSetNX) Instead() string        { return "SetArgs" }
func (commandSetNX) ETC() string {
	return "client.SetArgs(ctx, key, value, redisson.SetArgs{Mode: redisson.NX})"
}
func (commandSetNX) PR(b BaseCmd) BoolCmd        { return b.(BoolCmd) }
func (commandSetNX) P(p Pipeliner) commandSetNXP { return commandSetNXP{p} }
func (b commandSetNXP) Cmd(key string, value any, expiration time.Duration) {
	b.p.cmd(b.p.builder().SetNXCompleted(key, value, expiration), &boolCmd{})
}

var CommandSetNXGet commandSetNXGet

type commandSetNXGet string
type commandSetNXGetP struct{ p Pipeliner }

func (commandSetNXGet) String() string                 { return "SET" }
func (commandSetNXGet) Class() string                  { return "String" }
func (commandSetNXGet) RequireVersion() string         { return "7.0.0" }
func (commandSetNXGet) Forbid() bool                   { return false }
func (commandSetNXGet) WarningOnce() bool              { return false }
func (commandSetNXGet) WarnVersion() string            { return "" }
func (commandSetNXGet) Warning() string                { return "" }
func (commandSetNXGet) Instead() string                { return "" }
func (commandSetNXGet) ETC() string                    { return "" }
func (commandSetNXGet) PR(b BaseCmd) StatusCmd         { return b.(StatusCmd) }
func (commandSetNXGet) P(p Pipeliner) commandSetNXGetP { return commandSetNXGetP{p} }
func (b commandSetNXGetP) Cmd(key string, value any, a SetArgs) {
	b.p.cmd(b.p.builder().SetArgsCompleted(key, value, a), &statusCmd{})
}

var CommandSetRange commandSetRange

type commandSetRange string
type commandSetRangeP struct{ p Pipeliner }

func (commandSetRange) String() string                 { return "SETRANGE" }
func (commandSetRange) Class() string                  { return "String" }
func (commandSetRange) RequireVersion() string         { return "2.2.0" }
func (commandSetRange) Forbid() bool                   { return false }
func (commandSetRange) WarningOnce() bool              { return false }
func (commandSetRange) WarnVersion() string            { return "" }
func (commandSetRange) Warning() string                { return "" }
func (commandSetRange) Instead() string                { return "" }
func (commandSetRange) ETC() string                    { return "" }
func (commandSetRange) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandSetRange) P(p Pipeliner) commandSetRangeP { return commandSetRangeP{p} }
func (b commandSetRangeP) Cmd(key string, offset int64, value string) {
	b.p.cmd(b.p.builder().SetRangeCompleted(key, offset, value), &intCmd{})
}

var CommandSetXX commandSetXX

type commandSetXX string
type commandSetXXP struct{ p Pipeliner }

func (commandSetXX) String() string              { return "SETXX" }
func (commandSetXX) Class() string               { return "String" }
func (commandSetXX) RequireVersion() string      { return "2.6.12" }
func (commandSetXX) Forbid() bool                { return false }
func (commandSetXX) WarningOnce() bool           { return false }
func (commandSetXX) WarnVersion() string         { return "" }
func (commandSetXX) Warning() string             { return "" }
func (commandSetXX) Instead() string             { return "" }
func (commandSetXX) ETC() string                 { return "" }
func (commandSetXX) PR(b BaseCmd) BoolCmd        { return b.(BoolCmd) }
func (commandSetXX) P(p Pipeliner) commandSetXXP { return commandSetXXP{p} }
func (b commandSetXXP) Cmd(key string, value any, expiration time.Duration) {
	b.p.cmd(b.p.builder().SetXXCompleted(key, value, expiration), &boolCmd{})
}

var CommandStrLen commandStrLen

type commandStrLen string
type commandStrLenP struct{ p Pipeliner }

func (commandStrLen) String() string               { return "STRLEN" }
func (commandStrLen) Class() string                { return "String" }
func (commandStrLen) RequireVersion() string       { return "2.2.0" }
func (commandStrLen) Forbid() bool                 { return false }
func (commandStrLen) WarningOnce() bool            { return false }
func (commandStrLen) WarnVersion() string          { return "" }
func (commandStrLen) Warning() string              { return "" }
func (commandStrLen) Instead() string              { return "" }
func (commandStrLen) ETC() string                  { return "" }
func (commandStrLen) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandStrLen) P(p Pipeliner) commandStrLenP { return commandStrLenP{p} }
func (b commandStrLenP) Cmd(key string) {
	b.p.cmd(b.p.builder().StrLenCompleted(key), &intCmd{})
}
