// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

import (
	"time"
)

var CommandCopy commandCopy

type commandCopy string
type commandCopyP struct{ p Pipeliner }

func (commandCopy) String() string             { return "COPY" }
func (commandCopy) Class() string              { return "Generic" }
func (commandCopy) RequireVersion() string     { return "6.2.0" }
func (commandCopy) Forbid() bool               { return false }
func (commandCopy) WarningOnce() bool          { return false }
func (commandCopy) WarnVersion() string        { return "" }
func (commandCopy) Warning() string            { return "" }
func (commandCopy) Instead() string            { return "" }
func (commandCopy) ETC() string                { return "" }
func (commandCopy) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandCopy) P(p Pipeliner) commandCopyP { return commandCopyP{p} }
func (b commandCopyP) Cmd(source string, destination string, db int64, replace bool) {
	b.p.cmd(b.p.builder().CopyCompleted(source, destination, db, replace), &intCmd{})
}

var CommandDel commandDel

type commandDel string
type commandDelP struct{ p Pipeliner }

func (commandDel) String() string            { return "DEL" }
func (commandDel) Class() string             { return "Generic" }
func (commandDel) RequireVersion() string    { return "1.0.0" }
func (commandDel) Forbid() bool              { return false }
func (commandDel) WarningOnce() bool         { return false }
func (commandDel) WarnVersion() string       { return "" }
func (commandDel) Warning() string           { return "" }
func (commandDel) Instead() string           { return "" }
func (commandDel) ETC() string               { return "" }
func (commandDel) PR(b BaseCmd) IntCmd       { return b.(IntCmd) }
func (commandDel) P(p Pipeliner) commandDelP { return commandDelP{p} }
func (b commandDelP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().DelCompleted(keys...), &intCmd{})
}

var CommandDump commandDump

type commandDump string
type commandDumpP struct{ p Pipeliner }

func (commandDump) String() string             { return "DUMP" }
func (commandDump) Class() string              { return "Generic" }
func (commandDump) RequireVersion() string     { return "2.6.0" }
func (commandDump) Forbid() bool               { return false }
func (commandDump) WarningOnce() bool          { return false }
func (commandDump) WarnVersion() string        { return "" }
func (commandDump) Warning() string            { return "" }
func (commandDump) Instead() string            { return "" }
func (commandDump) ETC() string                { return "" }
func (commandDump) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandDump) P(p Pipeliner) commandDumpP { return commandDumpP{p} }
func (b commandDumpP) Cmd(key string) {
	b.p.cmd(b.p.builder().DumpCompleted(key), &stringCmd{})
}

var CommandExists commandExists

type commandExists string
type commandExistsP struct{ p Pipeliner }

func (commandExists) String() string               { return "EXISTS" }
func (commandExists) Class() string                { return "Generic" }
func (commandExists) RequireVersion() string       { return "1.0.0" }
func (commandExists) Forbid() bool                 { return false }
func (commandExists) WarningOnce() bool            { return false }
func (commandExists) WarnVersion() string          { return "" }
func (commandExists) Warning() string              { return "" }
func (commandExists) Instead() string              { return "" }
func (commandExists) ETC() string                  { return "" }
func (commandExists) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandExists) P(p Pipeliner) commandExistsP { return commandExistsP{p} }
func (b commandExistsP) Cmd(key string) {
	b.p.cmd(b.p.builder().ExistsCompleted(key), &intCmd{})
}

var CommandExpire commandExpire

type commandExpire string
type commandExpireP struct{ p Pipeliner }

func (commandExpire) String() string               { return "EXPIRE" }
func (commandExpire) Class() string                { return "Generic" }
func (commandExpire) RequireVersion() string       { return "1.0.0" }
func (commandExpire) Forbid() bool                 { return false }
func (commandExpire) WarningOnce() bool            { return false }
func (commandExpire) WarnVersion() string          { return "" }
func (commandExpire) Warning() string              { return "" }
func (commandExpire) Instead() string              { return "" }
func (commandExpire) ETC() string                  { return "" }
func (commandExpire) PR(b BaseCmd) BoolCmd         { return b.(BoolCmd) }
func (commandExpire) P(p Pipeliner) commandExpireP { return commandExpireP{p} }
func (b commandExpireP) Cmd(key string, seconds time.Duration) {
	b.p.cmd(b.p.builder().ExpireCompleted(key, seconds), &boolCmd{})
}

var CommandExpireAt commandExpireAt

type commandExpireAt string
type commandExpireAtP struct{ p Pipeliner }

func (commandExpireAt) String() string                 { return "EXPIREAT" }
func (commandExpireAt) Class() string                  { return "Generic" }
func (commandExpireAt) RequireVersion() string         { return "1.2.0" }
func (commandExpireAt) Forbid() bool                   { return false }
func (commandExpireAt) WarningOnce() bool              { return false }
func (commandExpireAt) WarnVersion() string            { return "" }
func (commandExpireAt) Warning() string                { return "" }
func (commandExpireAt) Instead() string                { return "" }
func (commandExpireAt) ETC() string                    { return "" }
func (commandExpireAt) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandExpireAt) P(p Pipeliner) commandExpireAtP { return commandExpireAtP{p} }
func (b commandExpireAtP) Cmd(key string, timestamp time.Time) {
	b.p.cmd(b.p.builder().ExpireAtCompleted(key, timestamp), &boolCmd{})
}

var CommandExpireAtGT commandExpireAtGT

type commandExpireAtGT string
type commandExpireAtGTP struct{ p Pipeliner }

func (commandExpireAtGT) String() string                   { return "EXPIREAT GT" }
func (commandExpireAtGT) Class() string                    { return "Generic" }
func (commandExpireAtGT) RequireVersion() string           { return "7.0.0" }
func (commandExpireAtGT) Forbid() bool                     { return false }
func (commandExpireAtGT) WarningOnce() bool                { return false }
func (commandExpireAtGT) WarnVersion() string              { return "" }
func (commandExpireAtGT) Warning() string                  { return "" }
func (commandExpireAtGT) Instead() string                  { return "" }
func (commandExpireAtGT) ETC() string                      { return "" }
func (commandExpireAtGT) PR(b BaseCmd) BoolCmd             { return b.(BoolCmd) }
func (commandExpireAtGT) P(p Pipeliner) commandExpireAtGTP { return commandExpireAtGTP{p} }
func (b commandExpireAtGTP) Cmd(key string, timestamp time.Time) {
	b.p.cmd(b.p.builder().ExpireAtGTCompleted(key, timestamp), &boolCmd{})
}

var CommandExpireAtLT commandExpireAtLT

type commandExpireAtLT string
type commandExpireAtLTP struct{ p Pipeliner }

func (commandExpireAtLT) String() string                   { return "EXPIREAT LT" }
func (commandExpireAtLT) Class() string                    { return "Generic" }
func (commandExpireAtLT) RequireVersion() string           { return "7.0.0" }
func (commandExpireAtLT) Forbid() bool                     { return false }
func (commandExpireAtLT) WarningOnce() bool                { return false }
func (commandExpireAtLT) WarnVersion() string              { return "" }
func (commandExpireAtLT) Warning() string                  { return "" }
func (commandExpireAtLT) Instead() string                  { return "" }
func (commandExpireAtLT) ETC() string                      { return "" }
func (commandExpireAtLT) PR(b BaseCmd) BoolCmd             { return b.(BoolCmd) }
func (commandExpireAtLT) P(p Pipeliner) commandExpireAtLTP { return commandExpireAtLTP{p} }
func (b commandExpireAtLTP) Cmd(key string, timestamp time.Time) {
	b.p.cmd(b.p.builder().ExpireAtLTCompleted(key, timestamp), &boolCmd{})
}

var CommandExpireAtNX commandExpireAtNX

type commandExpireAtNX string
type commandExpireAtNXP struct{ p Pipeliner }

func (commandExpireAtNX) String() string                   { return "EXPIREAT NX" }
func (commandExpireAtNX) Class() string                    { return "Generic" }
func (commandExpireAtNX) RequireVersion() string           { return "7.0.0" }
func (commandExpireAtNX) Forbid() bool                     { return false }
func (commandExpireAtNX) WarningOnce() bool                { return false }
func (commandExpireAtNX) WarnVersion() string              { return "" }
func (commandExpireAtNX) Warning() string                  { return "" }
func (commandExpireAtNX) Instead() string                  { return "" }
func (commandExpireAtNX) ETC() string                      { return "" }
func (commandExpireAtNX) PR(b BaseCmd) BoolCmd             { return b.(BoolCmd) }
func (commandExpireAtNX) P(p Pipeliner) commandExpireAtNXP { return commandExpireAtNXP{p} }
func (b commandExpireAtNXP) Cmd(key string, timestamp time.Time) {
	b.p.cmd(b.p.builder().ExpireAtNXCompleted(key, timestamp), &boolCmd{})
}

var CommandExpireAtXX commandExpireAtXX

type commandExpireAtXX string
type commandExpireAtXXP struct{ p Pipeliner }

func (commandExpireAtXX) String() string                   { return "EXPIREAT XX" }
func (commandExpireAtXX) Class() string                    { return "Generic" }
func (commandExpireAtXX) RequireVersion() string           { return "7.0.0" }
func (commandExpireAtXX) Forbid() bool                     { return false }
func (commandExpireAtXX) WarningOnce() bool                { return false }
func (commandExpireAtXX) WarnVersion() string              { return "" }
func (commandExpireAtXX) Warning() string                  { return "" }
func (commandExpireAtXX) Instead() string                  { return "" }
func (commandExpireAtXX) ETC() string                      { return "" }
func (commandExpireAtXX) PR(b BaseCmd) BoolCmd             { return b.(BoolCmd) }
func (commandExpireAtXX) P(p Pipeliner) commandExpireAtXXP { return commandExpireAtXXP{p} }
func (b commandExpireAtXXP) Cmd(key string, timestamp time.Time) {
	b.p.cmd(b.p.builder().ExpireAtXXCompleted(key, timestamp), &boolCmd{})
}

var CommandExpireGT commandExpireGT

type commandExpireGT string
type commandExpireGTP struct{ p Pipeliner }

func (commandExpireGT) String() string                 { return "EXPIRE GT" }
func (commandExpireGT) Class() string                  { return "Generic" }
func (commandExpireGT) RequireVersion() string         { return "7.0.0" }
func (commandExpireGT) Forbid() bool                   { return false }
func (commandExpireGT) WarningOnce() bool              { return false }
func (commandExpireGT) WarnVersion() string            { return "" }
func (commandExpireGT) Warning() string                { return "" }
func (commandExpireGT) Instead() string                { return "" }
func (commandExpireGT) ETC() string                    { return "" }
func (commandExpireGT) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandExpireGT) P(p Pipeliner) commandExpireGTP { return commandExpireGTP{p} }
func (b commandExpireGTP) Cmd(key string, seconds time.Duration) {
	b.p.cmd(b.p.builder().ExpireGTCompleted(key, seconds), &boolCmd{})
}

var CommandExpireLT commandExpireLT

type commandExpireLT string
type commandExpireLTP struct{ p Pipeliner }

func (commandExpireLT) String() string                 { return "EXPIRE LT" }
func (commandExpireLT) Class() string                  { return "Generic" }
func (commandExpireLT) RequireVersion() string         { return "7.0.0" }
func (commandExpireLT) Forbid() bool                   { return false }
func (commandExpireLT) WarningOnce() bool              { return false }
func (commandExpireLT) WarnVersion() string            { return "" }
func (commandExpireLT) Warning() string                { return "" }
func (commandExpireLT) Instead() string                { return "" }
func (commandExpireLT) ETC() string                    { return "" }
func (commandExpireLT) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandExpireLT) P(p Pipeliner) commandExpireLTP { return commandExpireLTP{p} }
func (b commandExpireLTP) Cmd(key string, seconds time.Duration) {
	b.p.cmd(b.p.builder().ExpireLTCompleted(key, seconds), &boolCmd{})
}

var CommandExpireNX commandExpireNX

type commandExpireNX string
type commandExpireNXP struct{ p Pipeliner }

func (commandExpireNX) String() string                 { return "EXPIRE NX" }
func (commandExpireNX) Class() string                  { return "Generic" }
func (commandExpireNX) RequireVersion() string         { return "7.0.0" }
func (commandExpireNX) Forbid() bool                   { return false }
func (commandExpireNX) WarningOnce() bool              { return false }
func (commandExpireNX) WarnVersion() string            { return "" }
func (commandExpireNX) Warning() string                { return "" }
func (commandExpireNX) Instead() string                { return "" }
func (commandExpireNX) ETC() string                    { return "" }
func (commandExpireNX) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandExpireNX) P(p Pipeliner) commandExpireNXP { return commandExpireNXP{p} }
func (b commandExpireNXP) Cmd(key string, seconds time.Duration) {
	b.p.cmd(b.p.builder().ExpireNXCompleted(key, seconds), &boolCmd{})
}

var CommandExpireTime commandExpireTime

type commandExpireTime string
type commandExpireTimeP struct{ p Pipeliner }

func (commandExpireTime) String() string                   { return "EXPIRETIME" }
func (commandExpireTime) Class() string                    { return "Generic" }
func (commandExpireTime) RequireVersion() string           { return "7.0.0" }
func (commandExpireTime) Forbid() bool                     { return false }
func (commandExpireTime) WarningOnce() bool                { return false }
func (commandExpireTime) WarnVersion() string              { return "" }
func (commandExpireTime) Warning() string                  { return "" }
func (commandExpireTime) Instead() string                  { return "" }
func (commandExpireTime) ETC() string                      { return "" }
func (commandExpireTime) PR(b BaseCmd) DurationCmd         { return b.(DurationCmd) }
func (commandExpireTime) P(p Pipeliner) commandExpireTimeP { return commandExpireTimeP{p} }
func (b commandExpireTimeP) Cmd(key string) {
	b.p.cmd(b.p.builder().ExpireTimeCompleted(key), &durationCmd{})
}

var CommandExpireXX commandExpireXX

type commandExpireXX string
type commandExpireXXP struct{ p Pipeliner }

func (commandExpireXX) String() string                 { return "EXPIRE XX" }
func (commandExpireXX) Class() string                  { return "Generic" }
func (commandExpireXX) RequireVersion() string         { return "7.0.0" }
func (commandExpireXX) Forbid() bool                   { return false }
func (commandExpireXX) WarningOnce() bool              { return false }
func (commandExpireXX) WarnVersion() string            { return "" }
func (commandExpireXX) Warning() string                { return "" }
func (commandExpireXX) Instead() string                { return "" }
func (commandExpireXX) ETC() string                    { return "" }
func (commandExpireXX) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandExpireXX) P(p Pipeliner) commandExpireXXP { return commandExpireXXP{p} }
func (b commandExpireXXP) Cmd(key string, seconds time.Duration) {
	b.p.cmd(b.p.builder().ExpireXXCompleted(key, seconds), &boolCmd{})
}

var CommandKeys commandKeys

type commandKeys string

func (commandKeys) String() string         { return "KEYS" }
func (commandKeys) Class() string          { return "Generic" }
func (commandKeys) RequireVersion() string { return "1.0.0" }
func (commandKeys) Forbid() bool           { return true }
func (commandKeys) WarningOnce() bool      { return false }
func (commandKeys) WarnVersion() string    { return "0.0.0" }
func (commandKeys) Warning() string        { return commandKeysWarning }
func (commandKeys) Instead() string        { return "" }
func (commandKeys) ETC() string            { return "" }

var CommandMExists commandMExists

type commandMExists string
type commandMExistsP struct{ p Pipeliner }

func (commandMExists) String() string                { return "EXISTS" }
func (commandMExists) Class() string                 { return "Generic" }
func (commandMExists) RequireVersion() string        { return "3.0.3" }
func (commandMExists) Forbid() bool                  { return false }
func (commandMExists) WarningOnce() bool             { return false }
func (commandMExists) WarnVersion() string           { return "" }
func (commandMExists) Warning() string               { return "" }
func (commandMExists) Instead() string               { return "" }
func (commandMExists) ETC() string                   { return "" }
func (commandMExists) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandMExists) P(p Pipeliner) commandMExistsP { return commandMExistsP{p} }
func (b commandMExistsP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().ExistsCompleted(keys...), &intCmd{})
}

var CommandMigrate commandMigrate

type commandMigrate string
type commandMigrateP struct{ p Pipeliner }

func (commandMigrate) String() string                { return "MIGRATE" }
func (commandMigrate) Class() string                 { return "Generic" }
func (commandMigrate) RequireVersion() string        { return "2.6.0" }
func (commandMigrate) Forbid() bool                  { return true }
func (commandMigrate) WarningOnce() bool             { return false }
func (commandMigrate) WarnVersion() string           { return "" }
func (commandMigrate) Warning() string               { return "" }
func (commandMigrate) Instead() string               { return "" }
func (commandMigrate) ETC() string                   { return "" }
func (commandMigrate) PR(b BaseCmd) StatusCmd        { return b.(StatusCmd) }
func (commandMigrate) P(p Pipeliner) commandMigrateP { return commandMigrateP{p} }
func (b commandMigrateP) Cmd(host string, port int64, key string, db int64, timeout time.Duration) {
	b.p.cmd(b.p.builder().MigrateCompleted(host, port, key, db, timeout), &statusCmd{})
}

var CommandMove commandMove

type commandMove string
type commandMoveP struct{ p Pipeliner }

func (commandMove) String() string             { return "MOVE" }
func (commandMove) Class() string              { return "Generic" }
func (commandMove) RequireVersion() string     { return "1.0.0" }
func (commandMove) Forbid() bool               { return false }
func (commandMove) WarningOnce() bool          { return false }
func (commandMove) WarnVersion() string        { return "" }
func (commandMove) Warning() string            { return "" }
func (commandMove) Instead() string            { return "" }
func (commandMove) ETC() string                { return "" }
func (commandMove) PR(b BaseCmd) BoolCmd       { return b.(BoolCmd) }
func (commandMove) P(p Pipeliner) commandMoveP { return commandMoveP{p} }
func (b commandMoveP) Cmd(key string, db int64) {
	b.p.cmd(b.p.builder().MoveCompleted(key, db), &boolCmd{})
}

var CommandObjectEncoding commandObjectEncoding

type commandObjectEncoding string
type commandObjectEncodingP struct{ p Pipeliner }

func (commandObjectEncoding) String() string                       { return "OBJECT ENCODING" }
func (commandObjectEncoding) Class() string                        { return "Generic" }
func (commandObjectEncoding) RequireVersion() string               { return "2.2.3" }
func (commandObjectEncoding) Forbid() bool                         { return false }
func (commandObjectEncoding) WarningOnce() bool                    { return false }
func (commandObjectEncoding) WarnVersion() string                  { return "" }
func (commandObjectEncoding) Warning() string                      { return "" }
func (commandObjectEncoding) Instead() string                      { return "" }
func (commandObjectEncoding) ETC() string                          { return "" }
func (commandObjectEncoding) PR(b BaseCmd) StringCmd               { return b.(StringCmd) }
func (commandObjectEncoding) P(p Pipeliner) commandObjectEncodingP { return commandObjectEncodingP{p} }
func (b commandObjectEncodingP) Cmd(key string) {
	b.p.cmd(b.p.builder().ObjectEncodingCompleted(key), &stringCmd{})
}

var CommandObjectIdleTime commandObjectIdleTime

type commandObjectIdleTime string
type commandObjectIdleTimeP struct{ p Pipeliner }

func (commandObjectIdleTime) String() string                       { return "OBJECT IDLETIME" }
func (commandObjectIdleTime) Class() string                        { return "Generic" }
func (commandObjectIdleTime) RequireVersion() string               { return "2.2.3" }
func (commandObjectIdleTime) Forbid() bool                         { return false }
func (commandObjectIdleTime) WarningOnce() bool                    { return false }
func (commandObjectIdleTime) WarnVersion() string                  { return "" }
func (commandObjectIdleTime) Warning() string                      { return "" }
func (commandObjectIdleTime) Instead() string                      { return "" }
func (commandObjectIdleTime) ETC() string                          { return "" }
func (commandObjectIdleTime) PR(b BaseCmd) DurationCmd             { return b.(DurationCmd) }
func (commandObjectIdleTime) P(p Pipeliner) commandObjectIdleTimeP { return commandObjectIdleTimeP{p} }
func (b commandObjectIdleTimeP) Cmd(key string) {
	b.p.cmd(b.p.builder().ObjectIdleTimeCompleted(key), &durationCmd{})
}

var CommandObjectRefCount commandObjectRefCount

type commandObjectRefCount string
type commandObjectRefCountP struct{ p Pipeliner }

func (commandObjectRefCount) String() string                       { return "OBJECT REFCOUNT" }
func (commandObjectRefCount) Class() string                        { return "Generic" }
func (commandObjectRefCount) RequireVersion() string               { return "2.2.3" }
func (commandObjectRefCount) Forbid() bool                         { return false }
func (commandObjectRefCount) WarningOnce() bool                    { return false }
func (commandObjectRefCount) WarnVersion() string                  { return "" }
func (commandObjectRefCount) Warning() string                      { return "" }
func (commandObjectRefCount) Instead() string                      { return "" }
func (commandObjectRefCount) ETC() string                          { return "" }
func (commandObjectRefCount) PR(b BaseCmd) IntCmd                  { return b.(IntCmd) }
func (commandObjectRefCount) P(p Pipeliner) commandObjectRefCountP { return commandObjectRefCountP{p} }
func (b commandObjectRefCountP) Cmd(key string) {
	b.p.cmd(b.p.builder().ObjectRefCountCompleted(key), &intCmd{})
}

var CommandPExpire commandPExpire

type commandPExpire string
type commandPExpireP struct{ p Pipeliner }

func (commandPExpire) String() string                { return "PEXPIRE" }
func (commandPExpire) Class() string                 { return "Generic" }
func (commandPExpire) RequireVersion() string        { return "2.6.0" }
func (commandPExpire) Forbid() bool                  { return false }
func (commandPExpire) WarningOnce() bool             { return false }
func (commandPExpire) WarnVersion() string           { return "" }
func (commandPExpire) Warning() string               { return "" }
func (commandPExpire) Instead() string               { return "" }
func (commandPExpire) ETC() string                   { return "" }
func (commandPExpire) PR(b BaseCmd) BoolCmd          { return b.(BoolCmd) }
func (commandPExpire) P(p Pipeliner) commandPExpireP { return commandPExpireP{p} }
func (b commandPExpireP) Cmd(key string, milliseconds time.Duration) {
	b.p.cmd(b.p.builder().PExpireCompleted(key, milliseconds), &boolCmd{})
}

var CommandPExpireAt commandPExpireAt

type commandPExpireAt string
type commandPExpireAtP struct{ p Pipeliner }

func (commandPExpireAt) String() string                  { return "PEXPIREAT" }
func (commandPExpireAt) Class() string                   { return "Generic" }
func (commandPExpireAt) RequireVersion() string          { return "2.6.0" }
func (commandPExpireAt) Forbid() bool                    { return false }
func (commandPExpireAt) WarningOnce() bool               { return false }
func (commandPExpireAt) WarnVersion() string             { return "" }
func (commandPExpireAt) Warning() string                 { return "" }
func (commandPExpireAt) Instead() string                 { return "" }
func (commandPExpireAt) ETC() string                     { return "" }
func (commandPExpireAt) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandPExpireAt) P(p Pipeliner) commandPExpireAtP { return commandPExpireAtP{p} }
func (b commandPExpireAtP) Cmd(key string, millisecondsTimestamp time.Time) {
	b.p.cmd(b.p.builder().PExpireAtCompleted(key, millisecondsTimestamp), &boolCmd{})
}

var CommandPExpireAtGT commandPExpireAtGT

type commandPExpireAtGT string
type commandPExpireAtGTP struct{ p Pipeliner }

func (commandPExpireAtGT) String() string                    { return "PEXPIREAT GT" }
func (commandPExpireAtGT) Class() string                     { return "Generic" }
func (commandPExpireAtGT) RequireVersion() string            { return "7.0.0" }
func (commandPExpireAtGT) Forbid() bool                      { return false }
func (commandPExpireAtGT) WarningOnce() bool                 { return false }
func (commandPExpireAtGT) WarnVersion() string               { return "" }
func (commandPExpireAtGT) Warning() string                   { return "" }
func (commandPExpireAtGT) Instead() string                   { return "" }
func (commandPExpireAtGT) ETC() string                       { return "" }
func (commandPExpireAtGT) PR(b BaseCmd) BoolCmd              { return b.(BoolCmd) }
func (commandPExpireAtGT) P(p Pipeliner) commandPExpireAtGTP { return commandPExpireAtGTP{p} }
func (b commandPExpireAtGTP) Cmd(key string, millisecondsTimestamp time.Time) {
	b.p.cmd(b.p.builder().PExpireAtGTCompleted(key, millisecondsTimestamp), &boolCmd{})
}

var CommandPExpireAtLT commandPExpireAtLT

type commandPExpireAtLT string
type commandPExpireAtLTP struct{ p Pipeliner }

func (commandPExpireAtLT) String() string                    { return "PEXPIREAT LT" }
func (commandPExpireAtLT) Class() string                     { return "Generic" }
func (commandPExpireAtLT) RequireVersion() string            { return "7.0.0" }
func (commandPExpireAtLT) Forbid() bool                      { return false }
func (commandPExpireAtLT) WarningOnce() bool                 { return false }
func (commandPExpireAtLT) WarnVersion() string               { return "" }
func (commandPExpireAtLT) Warning() string                   { return "" }
func (commandPExpireAtLT) Instead() string                   { return "" }
func (commandPExpireAtLT) ETC() string                       { return "" }
func (commandPExpireAtLT) PR(b BaseCmd) BoolCmd              { return b.(BoolCmd) }
func (commandPExpireAtLT) P(p Pipeliner) commandPExpireAtLTP { return commandPExpireAtLTP{p} }
func (b commandPExpireAtLTP) Cmd(key string, millisecondsTimestamp time.Time) {
	b.p.cmd(b.p.builder().PExpireAtLTCompleted(key, millisecondsTimestamp), &boolCmd{})
}

var CommandPExpireAtNX commandPExpireAtNX

type commandPExpireAtNX string
type commandPExpireAtNXP struct{ p Pipeliner }

func (commandPExpireAtNX) String() string                    { return "PEXPIREAT NX" }
func (commandPExpireAtNX) Class() string                     { return "Generic" }
func (commandPExpireAtNX) RequireVersion() string            { return "7.0.0" }
func (commandPExpireAtNX) Forbid() bool                      { return false }
func (commandPExpireAtNX) WarningOnce() bool                 { return false }
func (commandPExpireAtNX) WarnVersion() string               { return "" }
func (commandPExpireAtNX) Warning() string                   { return "" }
func (commandPExpireAtNX) Instead() string                   { return "" }
func (commandPExpireAtNX) ETC() string                       { return "" }
func (commandPExpireAtNX) PR(b BaseCmd) BoolCmd              { return b.(BoolCmd) }
func (commandPExpireAtNX) P(p Pipeliner) commandPExpireAtNXP { return commandPExpireAtNXP{p} }
func (b commandPExpireAtNXP) Cmd(key string, millisecondsTimestamp time.Time) {
	b.p.cmd(b.p.builder().PExpireAtNXCompleted(key, millisecondsTimestamp), &boolCmd{})
}

var CommandPExpireAtXX commandPExpireAtXX

type commandPExpireAtXX string
type commandPExpireAtXXP struct{ p Pipeliner }

func (commandPExpireAtXX) String() string                    { return "PEXPIREAT XX" }
func (commandPExpireAtXX) Class() string                     { return "Generic" }
func (commandPExpireAtXX) RequireVersion() string            { return "7.0.0" }
func (commandPExpireAtXX) Forbid() bool                      { return false }
func (commandPExpireAtXX) WarningOnce() bool                 { return false }
func (commandPExpireAtXX) WarnVersion() string               { return "" }
func (commandPExpireAtXX) Warning() string                   { return "" }
func (commandPExpireAtXX) Instead() string                   { return "" }
func (commandPExpireAtXX) ETC() string                       { return "" }
func (commandPExpireAtXX) PR(b BaseCmd) BoolCmd              { return b.(BoolCmd) }
func (commandPExpireAtXX) P(p Pipeliner) commandPExpireAtXXP { return commandPExpireAtXXP{p} }
func (b commandPExpireAtXXP) Cmd(key string, millisecondsTimestamp time.Time) {
	b.p.cmd(b.p.builder().PExpireAtXXCompleted(key, millisecondsTimestamp), &boolCmd{})
}

var CommandPExpireGT commandPExpireGT

type commandPExpireGT string
type commandPExpireGTP struct{ p Pipeliner }

func (commandPExpireGT) String() string                  { return "PEXPIRE GT" }
func (commandPExpireGT) Class() string                   { return "Generic" }
func (commandPExpireGT) RequireVersion() string          { return "7.0.0" }
func (commandPExpireGT) Forbid() bool                    { return false }
func (commandPExpireGT) WarningOnce() bool               { return false }
func (commandPExpireGT) WarnVersion() string             { return "" }
func (commandPExpireGT) Warning() string                 { return "" }
func (commandPExpireGT) Instead() string                 { return "" }
func (commandPExpireGT) ETC() string                     { return "" }
func (commandPExpireGT) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandPExpireGT) P(p Pipeliner) commandPExpireGTP { return commandPExpireGTP{p} }
func (b commandPExpireGTP) Cmd(key string, milliseconds time.Duration) {
	b.p.cmd(b.p.builder().PExpireGTCompleted(key, milliseconds), &boolCmd{})
}

var CommandPExpireLT commandPExpireLT

type commandPExpireLT string
type commandPExpireLTP struct{ p Pipeliner }

func (commandPExpireLT) String() string                  { return "PEXPIRE LT" }
func (commandPExpireLT) Class() string                   { return "Generic" }
func (commandPExpireLT) RequireVersion() string          { return "7.0.0" }
func (commandPExpireLT) Forbid() bool                    { return false }
func (commandPExpireLT) WarningOnce() bool               { return false }
func (commandPExpireLT) WarnVersion() string             { return "" }
func (commandPExpireLT) Warning() string                 { return "" }
func (commandPExpireLT) Instead() string                 { return "" }
func (commandPExpireLT) ETC() string                     { return "" }
func (commandPExpireLT) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandPExpireLT) P(p Pipeliner) commandPExpireLTP { return commandPExpireLTP{p} }
func (b commandPExpireLTP) Cmd(key string, milliseconds time.Duration) {
	b.p.cmd(b.p.builder().PExpireLTCompleted(key, milliseconds), &boolCmd{})
}

var CommandPExpireNX commandPExpireNX

type commandPExpireNX string
type commandPExpireNXP struct{ p Pipeliner }

func (commandPExpireNX) String() string                  { return "PEXPIRE NX" }
func (commandPExpireNX) Class() string                   { return "Generic" }
func (commandPExpireNX) RequireVersion() string          { return "7.0.0" }
func (commandPExpireNX) Forbid() bool                    { return false }
func (commandPExpireNX) WarningOnce() bool               { return false }
func (commandPExpireNX) WarnVersion() string             { return "" }
func (commandPExpireNX) Warning() string                 { return "" }
func (commandPExpireNX) Instead() string                 { return "" }
func (commandPExpireNX) ETC() string                     { return "" }
func (commandPExpireNX) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandPExpireNX) P(p Pipeliner) commandPExpireNXP { return commandPExpireNXP{p} }
func (b commandPExpireNXP) Cmd(key string, milliseconds time.Duration) {
	b.p.cmd(b.p.builder().PExpireNXCompleted(key, milliseconds), &boolCmd{})
}

var CommandPExpireTime commandPExpireTime

type commandPExpireTime string
type commandPExpireTimeP struct{ p Pipeliner }

func (commandPExpireTime) String() string                    { return "PEXPIRETIME" }
func (commandPExpireTime) Class() string                     { return "Generic" }
func (commandPExpireTime) RequireVersion() string            { return "7.0.0" }
func (commandPExpireTime) Forbid() bool                      { return false }
func (commandPExpireTime) WarningOnce() bool                 { return false }
func (commandPExpireTime) WarnVersion() string               { return "" }
func (commandPExpireTime) Warning() string                   { return "" }
func (commandPExpireTime) Instead() string                   { return "" }
func (commandPExpireTime) ETC() string                       { return "" }
func (commandPExpireTime) PR(b BaseCmd) DurationCmd          { return b.(DurationCmd) }
func (commandPExpireTime) P(p Pipeliner) commandPExpireTimeP { return commandPExpireTimeP{p} }
func (b commandPExpireTimeP) Cmd(key string) {
	b.p.cmd(b.p.builder().PExpireTimeCompleted(key), &durationCmd{})
}

var CommandPExpireXX commandPExpireXX

type commandPExpireXX string
type commandPExpireXXP struct{ p Pipeliner }

func (commandPExpireXX) String() string                  { return "PEXPIRE XX" }
func (commandPExpireXX) Class() string                   { return "Generic" }
func (commandPExpireXX) RequireVersion() string          { return "7.0.0" }
func (commandPExpireXX) Forbid() bool                    { return false }
func (commandPExpireXX) WarningOnce() bool               { return false }
func (commandPExpireXX) WarnVersion() string             { return "" }
func (commandPExpireXX) Warning() string                 { return "" }
func (commandPExpireXX) Instead() string                 { return "" }
func (commandPExpireXX) ETC() string                     { return "" }
func (commandPExpireXX) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandPExpireXX) P(p Pipeliner) commandPExpireXXP { return commandPExpireXXP{p} }
func (b commandPExpireXXP) Cmd(key string, milliseconds time.Duration) {
	b.p.cmd(b.p.builder().PExpireXXCompleted(key, milliseconds), &boolCmd{})
}

var CommandPTTL commandPTTL

type commandPTTL string
type commandPTTLP struct{ p Pipeliner }

func (commandPTTL) String() string             { return "PTTL" }
func (commandPTTL) Class() string              { return "Generic" }
func (commandPTTL) RequireVersion() string     { return "2.6.0" }
func (commandPTTL) Forbid() bool               { return false }
func (commandPTTL) WarningOnce() bool          { return false }
func (commandPTTL) WarnVersion() string        { return "" }
func (commandPTTL) Warning() string            { return "" }
func (commandPTTL) Instead() string            { return "" }
func (commandPTTL) ETC() string                { return "" }
func (commandPTTL) PR(b BaseCmd) DurationCmd   { return b.(DurationCmd) }
func (commandPTTL) P(p Pipeliner) commandPTTLP { return commandPTTLP{p} }
func (b commandPTTLP) Cmd(key string) {
	b.p.cmd(b.p.builder().PTTLCompleted(key), &durationCmd{})
}

var CommandPersist commandPersist

type commandPersist string
type commandPersistP struct{ p Pipeliner }

func (commandPersist) String() string                { return "PERSIST" }
func (commandPersist) Class() string                 { return "Generic" }
func (commandPersist) RequireVersion() string        { return "2.2.0" }
func (commandPersist) Forbid() bool                  { return false }
func (commandPersist) WarningOnce() bool             { return false }
func (commandPersist) WarnVersion() string           { return "" }
func (commandPersist) Warning() string               { return "" }
func (commandPersist) Instead() string               { return "" }
func (commandPersist) ETC() string                   { return "" }
func (commandPersist) PR(b BaseCmd) BoolCmd          { return b.(BoolCmd) }
func (commandPersist) P(p Pipeliner) commandPersistP { return commandPersistP{p} }
func (b commandPersistP) Cmd(key string) {
	b.p.cmd(b.p.builder().PersistCompleted(key), &boolCmd{})
}

var CommandRandomKey commandRandomKey

type commandRandomKey string
type commandRandomKeyP struct{ p Pipeliner }

func (commandRandomKey) String() string                  { return "RANDOMKEY" }
func (commandRandomKey) Class() string                   { return "Generic" }
func (commandRandomKey) RequireVersion() string          { return "1.0.0" }
func (commandRandomKey) Forbid() bool                    { return false }
func (commandRandomKey) WarningOnce() bool               { return false }
func (commandRandomKey) WarnVersion() string             { return "" }
func (commandRandomKey) Warning() string                 { return "" }
func (commandRandomKey) Instead() string                 { return "" }
func (commandRandomKey) ETC() string                     { return "" }
func (commandRandomKey) PR(b BaseCmd) StringCmd          { return b.(StringCmd) }
func (commandRandomKey) P(p Pipeliner) commandRandomKeyP { return commandRandomKeyP{p} }
func (b commandRandomKeyP) Cmd() {
	b.p.cmd(b.p.builder().RandomKeyCompleted(), &stringCmd{})
}

var CommandRename commandRename

type commandRename string
type commandRenameP struct{ p Pipeliner }

func (commandRename) String() string               { return "RENAME" }
func (commandRename) Class() string                { return "Generic" }
func (commandRename) RequireVersion() string       { return "1.0.0" }
func (commandRename) Forbid() bool                 { return false }
func (commandRename) WarningOnce() bool            { return false }
func (commandRename) WarnVersion() string          { return "" }
func (commandRename) Warning() string              { return "" }
func (commandRename) Instead() string              { return "" }
func (commandRename) ETC() string                  { return "" }
func (commandRename) PR(b BaseCmd) StatusCmd       { return b.(StatusCmd) }
func (commandRename) P(p Pipeliner) commandRenameP { return commandRenameP{p} }
func (b commandRenameP) Cmd(key string, newkey string) {
	b.p.cmd(b.p.builder().RenameCompleted(key, newkey), &statusCmd{})
}

var CommandRenameNX commandRenameNX

type commandRenameNX string
type commandRenameNXP struct{ p Pipeliner }

func (commandRenameNX) String() string                 { return "RENAMENX" }
func (commandRenameNX) Class() string                  { return "Generic" }
func (commandRenameNX) RequireVersion() string         { return "1.0.0" }
func (commandRenameNX) Forbid() bool                   { return false }
func (commandRenameNX) WarningOnce() bool              { return false }
func (commandRenameNX) WarnVersion() string            { return "" }
func (commandRenameNX) Warning() string                { return "" }
func (commandRenameNX) Instead() string                { return "" }
func (commandRenameNX) ETC() string                    { return "" }
func (commandRenameNX) PR(b BaseCmd) BoolCmd           { return b.(BoolCmd) }
func (commandRenameNX) P(p Pipeliner) commandRenameNXP { return commandRenameNXP{p} }
func (b commandRenameNXP) Cmd(key string, newkey string) {
	b.p.cmd(b.p.builder().RenameNXCompleted(key, newkey), &boolCmd{})
}

var CommandRestore commandRestore

type commandRestore string
type commandRestoreP struct{ p Pipeliner }

func (commandRestore) String() string                { return "RESTORE" }
func (commandRestore) Class() string                 { return "Generic" }
func (commandRestore) RequireVersion() string        { return "2.6.0" }
func (commandRestore) Forbid() bool                  { return true }
func (commandRestore) WarningOnce() bool             { return false }
func (commandRestore) WarnVersion() string           { return "" }
func (commandRestore) Warning() string               { return "" }
func (commandRestore) Instead() string               { return "" }
func (commandRestore) ETC() string                   { return "" }
func (commandRestore) PR(b BaseCmd) StatusCmd        { return b.(StatusCmd) }
func (commandRestore) P(p Pipeliner) commandRestoreP { return commandRestoreP{p} }
func (b commandRestoreP) Cmd(key string, ttl time.Duration, serializedValue string) {
	b.p.cmd(b.p.builder().RestoreCompleted(key, ttl, serializedValue), &statusCmd{})
}

var CommandRestoreReplace commandRestoreReplace

type commandRestoreReplace string
type commandRestoreReplaceP struct{ p Pipeliner }

func (commandRestoreReplace) String() string                       { return "RESTORE REPLACE" }
func (commandRestoreReplace) Class() string                        { return "Generic" }
func (commandRestoreReplace) RequireVersion() string               { return "3.0.0" }
func (commandRestoreReplace) Forbid() bool                         { return true }
func (commandRestoreReplace) WarningOnce() bool                    { return false }
func (commandRestoreReplace) WarnVersion() string                  { return "" }
func (commandRestoreReplace) Warning() string                      { return "" }
func (commandRestoreReplace) Instead() string                      { return "" }
func (commandRestoreReplace) ETC() string                          { return "" }
func (commandRestoreReplace) PR(b BaseCmd) StatusCmd               { return b.(StatusCmd) }
func (commandRestoreReplace) P(p Pipeliner) commandRestoreReplaceP { return commandRestoreReplaceP{p} }
func (b commandRestoreReplaceP) Cmd(key string, ttl time.Duration, serializedValue string) {
	b.p.cmd(b.p.builder().RestoreReplaceCompleted(key, ttl, serializedValue), &statusCmd{})
}

var CommandScan commandScan

type commandScan string
type commandScanP struct{ p Pipeliner }

func (commandScan) String() string             { return "SCAN" }
func (commandScan) Class() string              { return "Generic" }
func (commandScan) RequireVersion() string     { return "2.8.0" }
func (commandScan) Forbid() bool               { return false }
func (commandScan) WarningOnce() bool          { return false }
func (commandScan) WarnVersion() string        { return "" }
func (commandScan) Warning() string            { return "" }
func (commandScan) Instead() string            { return "" }
func (commandScan) ETC() string                { return "" }
func (commandScan) PR(b BaseCmd) ScanCmd       { return b.(ScanCmd) }
func (commandScan) P(p Pipeliner) commandScanP { return commandScanP{p} }
func (b commandScanP) Cmd(cursor uint64, match string, count int64) {
	b.p.cmd(b.p.builder().ScanCompleted(cursor, match, count), &scanCmd{})
}

var CommandScanType commandScanType

type commandScanType string
type commandScanTypeP struct{ p Pipeliner }

func (commandScanType) String() string                 { return "SCAN TYPE" }
func (commandScanType) Class() string                  { return "Generic" }
func (commandScanType) RequireVersion() string         { return "6.0.0" }
func (commandScanType) Forbid() bool                   { return false }
func (commandScanType) WarningOnce() bool              { return false }
func (commandScanType) WarnVersion() string            { return "" }
func (commandScanType) Warning() string                { return "" }
func (commandScanType) Instead() string                { return "" }
func (commandScanType) ETC() string                    { return "" }
func (commandScanType) PR(b BaseCmd) ScanCmd           { return b.(ScanCmd) }
func (commandScanType) P(p Pipeliner) commandScanTypeP { return commandScanTypeP{p} }
func (b commandScanTypeP) Cmd(cursor uint64, match string, count int64, keyType string) {
	b.p.cmd(b.p.builder().ScanTypeCompleted(cursor, match, count, keyType), &scanCmd{})
}

var CommandSort commandSort

type commandSort string

func (commandSort) String() string         { return "SORT" }
func (commandSort) Class() string          { return "Generic" }
func (commandSort) RequireVersion() string { return "1.0.0" }
func (commandSort) Forbid() bool           { return true }
func (commandSort) WarningOnce() bool      { return false }
func (commandSort) WarnVersion() string    { return "" }
func (commandSort) Warning() string        { return "" }
func (commandSort) Instead() string        { return "" }
func (commandSort) ETC() string            { return "" }

var CommandSortRO commandSortRO

type commandSortRO string

func (commandSortRO) String() string         { return "SORT_RO" }
func (commandSortRO) Class() string          { return "Generic" }
func (commandSortRO) RequireVersion() string { return "7.0.0" }
func (commandSortRO) Forbid() bool           { return true }
func (commandSortRO) WarningOnce() bool      { return false }
func (commandSortRO) WarnVersion() string    { return "" }
func (commandSortRO) Warning() string        { return "" }
func (commandSortRO) Instead() string        { return "" }
func (commandSortRO) ETC() string            { return "" }

var CommandSortStore commandSortStore

type commandSortStore string

func (commandSortStore) String() string         { return "SORT STORE" }
func (commandSortStore) Class() string          { return "Generic" }
func (commandSortStore) RequireVersion() string { return "1.0.0" }
func (commandSortStore) Forbid() bool           { return true }
func (commandSortStore) WarningOnce() bool      { return false }
func (commandSortStore) WarnVersion() string    { return "" }
func (commandSortStore) Warning() string        { return "" }
func (commandSortStore) Instead() string        { return "" }
func (commandSortStore) ETC() string            { return "" }

var CommandTTL commandTTL

type commandTTL string
type commandTTLP struct{ p Pipeliner }

func (commandTTL) String() string            { return "TTL" }
func (commandTTL) Class() string             { return "Generic" }
func (commandTTL) RequireVersion() string    { return "1.0.0" }
func (commandTTL) Forbid() bool              { return false }
func (commandTTL) WarningOnce() bool         { return false }
func (commandTTL) WarnVersion() string       { return "" }
func (commandTTL) Warning() string           { return "" }
func (commandTTL) Instead() string           { return "" }
func (commandTTL) ETC() string               { return "" }
func (commandTTL) PR(b BaseCmd) DurationCmd  { return b.(DurationCmd) }
func (commandTTL) P(p Pipeliner) commandTTLP { return commandTTLP{p} }
func (b commandTTLP) Cmd(key string) {
	b.p.cmd(b.p.builder().TTLCompleted(key), &durationCmd{})
}

var CommandTouch commandTouch

type commandTouch string
type commandTouchP struct{ p Pipeliner }

func (commandTouch) String() string              { return "TOUCH" }
func (commandTouch) Class() string               { return "Generic" }
func (commandTouch) RequireVersion() string      { return "3.2.1" }
func (commandTouch) Forbid() bool                { return false }
func (commandTouch) WarningOnce() bool           { return false }
func (commandTouch) WarnVersion() string         { return "" }
func (commandTouch) Warning() string             { return "" }
func (commandTouch) Instead() string             { return "" }
func (commandTouch) ETC() string                 { return "" }
func (commandTouch) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandTouch) P(p Pipeliner) commandTouchP { return commandTouchP{p} }
func (b commandTouchP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().TouchCompleted(keys...), &intCmd{})
}

var CommandType commandType

type commandType string
type commandTypeP struct{ p Pipeliner }

func (commandType) String() string             { return "TYPE" }
func (commandType) Class() string              { return "Generic" }
func (commandType) RequireVersion() string     { return "1.0.0" }
func (commandType) Forbid() bool               { return false }
func (commandType) WarningOnce() bool          { return false }
func (commandType) WarnVersion() string        { return "" }
func (commandType) Warning() string            { return "" }
func (commandType) Instead() string            { return "" }
func (commandType) ETC() string                { return "" }
func (commandType) PR(b BaseCmd) StatusCmd     { return b.(StatusCmd) }
func (commandType) P(p Pipeliner) commandTypeP { return commandTypeP{p} }
func (b commandTypeP) Cmd(key string) {
	b.p.cmd(b.p.builder().TypeCompleted(key), &statusCmd{})
}

var CommandUnlink commandUnlink

type commandUnlink string
type commandUnlinkP struct{ p Pipeliner }

func (commandUnlink) String() string               { return "UNLINK" }
func (commandUnlink) Class() string                { return "Generic" }
func (commandUnlink) RequireVersion() string       { return "4.0.0" }
func (commandUnlink) Forbid() bool                 { return false }
func (commandUnlink) WarningOnce() bool            { return false }
func (commandUnlink) WarnVersion() string          { return "" }
func (commandUnlink) Warning() string              { return "" }
func (commandUnlink) Instead() string              { return "" }
func (commandUnlink) ETC() string                  { return "" }
func (commandUnlink) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandUnlink) P(p Pipeliner) commandUnlinkP { return commandUnlinkP{p} }
func (b commandUnlinkP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().UnlinkCompleted(keys...), &intCmd{})
}
