// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandPSubscribe commandPSubscribe

type commandPSubscribe string

func (commandPSubscribe) String() string         { return "PSUBSCRIBE" }
func (commandPSubscribe) Class() string          { return "PubSub" }
func (commandPSubscribe) RequireVersion() string { return "2.0.0" }
func (commandPSubscribe) Forbid() bool           { return false }
func (commandPSubscribe) WarningOnce() bool      { return false }
func (commandPSubscribe) WarnVersion() string    { return "" }
func (commandPSubscribe) Warning() string        { return "" }
func (commandPSubscribe) Instead() string        { return "" }
func (commandPSubscribe) ETC() string            { return "" }

var CommandPUnsubscribe commandPUnsubscribe

type commandPUnsubscribe string

func (commandPUnsubscribe) String() string         { return "PUNSUBSCRIBE" }
func (commandPUnsubscribe) Class() string          { return "PubSub" }
func (commandPUnsubscribe) RequireVersion() string { return "2.0.0" }
func (commandPUnsubscribe) Forbid() bool           { return false }
func (commandPUnsubscribe) WarningOnce() bool      { return false }
func (commandPUnsubscribe) WarnVersion() string    { return "" }
func (commandPUnsubscribe) Warning() string        { return "" }
func (commandPUnsubscribe) Instead() string        { return "" }
func (commandPUnsubscribe) ETC() string            { return "" }

var CommandPubSubChannels commandPubSubChannels

type commandPubSubChannels string
type commandPubSubChannelsP struct{ p Pipeliner }

func (commandPubSubChannels) String() string                       { return "PUBSUB CHANNELS" }
func (commandPubSubChannels) Class() string                        { return "PubSub" }
func (commandPubSubChannels) RequireVersion() string               { return "2.8.0" }
func (commandPubSubChannels) Forbid() bool                         { return false }
func (commandPubSubChannels) WarningOnce() bool                    { return false }
func (commandPubSubChannels) WarnVersion() string                  { return "" }
func (commandPubSubChannels) Warning() string                      { return "" }
func (commandPubSubChannels) Instead() string                      { return "" }
func (commandPubSubChannels) ETC() string                          { return "" }
func (commandPubSubChannels) PR(b BaseCmd) StringSliceCmd          { return b.(StringSliceCmd) }
func (commandPubSubChannels) P(p Pipeliner) commandPubSubChannelsP { return commandPubSubChannelsP{p} }
func (b commandPubSubChannelsP) Cmd(pattern string) {
	b.p.cmd(b.p.builder().PubSubChannelsCompleted(pattern), &stringSliceCmd{})
}

var CommandPubSubNumPat commandPubSubNumPat

type commandPubSubNumPat string
type commandPubSubNumPatP struct{ p Pipeliner }

func (commandPubSubNumPat) String() string                     { return "PUBSUB NUMPAT" }
func (commandPubSubNumPat) Class() string                      { return "PubSub" }
func (commandPubSubNumPat) RequireVersion() string             { return "2.8.0" }
func (commandPubSubNumPat) Forbid() bool                       { return false }
func (commandPubSubNumPat) WarningOnce() bool                  { return false }
func (commandPubSubNumPat) WarnVersion() string                { return "" }
func (commandPubSubNumPat) Warning() string                    { return "" }
func (commandPubSubNumPat) Instead() string                    { return "" }
func (commandPubSubNumPat) ETC() string                        { return "" }
func (commandPubSubNumPat) PR(b BaseCmd) IntCmd                { return b.(IntCmd) }
func (commandPubSubNumPat) P(p Pipeliner) commandPubSubNumPatP { return commandPubSubNumPatP{p} }
func (b commandPubSubNumPatP) Cmd() {
	b.p.cmd(b.p.builder().PubSubNumPatCompleted(), &intCmd{})
}

var CommandPubSubNumSub commandPubSubNumSub

type commandPubSubNumSub string
type commandPubSubNumSubP struct{ p Pipeliner }

func (commandPubSubNumSub) String() string                     { return "PUBSUB NUMSUB" }
func (commandPubSubNumSub) Class() string                      { return "PubSub" }
func (commandPubSubNumSub) RequireVersion() string             { return "2.8.0" }
func (commandPubSubNumSub) Forbid() bool                       { return false }
func (commandPubSubNumSub) WarningOnce() bool                  { return false }
func (commandPubSubNumSub) WarnVersion() string                { return "" }
func (commandPubSubNumSub) Warning() string                    { return "" }
func (commandPubSubNumSub) Instead() string                    { return "" }
func (commandPubSubNumSub) ETC() string                        { return "" }
func (commandPubSubNumSub) PR(b BaseCmd) StringIntMapCmd       { return b.(StringIntMapCmd) }
func (commandPubSubNumSub) P(p Pipeliner) commandPubSubNumSubP { return commandPubSubNumSubP{p} }
func (b commandPubSubNumSubP) Cmd(channels ...string) {
	b.p.cmd(b.p.builder().PubSubNumSubCompleted(channels...), &stringIntMapCmd{})
}

var CommandPubSubShardChannels commandPubSubShardChannels

type commandPubSubShardChannels string
type commandPubSubShardChannelsP struct{ p Pipeliner }

func (commandPubSubShardChannels) String() string              { return "PUBSUB SHARDCHANNELS" }
func (commandPubSubShardChannels) Class() string               { return "PubSub" }
func (commandPubSubShardChannels) RequireVersion() string      { return "7.0.0" }
func (commandPubSubShardChannels) Forbid() bool                { return false }
func (commandPubSubShardChannels) WarningOnce() bool           { return false }
func (commandPubSubShardChannels) WarnVersion() string         { return "" }
func (commandPubSubShardChannels) Warning() string             { return "" }
func (commandPubSubShardChannels) Instead() string             { return "" }
func (commandPubSubShardChannels) ETC() string                 { return "" }
func (commandPubSubShardChannels) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandPubSubShardChannels) P(p Pipeliner) commandPubSubShardChannelsP {
	return commandPubSubShardChannelsP{p}
}
func (b commandPubSubShardChannelsP) Cmd(pattern string) {
	b.p.cmd(b.p.builder().PubSubShardChannelsCompleted(pattern), &stringSliceCmd{})
}

var CommandPubSubShardNumSub commandPubSubShardNumSub

type commandPubSubShardNumSub string
type commandPubSubShardNumSubP struct{ p Pipeliner }

func (commandPubSubShardNumSub) String() string               { return "PUBSUB SHARDNUMSUB" }
func (commandPubSubShardNumSub) Class() string                { return "PubSub" }
func (commandPubSubShardNumSub) RequireVersion() string       { return "7.0.0" }
func (commandPubSubShardNumSub) Forbid() bool                 { return false }
func (commandPubSubShardNumSub) WarningOnce() bool            { return false }
func (commandPubSubShardNumSub) WarnVersion() string          { return "" }
func (commandPubSubShardNumSub) Warning() string              { return "" }
func (commandPubSubShardNumSub) Instead() string              { return "" }
func (commandPubSubShardNumSub) ETC() string                  { return "" }
func (commandPubSubShardNumSub) PR(b BaseCmd) StringIntMapCmd { return b.(StringIntMapCmd) }
func (commandPubSubShardNumSub) P(p Pipeliner) commandPubSubShardNumSubP {
	return commandPubSubShardNumSubP{p}
}
func (b commandPubSubShardNumSubP) Cmd(channels ...string) {
	b.p.cmd(b.p.builder().PubSubShardNumSubCompleted(channels...), &stringIntMapCmd{})
}

var CommandPublish commandPublish

type commandPublish string
type commandPublishP struct{ p Pipeliner }

func (commandPublish) String() string                { return "PUBLISH" }
func (commandPublish) Class() string                 { return "PubSub" }
func (commandPublish) RequireVersion() string        { return "2.0.0" }
func (commandPublish) Forbid() bool                  { return false }
func (commandPublish) WarningOnce() bool             { return false }
func (commandPublish) WarnVersion() string           { return "" }
func (commandPublish) Warning() string               { return "" }
func (commandPublish) Instead() string               { return "" }
func (commandPublish) ETC() string                   { return "" }
func (commandPublish) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandPublish) P(p Pipeliner) commandPublishP { return commandPublishP{p} }
func (b commandPublishP) Cmd(channel string, message any) {
	b.p.cmd(b.p.builder().PublishCompleted(channel, message), &intCmd{})
}

var CommandSPublish commandSPublish

type commandSPublish string
type commandSPublishP struct{ p Pipeliner }

func (commandSPublish) String() string                 { return "SPUBLISH" }
func (commandSPublish) Class() string                  { return "PubSub" }
func (commandSPublish) RequireVersion() string         { return "7.0.0" }
func (commandSPublish) Forbid() bool                   { return false }
func (commandSPublish) WarningOnce() bool              { return false }
func (commandSPublish) WarnVersion() string            { return "" }
func (commandSPublish) Warning() string                { return "" }
func (commandSPublish) Instead() string                { return "" }
func (commandSPublish) ETC() string                    { return "" }
func (commandSPublish) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandSPublish) P(p Pipeliner) commandSPublishP { return commandSPublishP{p} }
func (b commandSPublishP) Cmd(channel string, message any) {
	b.p.cmd(b.p.builder().SPublishCompleted(channel, message), &intCmd{})
}

var CommandSSubscribe commandSSubscribe

type commandSSubscribe string

func (commandSSubscribe) String() string         { return "SSUBSCRIBE" }
func (commandSSubscribe) Class() string          { return "PubSub" }
func (commandSSubscribe) RequireVersion() string { return "7.0.0" }
func (commandSSubscribe) Forbid() bool           { return false }
func (commandSSubscribe) WarningOnce() bool      { return false }
func (commandSSubscribe) WarnVersion() string    { return "" }
func (commandSSubscribe) Warning() string        { return "" }
func (commandSSubscribe) Instead() string        { return "" }
func (commandSSubscribe) ETC() string            { return "" }

var CommandSUnsubscribe commandSUnsubscribe

type commandSUnsubscribe string

func (commandSUnsubscribe) String() string         { return "SUNSUBSCRIBE" }
func (commandSUnsubscribe) Class() string          { return "PubSub" }
func (commandSUnsubscribe) RequireVersion() string { return "7.0.0" }
func (commandSUnsubscribe) Forbid() bool           { return false }
func (commandSUnsubscribe) WarningOnce() bool      { return false }
func (commandSUnsubscribe) WarnVersion() string    { return "" }
func (commandSUnsubscribe) Warning() string        { return "" }
func (commandSUnsubscribe) Instead() string        { return "" }
func (commandSUnsubscribe) ETC() string            { return "" }

var CommandSubscribe commandSubscribe

type commandSubscribe string

func (commandSubscribe) String() string         { return "SUBSCRIBE" }
func (commandSubscribe) Class() string          { return "PubSub" }
func (commandSubscribe) RequireVersion() string { return "2.0.0" }
func (commandSubscribe) Forbid() bool           { return false }
func (commandSubscribe) WarningOnce() bool      { return false }
func (commandSubscribe) WarnVersion() string    { return "" }
func (commandSubscribe) Warning() string        { return "" }
func (commandSubscribe) Instead() string        { return "" }
func (commandSubscribe) ETC() string            { return "" }

var CommandUnsubscribe commandUnsubscribe

type commandUnsubscribe string

func (commandUnsubscribe) String() string         { return "UNSUBSCRIBE" }
func (commandUnsubscribe) Class() string          { return "PubSub" }
func (commandUnsubscribe) RequireVersion() string { return "2.0.0" }
func (commandUnsubscribe) Forbid() bool           { return false }
func (commandUnsubscribe) WarningOnce() bool      { return false }
func (commandUnsubscribe) WarnVersion() string    { return "" }
func (commandUnsubscribe) Warning() string        { return "" }
func (commandUnsubscribe) Instead() string        { return "" }
func (commandUnsubscribe) ETC() string            { return "" }
