// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandGeoAdd commandGeoAdd

type commandGeoAdd string
type commandGeoAddP struct{ p Pipeliner }

func (commandGeoAdd) String() string               { return "GEOADD" }
func (commandGeoAdd) Class() string                { return "Geospatial" }
func (commandGeoAdd) RequireVersion() string       { return "3.2.0" }
func (commandGeoAdd) Forbid() bool                 { return false }
func (commandGeoAdd) WarningOnce() bool            { return false }
func (commandGeoAdd) WarnVersion() string          { return "" }
func (commandGeoAdd) Warning() string              { return "" }
func (commandGeoAdd) Instead() string              { return "" }
func (commandGeoAdd) ETC() string                  { return "" }
func (commandGeoAdd) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandGeoAdd) P(p Pipeliner) commandGeoAddP { return commandGeoAddP{p} }
func (b commandGeoAddP) Cmd(key string, geoLocation ...GeoLocation) {
	b.p.cmd(b.p.builder().GeoAddCompleted(key, geoLocation...), &intCmd{})
}

var CommandGeoDist commandGeoDist

type commandGeoDist string
type commandGeoDistP struct{ p Pipeliner }

func (commandGeoDist) String() string                { return "GEODIST" }
func (commandGeoDist) Class() string                 { return "Geospatial" }
func (commandGeoDist) RequireVersion() string        { return "3.2.0" }
func (commandGeoDist) Forbid() bool                  { return false }
func (commandGeoDist) WarningOnce() bool             { return false }
func (commandGeoDist) WarnVersion() string           { return "" }
func (commandGeoDist) Warning() string               { return "" }
func (commandGeoDist) Instead() string               { return "" }
func (commandGeoDist) ETC() string                   { return "" }
func (commandGeoDist) PR(b BaseCmd) FloatCmd         { return b.(FloatCmd) }
func (commandGeoDist) P(p Pipeliner) commandGeoDistP { return commandGeoDistP{p} }
func (b commandGeoDistP) Cmd(key string, member1 string, member2 string, unit string) {
	b.p.cmd(b.p.builder().GeoDistCompleted(key, member1, member2, unit), &floatCmd{})
}

var CommandGeoHash commandGeoHash

type commandGeoHash string
type commandGeoHashP struct{ p Pipeliner }

func (commandGeoHash) String() string                { return "GEOHASH" }
func (commandGeoHash) Class() string                 { return "Geospatial" }
func (commandGeoHash) RequireVersion() string        { return "3.2.0" }
func (commandGeoHash) Forbid() bool                  { return false }
func (commandGeoHash) WarningOnce() bool             { return false }
func (commandGeoHash) WarnVersion() string           { return "" }
func (commandGeoHash) Warning() string               { return "" }
func (commandGeoHash) Instead() string               { return "" }
func (commandGeoHash) ETC() string                   { return "" }
func (commandGeoHash) PR(b BaseCmd) StringSliceCmd   { return b.(StringSliceCmd) }
func (commandGeoHash) P(p Pipeliner) commandGeoHashP { return commandGeoHashP{p} }
func (b commandGeoHashP) Cmd(key string, members ...string) {
	b.p.cmd(b.p.builder().GeoHashCompleted(key, members...), &stringSliceCmd{})
}

var CommandGeoPos commandGeoPos

type commandGeoPos string
type commandGeoPosP struct{ p Pipeliner }

func (commandGeoPos) String() string               { return "GEOPOS" }
func (commandGeoPos) Class() string                { return "Geospatial" }
func (commandGeoPos) RequireVersion() string       { return "3.2.0" }
func (commandGeoPos) Forbid() bool                 { return false }
func (commandGeoPos) WarningOnce() bool            { return false }
func (commandGeoPos) WarnVersion() string          { return "" }
func (commandGeoPos) Warning() string              { return "" }
func (commandGeoPos) Instead() string              { return "" }
func (commandGeoPos) ETC() string                  { return "" }
func (commandGeoPos) PR(b BaseCmd) GeoPosCmd       { return b.(GeoPosCmd) }
func (commandGeoPos) P(p Pipeliner) commandGeoPosP { return commandGeoPosP{p} }
func (b commandGeoPosP) Cmd(key string, members ...string) {
	b.p.cmd(b.p.builder().GeoPosCompleted(key, members...), &geoPosCmd{})
}

var CommandGeoRadiusByMemberRO commandGeoRadiusByMemberRO

type commandGeoRadiusByMemberRO string
type commandGeoRadiusByMemberROP struct{ p Pipeliner }

func (commandGeoRadiusByMemberRO) String() string         { return "GEORADIUSBYMEMBER_RO" }
func (commandGeoRadiusByMemberRO) Class() string          { return "Geospatial" }
func (commandGeoRadiusByMemberRO) RequireVersion() string { return "3.2.10" }
func (commandGeoRadiusByMemberRO) Forbid() bool           { return false }
func (commandGeoRadiusByMemberRO) WarningOnce() bool      { return false }
func (commandGeoRadiusByMemberRO) WarnVersion() string    { return "6.2.0" }
func (commandGeoRadiusByMemberRO) Warning() string        { return commandGeoRadiusByMemberROWarning }
func (commandGeoRadiusByMemberRO) Instead() string        { return "GeoSearch" }
func (commandGeoRadiusByMemberRO) ETC() string {
	return "client.GeoSearch(ctx, key, redisson.GeoSearchQuery{Member: member, Radius: radius, BoxUnit: <redisson.M | redisson.KM | redisson.FT | redisson.MI>})"
}
func (commandGeoRadiusByMemberRO) PR(b BaseCmd) GeoLocationCmd { return b.(GeoLocationCmd) }
func (commandGeoRadiusByMemberRO) P(p Pipeliner) commandGeoRadiusByMemberROP {
	return commandGeoRadiusByMemberROP{p}
}
func (b commandGeoRadiusByMemberROP) Cmd(key string, member string, query GeoRadiusQuery) {
	b.p.cmd(b.p.builder().GeoRadiusByMemberCompleted(key, member, query), &geoLocationCmd{})
}

var CommandGeoRadiusByMemberStore commandGeoRadiusByMemberStore

type commandGeoRadiusByMemberStore string
type commandGeoRadiusByMemberStoreP struct{ p Pipeliner }

func (commandGeoRadiusByMemberStore) String() string         { return "GEORADIUSBYMEMBER" }
func (commandGeoRadiusByMemberStore) Class() string          { return "Geospatial" }
func (commandGeoRadiusByMemberStore) RequireVersion() string { return "3.2.0" }
func (commandGeoRadiusByMemberStore) Forbid() bool           { return false }
func (commandGeoRadiusByMemberStore) WarningOnce() bool      { return false }
func (commandGeoRadiusByMemberStore) WarnVersion() string    { return "6.2.0" }
func (commandGeoRadiusByMemberStore) Warning() string        { return commandGeoRadiusByMemberStoreWarning }
func (commandGeoRadiusByMemberStore) Instead() string        { return "GeoSearchStore" }
func (commandGeoRadiusByMemberStore) ETC() string {
	return "client.GeoSearchStore(ctx, key, redisson.GeoSearchQuery{Member: member, Radius: radius, BoxUnit: <redisson.M | redisson.KM | redisson.FT | redisson.MI>})"
}
func (commandGeoRadiusByMemberStore) PR(b BaseCmd) IntCmd { return b.(IntCmd) }
func (commandGeoRadiusByMemberStore) P(p Pipeliner) commandGeoRadiusByMemberStoreP {
	return commandGeoRadiusByMemberStoreP{p}
}
func (b commandGeoRadiusByMemberStoreP) Cmd(key string, member string, query GeoRadiusQuery) {
	b.p.cmd(b.p.builder().GeoRadiusByMemberStoreCompleted(key, member, query), &intCmd{})
}

var CommandGeoRadiusRO commandGeoRadiusRO

type commandGeoRadiusRO string
type commandGeoRadiusROP struct{ p Pipeliner }

func (commandGeoRadiusRO) String() string         { return "GEORADIUS_RO" }
func (commandGeoRadiusRO) Class() string          { return "Geospatial" }
func (commandGeoRadiusRO) RequireVersion() string { return "3.2.10" }
func (commandGeoRadiusRO) Forbid() bool           { return false }
func (commandGeoRadiusRO) WarningOnce() bool      { return false }
func (commandGeoRadiusRO) WarnVersion() string    { return "6.2.0" }
func (commandGeoRadiusRO) Warning() string        { return commandGeoRadiusROWarning }
func (commandGeoRadiusRO) Instead() string        { return "GeoSearch" }
func (commandGeoRadiusRO) ETC() string {
	return "client.GeoSearch(ctx, key, redisson.GeoSearchQuery{Longitude: longitude, Latitude: latitude, Radius: radius, BoxUnit: <redisson.M | redisson.KM | redisson.FT | redisson.MI>})"
}
func (commandGeoRadiusRO) PR(b BaseCmd) GeoLocationCmd       { return b.(GeoLocationCmd) }
func (commandGeoRadiusRO) P(p Pipeliner) commandGeoRadiusROP { return commandGeoRadiusROP{p} }
func (b commandGeoRadiusROP) Cmd(key string, longitude float64, latitude float64, query GeoRadiusQuery) {
	b.p.cmd(b.p.builder().GeoRadiusCompleted(key, longitude, latitude, query), &geoLocationCmd{})
}

var CommandGeoRadiusStore commandGeoRadiusStore

type commandGeoRadiusStore string
type commandGeoRadiusStoreP struct{ p Pipeliner }

func (commandGeoRadiusStore) String() string         { return "GEORADIUS" }
func (commandGeoRadiusStore) Class() string          { return "Geospatial" }
func (commandGeoRadiusStore) RequireVersion() string { return "3.2.0" }
func (commandGeoRadiusStore) Forbid() bool           { return false }
func (commandGeoRadiusStore) WarningOnce() bool      { return false }
func (commandGeoRadiusStore) WarnVersion() string    { return "6.2.0" }
func (commandGeoRadiusStore) Warning() string        { return commandGeoRadiusStoreWarning }
func (commandGeoRadiusStore) Instead() string        { return "GeoSearchStore" }
func (commandGeoRadiusStore) ETC() string {
	return "client.GeoSearchStore(ctx, key, redisson.GeoSearchQuery{Longitude: longitude, Latitude: latitude, Radius: radius, BoxUnit: <redisson.M | redisson.KM | redisson.FT | redisson.MI>})"
}
func (commandGeoRadiusStore) PR(b BaseCmd) IntCmd                  { return b.(IntCmd) }
func (commandGeoRadiusStore) P(p Pipeliner) commandGeoRadiusStoreP { return commandGeoRadiusStoreP{p} }
func (b commandGeoRadiusStoreP) Cmd(key string, longitude float64, latitude float64, query GeoRadiusQuery) {
	b.p.cmd(b.p.builder().GeoRadiusStoreCompleted(key, longitude, latitude, query), &intCmd{})
}

var CommandGeoSearch commandGeoSearch

type commandGeoSearch string
type commandGeoSearchP struct{ p Pipeliner }

func (commandGeoSearch) String() string                  { return "GEOSEARCH" }
func (commandGeoSearch) Class() string                   { return "Geospatial" }
func (commandGeoSearch) RequireVersion() string          { return "6.2.0" }
func (commandGeoSearch) Forbid() bool                    { return false }
func (commandGeoSearch) WarningOnce() bool               { return false }
func (commandGeoSearch) WarnVersion() string             { return "" }
func (commandGeoSearch) Warning() string                 { return "" }
func (commandGeoSearch) Instead() string                 { return "" }
func (commandGeoSearch) ETC() string                     { return "" }
func (commandGeoSearch) PR(b BaseCmd) StringSliceCmd     { return b.(StringSliceCmd) }
func (commandGeoSearch) P(p Pipeliner) commandGeoSearchP { return commandGeoSearchP{p} }
func (b commandGeoSearchP) Cmd(key string, q GeoSearchQuery) {
	b.p.cmd(b.p.builder().GeoSearchCompleted(key, q), &stringSliceCmd{})
}

var CommandGeoSearchLocation commandGeoSearchLocation

type commandGeoSearchLocation string
type commandGeoSearchLocationP struct{ p Pipeliner }

func (commandGeoSearchLocation) String() string              { return "GEOSEARCH" }
func (commandGeoSearchLocation) Class() string               { return "Geospatial" }
func (commandGeoSearchLocation) RequireVersion() string      { return "6.2.0" }
func (commandGeoSearchLocation) Forbid() bool                { return false }
func (commandGeoSearchLocation) WarningOnce() bool           { return false }
func (commandGeoSearchLocation) WarnVersion() string         { return "" }
func (commandGeoSearchLocation) Warning() string             { return "" }
func (commandGeoSearchLocation) Instead() string             { return "" }
func (commandGeoSearchLocation) ETC() string                 { return "" }
func (commandGeoSearchLocation) PR(b BaseCmd) GeoLocationCmd { return b.(GeoLocationCmd) }
func (commandGeoSearchLocation) P(p Pipeliner) commandGeoSearchLocationP {
	return commandGeoSearchLocationP{p}
}
func (b commandGeoSearchLocationP) Cmd(key string, q GeoSearchLocationQuery) {
	b.p.cmd(b.p.builder().GeoSearchLocationCompleted(key, q), &geoLocationCmd{})
}

var CommandGeoSearchStore commandGeoSearchStore

type commandGeoSearchStore string
type commandGeoSearchStoreP struct{ p Pipeliner }

func (commandGeoSearchStore) String() string                       { return "GEOSEARCHSTORE" }
func (commandGeoSearchStore) Class() string                        { return "Geospatial" }
func (commandGeoSearchStore) RequireVersion() string               { return "6.2.0" }
func (commandGeoSearchStore) Forbid() bool                         { return false }
func (commandGeoSearchStore) WarningOnce() bool                    { return false }
func (commandGeoSearchStore) WarnVersion() string                  { return "" }
func (commandGeoSearchStore) Warning() string                      { return "" }
func (commandGeoSearchStore) Instead() string                      { return "" }
func (commandGeoSearchStore) ETC() string                          { return "" }
func (commandGeoSearchStore) PR(b BaseCmd) IntCmd                  { return b.(IntCmd) }
func (commandGeoSearchStore) P(p Pipeliner) commandGeoSearchStoreP { return commandGeoSearchStoreP{p} }
func (b commandGeoSearchStoreP) Cmd(src string, dest string, q GeoSearchStoreQuery) {
	b.p.cmd(b.p.builder().GeoSearchStoreCompleted(src, dest, q), &intCmd{})
}
