// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

import (
	"time"
)

var CommandHDel commandHDel

type commandHDel string
type commandHDelP struct{ p Pipeliner }

func (commandHDel) String() string             { return "HDEL" }
func (commandHDel) Class() string              { return "Hash" }
func (commandHDel) RequireVersion() string     { return "2.0.0" }
func (commandHDel) Forbid() bool               { return false }
func (commandHDel) WarningOnce() bool          { return false }
func (commandHDel) WarnVersion() string        { return "" }
func (commandHDel) Warning() string            { return "" }
func (commandHDel) Instead() string            { return "" }
func (commandHDel) ETC() string                { return "" }
func (commandHDel) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandHDel) P(p Pipeliner) commandHDelP { return commandHDelP{p} }
func (b commandHDelP) Cmd(key string, field string) {
	b.p.cmd(b.p.builder().HDelCompleted(key, field), &intCmd{})
}

var CommandHExists commandHExists

type commandHExists string
type commandHExistsP struct{ p Pipeliner }

func (commandHExists) String() string                { return "HEXISTS" }
func (commandHExists) Class() string                 { return "Hash" }
func (commandHExists) RequireVersion() string        { return "2.0.0" }
func (commandHExists) Forbid() bool                  { return false }
func (commandHExists) WarningOnce() bool             { return false }
func (commandHExists) WarnVersion() string           { return "" }
func (commandHExists) Warning() string               { return "" }
func (commandHExists) Instead() string               { return "" }
func (commandHExists) ETC() string                   { return "" }
func (commandHExists) PR(b BaseCmd) BoolCmd          { return b.(BoolCmd) }
func (commandHExists) P(p Pipeliner) commandHExistsP { return commandHExistsP{p} }
func (b commandHExistsP) Cmd(key string, field string) {
	b.p.cmd(b.p.builder().HExistsCompleted(key, field), &boolCmd{})
}

var CommandHExpire commandHExpire

type commandHExpire string
type commandHExpireP struct{ p Pipeliner }

func (commandHExpire) String() string                { return "HEXPIRE" }
func (commandHExpire) Class() string                 { return "Hash" }
func (commandHExpire) RequireVersion() string        { return "7.4.0" }
func (commandHExpire) Forbid() bool                  { return false }
func (commandHExpire) WarningOnce() bool             { return false }
func (commandHExpire) WarnVersion() string           { return "" }
func (commandHExpire) Warning() string               { return "" }
func (commandHExpire) Instead() string               { return "" }
func (commandHExpire) ETC() string                   { return "" }
func (commandHExpire) PR(b BaseCmd) IntSliceCmd      { return b.(IntSliceCmd) }
func (commandHExpire) P(p Pipeliner) commandHExpireP { return commandHExpireP{p} }
func (b commandHExpireP) Cmd(key string, seconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HExpireCompleted(key, seconds, fields...), &intSliceCmd{})
}

var CommandHExpireAt commandHExpireAt

type commandHExpireAt string
type commandHExpireAtP struct{ p Pipeliner }

func (commandHExpireAt) String() string                  { return "HEXPIREAT" }
func (commandHExpireAt) Class() string                   { return "Hash" }
func (commandHExpireAt) RequireVersion() string          { return "7.4.0" }
func (commandHExpireAt) Forbid() bool                    { return false }
func (commandHExpireAt) WarningOnce() bool               { return false }
func (commandHExpireAt) WarnVersion() string             { return "" }
func (commandHExpireAt) Warning() string                 { return "" }
func (commandHExpireAt) Instead() string                 { return "" }
func (commandHExpireAt) ETC() string                     { return "" }
func (commandHExpireAt) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandHExpireAt) P(p Pipeliner) commandHExpireAtP { return commandHExpireAtP{p} }
func (b commandHExpireAtP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HExpireAtCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHExpireAtGT commandHExpireAtGT

type commandHExpireAtGT string
type commandHExpireAtGTP struct{ p Pipeliner }

func (commandHExpireAtGT) String() string                    { return "HEXPIREAT GT" }
func (commandHExpireAtGT) Class() string                     { return "Hash" }
func (commandHExpireAtGT) RequireVersion() string            { return "7.4.0" }
func (commandHExpireAtGT) Forbid() bool                      { return false }
func (commandHExpireAtGT) WarningOnce() bool                 { return false }
func (commandHExpireAtGT) WarnVersion() string               { return "" }
func (commandHExpireAtGT) Warning() string                   { return "" }
func (commandHExpireAtGT) Instead() string                   { return "" }
func (commandHExpireAtGT) ETC() string                       { return "" }
func (commandHExpireAtGT) PR(b BaseCmd) IntSliceCmd          { return b.(IntSliceCmd) }
func (commandHExpireAtGT) P(p Pipeliner) commandHExpireAtGTP { return commandHExpireAtGTP{p} }
func (b commandHExpireAtGTP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HExpireAtGTCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHExpireAtLT commandHExpireAtLT

type commandHExpireAtLT string
type commandHExpireAtLTP struct{ p Pipeliner }

func (commandHExpireAtLT) String() string                    { return "HEXPIREAT LT" }
func (commandHExpireAtLT) Class() string                     { return "Hash" }
func (commandHExpireAtLT) RequireVersion() string            { return "7.4.0" }
func (commandHExpireAtLT) Forbid() bool                      { return false }
func (commandHExpireAtLT) WarningOnce() bool                 { return false }
func (commandHExpireAtLT) WarnVersion() string               { return "" }
func (commandHExpireAtLT) Warning() string                   { return "" }
func (commandHExpireAtLT) Instead() string                   { return "" }
func (commandHExpireAtLT) ETC() string                       { return "" }
func (commandHExpireAtLT) PR(b BaseCmd) IntSliceCmd          { return b.(IntSliceCmd) }
func (commandHExpireAtLT) P(p Pipeliner) commandHExpireAtLTP { return commandHExpireAtLTP{p} }
func (b commandHExpireAtLTP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HExpireAtLTCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHExpireAtNX commandHExpireAtNX

type commandHExpireAtNX string
type commandHExpireAtNXP struct{ p Pipeliner }

func (commandHExpireAtNX) String() string                    { return "HEXPIREAT NX" }
func (commandHExpireAtNX) Class() string                     { return "Hash" }
func (commandHExpireAtNX) RequireVersion() string            { return "7.4.0" }
func (commandHExpireAtNX) Forbid() bool                      { return false }
func (commandHExpireAtNX) WarningOnce() bool                 { return false }
func (commandHExpireAtNX) WarnVersion() string               { return "" }
func (commandHExpireAtNX) Warning() string                   { return "" }
func (commandHExpireAtNX) Instead() string                   { return "" }
func (commandHExpireAtNX) ETC() string                       { return "" }
func (commandHExpireAtNX) PR(b BaseCmd) IntSliceCmd          { return b.(IntSliceCmd) }
func (commandHExpireAtNX) P(p Pipeliner) commandHExpireAtNXP { return commandHExpireAtNXP{p} }
func (b commandHExpireAtNXP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HExpireAtNXCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHExpireAtXX commandHExpireAtXX

type commandHExpireAtXX string
type commandHExpireAtXXP struct{ p Pipeliner }

func (commandHExpireAtXX) String() string                    { return "HEXPIREAT XX" }
func (commandHExpireAtXX) Class() string                     { return "Hash" }
func (commandHExpireAtXX) RequireVersion() string            { return "7.4.0" }
func (commandHExpireAtXX) Forbid() bool                      { return false }
func (commandHExpireAtXX) WarningOnce() bool                 { return false }
func (commandHExpireAtXX) WarnVersion() string               { return "" }
func (commandHExpireAtXX) Warning() string                   { return "" }
func (commandHExpireAtXX) Instead() string                   { return "" }
func (commandHExpireAtXX) ETC() string                       { return "" }
func (commandHExpireAtXX) PR(b BaseCmd) IntSliceCmd          { return b.(IntSliceCmd) }
func (commandHExpireAtXX) P(p Pipeliner) commandHExpireAtXXP { return commandHExpireAtXXP{p} }
func (b commandHExpireAtXXP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HExpireAtXXCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHExpireGT commandHExpireGT

type commandHExpireGT string
type commandHExpireGTP struct{ p Pipeliner }

func (commandHExpireGT) String() string                  { return "HEXPIRE GT" }
func (commandHExpireGT) Class() string                   { return "Hash" }
func (commandHExpireGT) RequireVersion() string          { return "7.4.0" }
func (commandHExpireGT) Forbid() bool                    { return false }
func (commandHExpireGT) WarningOnce() bool               { return false }
func (commandHExpireGT) WarnVersion() string             { return "" }
func (commandHExpireGT) Warning() string                 { return "" }
func (commandHExpireGT) Instead() string                 { return "" }
func (commandHExpireGT) ETC() string                     { return "" }
func (commandHExpireGT) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandHExpireGT) P(p Pipeliner) commandHExpireGTP { return commandHExpireGTP{p} }
func (b commandHExpireGTP) Cmd(key string, seconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HExpireGTCompleted(key, seconds, fields...), &intSliceCmd{})
}

var CommandHExpireLT commandHExpireLT

type commandHExpireLT string
type commandHExpireLTP struct{ p Pipeliner }

func (commandHExpireLT) String() string                  { return "HEXPIRE LT" }
func (commandHExpireLT) Class() string                   { return "Hash" }
func (commandHExpireLT) RequireVersion() string          { return "7.4.0" }
func (commandHExpireLT) Forbid() bool                    { return false }
func (commandHExpireLT) WarningOnce() bool               { return false }
func (commandHExpireLT) WarnVersion() string             { return "" }
func (commandHExpireLT) Warning() string                 { return "" }
func (commandHExpireLT) Instead() string                 { return "" }
func (commandHExpireLT) ETC() string                     { return "" }
func (commandHExpireLT) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandHExpireLT) P(p Pipeliner) commandHExpireLTP { return commandHExpireLTP{p} }
func (b commandHExpireLTP) Cmd(key string, seconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HExpireLTCompleted(key, seconds, fields...), &intSliceCmd{})
}

var CommandHExpireNX commandHExpireNX

type commandHExpireNX string
type commandHExpireNXP struct{ p Pipeliner }

func (commandHExpireNX) String() string                  { return "HEXPIRE NX" }
func (commandHExpireNX) Class() string                   { return "Hash" }
func (commandHExpireNX) RequireVersion() string          { return "7.4.0" }
func (commandHExpireNX) Forbid() bool                    { return false }
func (commandHExpireNX) WarningOnce() bool               { return false }
func (commandHExpireNX) WarnVersion() string             { return "" }
func (commandHExpireNX) Warning() string                 { return "" }
func (commandHExpireNX) Instead() string                 { return "" }
func (commandHExpireNX) ETC() string                     { return "" }
func (commandHExpireNX) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandHExpireNX) P(p Pipeliner) commandHExpireNXP { return commandHExpireNXP{p} }
func (b commandHExpireNXP) Cmd(key string, seconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HExpireNXCompleted(key, seconds, fields...), &intSliceCmd{})
}

var CommandHExpireTime commandHExpireTime

type commandHExpireTime string
type commandHExpireTimeP struct{ p Pipeliner }

func (commandHExpireTime) String() string                    { return "HEXPIRETIME" }
func (commandHExpireTime) Class() string                     { return "Hash" }
func (commandHExpireTime) RequireVersion() string            { return "7.4.0" }
func (commandHExpireTime) Forbid() bool                      { return false }
func (commandHExpireTime) WarningOnce() bool                 { return false }
func (commandHExpireTime) WarnVersion() string               { return "" }
func (commandHExpireTime) Warning() string                   { return "" }
func (commandHExpireTime) Instead() string                   { return "" }
func (commandHExpireTime) ETC() string                       { return "" }
func (commandHExpireTime) PR(b BaseCmd) DurationSliceCmd     { return b.(DurationSliceCmd) }
func (commandHExpireTime) P(p Pipeliner) commandHExpireTimeP { return commandHExpireTimeP{p} }
func (b commandHExpireTimeP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HExpireTimeCompleted(key, fields...), &durationSliceCmd{})
}

var CommandHExpireXX commandHExpireXX

type commandHExpireXX string
type commandHExpireXXP struct{ p Pipeliner }

func (commandHExpireXX) String() string                  { return "HEXPIRE XX" }
func (commandHExpireXX) Class() string                   { return "Hash" }
func (commandHExpireXX) RequireVersion() string          { return "7.4.0" }
func (commandHExpireXX) Forbid() bool                    { return false }
func (commandHExpireXX) WarningOnce() bool               { return false }
func (commandHExpireXX) WarnVersion() string             { return "" }
func (commandHExpireXX) Warning() string                 { return "" }
func (commandHExpireXX) Instead() string                 { return "" }
func (commandHExpireXX) ETC() string                     { return "" }
func (commandHExpireXX) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandHExpireXX) P(p Pipeliner) commandHExpireXXP { return commandHExpireXXP{p} }
func (b commandHExpireXXP) Cmd(key string, seconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HExpireXXCompleted(key, seconds, fields...), &intSliceCmd{})
}

var CommandHGet commandHGet

type commandHGet string
type commandHGetP struct{ p Pipeliner }

func (commandHGet) String() string             { return "HGET" }
func (commandHGet) Class() string              { return "Hash" }
func (commandHGet) RequireVersion() string     { return "2.0.0" }
func (commandHGet) Forbid() bool               { return false }
func (commandHGet) WarningOnce() bool          { return false }
func (commandHGet) WarnVersion() string        { return "" }
func (commandHGet) Warning() string            { return "" }
func (commandHGet) Instead() string            { return "" }
func (commandHGet) ETC() string                { return "" }
func (commandHGet) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandHGet) P(p Pipeliner) commandHGetP { return commandHGetP{p} }
func (b commandHGetP) Cmd(key string, field string) {
	b.p.cmd(b.p.builder().HGetCompleted(key, field), &stringCmd{})
}

var CommandHGetAll commandHGetAll

type commandHGetAll string
type commandHGetAllP struct{ p Pipeliner }

func (commandHGetAll) String() string                  { return "HGETALL" }
func (commandHGetAll) Class() string                   { return "Hash" }
func (commandHGetAll) RequireVersion() string          { return "2.0.0" }
func (commandHGetAll) Forbid() bool                    { return false }
func (commandHGetAll) WarningOnce() bool               { return false }
func (commandHGetAll) WarnVersion() string             { return "" }
func (commandHGetAll) Warning() string                 { return "" }
func (commandHGetAll) Instead() string                 { return "" }
func (commandHGetAll) ETC() string                     { return "" }
func (commandHGetAll) PR(b BaseCmd) StringStringMapCmd { return b.(StringStringMapCmd) }
func (commandHGetAll) P(p Pipeliner) commandHGetAllP   { return commandHGetAllP{p} }
func (b commandHGetAllP) Cmd(key string) {
	b.p.cmd(b.p.builder().HGetAllCompleted(key), &stringStringMapCmd{})
}

var CommandHIncrBy commandHIncrBy

type commandHIncrBy string
type commandHIncrByP struct{ p Pipeliner }

func (commandHIncrBy) String() string                { return "HINCRBY" }
func (commandHIncrBy) Class() string                 { return "Hash" }
func (commandHIncrBy) RequireVersion() string        { return "2.0.0" }
func (commandHIncrBy) Forbid() bool                  { return false }
func (commandHIncrBy) WarningOnce() bool             { return false }
func (commandHIncrBy) WarnVersion() string           { return "" }
func (commandHIncrBy) Warning() string               { return "" }
func (commandHIncrBy) Instead() string               { return "" }
func (commandHIncrBy) ETC() string                   { return "" }
func (commandHIncrBy) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandHIncrBy) P(p Pipeliner) commandHIncrByP { return commandHIncrByP{p} }
func (b commandHIncrByP) Cmd(key string, field string, incr int64) {
	b.p.cmd(b.p.builder().HIncrByCompleted(key, field, incr), &intCmd{})
}

var CommandHIncrByFloat commandHIncrByFloat

type commandHIncrByFloat string
type commandHIncrByFloatP struct{ p Pipeliner }

func (commandHIncrByFloat) String() string                     { return "HINCRBYFLOAT" }
func (commandHIncrByFloat) Class() string                      { return "Hash" }
func (commandHIncrByFloat) RequireVersion() string             { return "2.6.0" }
func (commandHIncrByFloat) Forbid() bool                       { return false }
func (commandHIncrByFloat) WarningOnce() bool                  { return false }
func (commandHIncrByFloat) WarnVersion() string                { return "" }
func (commandHIncrByFloat) Warning() string                    { return "" }
func (commandHIncrByFloat) Instead() string                    { return "" }
func (commandHIncrByFloat) ETC() string                        { return "" }
func (commandHIncrByFloat) PR(b BaseCmd) FloatCmd              { return b.(FloatCmd) }
func (commandHIncrByFloat) P(p Pipeliner) commandHIncrByFloatP { return commandHIncrByFloatP{p} }
func (b commandHIncrByFloatP) Cmd(key string, field string, incr float64) {
	b.p.cmd(b.p.builder().HIncrByFloatCompleted(key, field, incr), &floatCmd{})
}

var CommandHKeys commandHKeys

type commandHKeys string
type commandHKeysP struct{ p Pipeliner }

func (commandHKeys) String() string              { return "HKEYS" }
func (commandHKeys) Class() string               { return "Hash" }
func (commandHKeys) RequireVersion() string      { return "2.0.0" }
func (commandHKeys) Forbid() bool                { return false }
func (commandHKeys) WarningOnce() bool           { return false }
func (commandHKeys) WarnVersion() string         { return "" }
func (commandHKeys) Warning() string             { return "" }
func (commandHKeys) Instead() string             { return "" }
func (commandHKeys) ETC() string                 { return "" }
func (commandHKeys) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandHKeys) P(p Pipeliner) commandHKeysP { return commandHKeysP{p} }
func (b commandHKeysP) Cmd(key string) {
	b.p.cmd(b.p.builder().HKeysCompleted(key), &stringSliceCmd{})
}

var CommandHLen commandHLen

type commandHLen string
type commandHLenP struct{ p Pipeliner }

func (commandHLen) String() string             { return "HLEN" }
func (commandHLen) Class() string              { return "Hash" }
func (commandHLen) RequireVersion() string     { return "2.0.0" }
func (commandHLen) Forbid() bool               { return false }
func (commandHLen) WarningOnce() bool          { return false }
func (commandHLen) WarnVersion() string        { return "" }
func (commandHLen) Warning() string            { return "" }
func (commandHLen) Instead() string            { return "" }
func (commandHLen) ETC() string                { return "" }
func (commandHLen) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandHLen) P(p Pipeliner) commandHLenP { return commandHLenP{p} }
func (b commandHLenP) Cmd(key string) {
	b.p.cmd(b.p.builder().HLenCompleted(key), &intCmd{})
}

var CommandHMDel commandHMDel

type commandHMDel string
type commandHMDelP struct{ p Pipeliner }

func (commandHMDel) String() string              { return "HDEL" }
func (commandHMDel) Class() string               { return "Hash" }
func (commandHMDel) RequireVersion() string      { return "2.4.0" }
func (commandHMDel) Forbid() bool                { return false }
func (commandHMDel) WarningOnce() bool           { return false }
func (commandHMDel) WarnVersion() string         { return "" }
func (commandHMDel) Warning() string             { return "" }
func (commandHMDel) Instead() string             { return "" }
func (commandHMDel) ETC() string                 { return "" }
func (commandHMDel) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandHMDel) P(p Pipeliner) commandHMDelP { return commandHMDelP{p} }
func (b commandHMDelP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HDelCompleted(key, fields...), &intCmd{})
}

var CommandHMGet commandHMGet

type commandHMGet string
type commandHMGetP struct{ p Pipeliner }

func (commandHMGet) String() string              { return "HMGET" }
func (commandHMGet) Class() string               { return "Hash" }
func (commandHMGet) RequireVersion() string      { return "2.0.0" }
func (commandHMGet) Forbid() bool                { return false }
func (commandHMGet) WarningOnce() bool           { return false }
func (commandHMGet) WarnVersion() string         { return "" }
func (commandHMGet) Warning() string             { return "" }
func (commandHMGet) Instead() string             { return "" }
func (commandHMGet) ETC() string                 { return "" }
func (commandHMGet) PR(b BaseCmd) SliceCmd       { return b.(SliceCmd) }
func (commandHMGet) P(p Pipeliner) commandHMGetP { return commandHMGetP{p} }
func (b commandHMGetP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HMGetCompleted(key, fields...), &sliceCmd{})
}

var CommandHMSet commandHMSet

type commandHMSet string
type commandHMSetP struct{ p Pipeliner }

func (commandHMSet) String() string              { return "HMSET" }
func (commandHMSet) Class() string               { return "Hash" }
func (commandHMSet) RequireVersion() string      { return "2.0.0" }
func (commandHMSet) Forbid() bool                { return false }
func (commandHMSet) WarningOnce() bool           { return false }
func (commandHMSet) WarnVersion() string         { return "4.0.0" }
func (commandHMSet) Warning() string             { return commandHMSetWarning }
func (commandHMSet) Instead() string             { return "HSet" }
func (commandHMSet) ETC() string                 { return "client.HSet(ctx, key, values...)" }
func (commandHMSet) PR(b BaseCmd) BoolCmd        { return b.(BoolCmd) }
func (commandHMSet) P(p Pipeliner) commandHMSetP { return commandHMSetP{p} }
func (b commandHMSetP) Cmd(key string, values ...any) {
	b.p.cmd(b.p.builder().HMSetCompleted(key, values...), &boolCmd{})
}

var CommandHMSetX commandHMSetX

type commandHMSetX string
type commandHMSetXP struct{ p Pipeliner }

func (commandHMSetX) String() string               { return "HSET" }
func (commandHMSetX) Class() string                { return "Hash" }
func (commandHMSetX) RequireVersion() string       { return "4.0.0" }
func (commandHMSetX) Forbid() bool                 { return false }
func (commandHMSetX) WarningOnce() bool            { return false }
func (commandHMSetX) WarnVersion() string          { return "" }
func (commandHMSetX) Warning() string              { return "" }
func (commandHMSetX) Instead() string              { return "" }
func (commandHMSetX) ETC() string                  { return "" }
func (commandHMSetX) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandHMSetX) P(p Pipeliner) commandHMSetXP { return commandHMSetXP{p} }
func (b commandHMSetXP) Cmd(key string, values ...any) {
	b.p.cmd(b.p.builder().HMSetXCompleted(key, values...), &intCmd{})
}

var CommandHPExpire commandHPExpire

type commandHPExpire string
type commandHPExpireP struct{ p Pipeliner }

func (commandHPExpire) String() string                 { return "HPEXPIRE" }
func (commandHPExpire) Class() string                  { return "Hash" }
func (commandHPExpire) RequireVersion() string         { return "7.4.0" }
func (commandHPExpire) Forbid() bool                   { return false }
func (commandHPExpire) WarningOnce() bool              { return false }
func (commandHPExpire) WarnVersion() string            { return "" }
func (commandHPExpire) Warning() string                { return "" }
func (commandHPExpire) Instead() string                { return "" }
func (commandHPExpire) ETC() string                    { return "" }
func (commandHPExpire) PR(b BaseCmd) IntSliceCmd       { return b.(IntSliceCmd) }
func (commandHPExpire) P(p Pipeliner) commandHPExpireP { return commandHPExpireP{p} }
func (b commandHPExpireP) Cmd(key string, milliseconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireCompleted(key, milliseconds, fields...), &intSliceCmd{})
}

var CommandHPExpireAt commandHPExpireAt

type commandHPExpireAt string
type commandHPExpireAtP struct{ p Pipeliner }

func (commandHPExpireAt) String() string                   { return "HPEXPIREAT" }
func (commandHPExpireAt) Class() string                    { return "Hash" }
func (commandHPExpireAt) RequireVersion() string           { return "7.4.0" }
func (commandHPExpireAt) Forbid() bool                     { return false }
func (commandHPExpireAt) WarningOnce() bool                { return false }
func (commandHPExpireAt) WarnVersion() string              { return "" }
func (commandHPExpireAt) Warning() string                  { return "" }
func (commandHPExpireAt) Instead() string                  { return "" }
func (commandHPExpireAt) ETC() string                      { return "" }
func (commandHPExpireAt) PR(b BaseCmd) IntSliceCmd         { return b.(IntSliceCmd) }
func (commandHPExpireAt) P(p Pipeliner) commandHPExpireAtP { return commandHPExpireAtP{p} }
func (b commandHPExpireAtP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireAtCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHPExpireAtGT commandHPExpireAtGT

type commandHPExpireAtGT string
type commandHPExpireAtGTP struct{ p Pipeliner }

func (commandHPExpireAtGT) String() string                     { return "HPEXPIREAT GT" }
func (commandHPExpireAtGT) Class() string                      { return "Hash" }
func (commandHPExpireAtGT) RequireVersion() string             { return "7.4.0" }
func (commandHPExpireAtGT) Forbid() bool                       { return false }
func (commandHPExpireAtGT) WarningOnce() bool                  { return false }
func (commandHPExpireAtGT) WarnVersion() string                { return "" }
func (commandHPExpireAtGT) Warning() string                    { return "" }
func (commandHPExpireAtGT) Instead() string                    { return "" }
func (commandHPExpireAtGT) ETC() string                        { return "" }
func (commandHPExpireAtGT) PR(b BaseCmd) IntSliceCmd           { return b.(IntSliceCmd) }
func (commandHPExpireAtGT) P(p Pipeliner) commandHPExpireAtGTP { return commandHPExpireAtGTP{p} }
func (b commandHPExpireAtGTP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireAtGTCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHPExpireAtLT commandHPExpireAtLT

type commandHPExpireAtLT string
type commandHPExpireAtLTP struct{ p Pipeliner }

func (commandHPExpireAtLT) String() string                     { return "HPEXPIREAT LT" }
func (commandHPExpireAtLT) Class() string                      { return "Hash" }
func (commandHPExpireAtLT) RequireVersion() string             { return "7.4.0" }
func (commandHPExpireAtLT) Forbid() bool                       { return false }
func (commandHPExpireAtLT) WarningOnce() bool                  { return false }
func (commandHPExpireAtLT) WarnVersion() string                { return "" }
func (commandHPExpireAtLT) Warning() string                    { return "" }
func (commandHPExpireAtLT) Instead() string                    { return "" }
func (commandHPExpireAtLT) ETC() string                        { return "" }
func (commandHPExpireAtLT) PR(b BaseCmd) IntSliceCmd           { return b.(IntSliceCmd) }
func (commandHPExpireAtLT) P(p Pipeliner) commandHPExpireAtLTP { return commandHPExpireAtLTP{p} }
func (b commandHPExpireAtLTP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireAtLTCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHPExpireAtNX commandHPExpireAtNX

type commandHPExpireAtNX string
type commandHPExpireAtNXP struct{ p Pipeliner }

func (commandHPExpireAtNX) String() string                     { return "HPEXPIREAT NX" }
func (commandHPExpireAtNX) Class() string                      { return "Hash" }
func (commandHPExpireAtNX) RequireVersion() string             { return "7.4.0" }
func (commandHPExpireAtNX) Forbid() bool                       { return false }
func (commandHPExpireAtNX) WarningOnce() bool                  { return false }
func (commandHPExpireAtNX) WarnVersion() string                { return "" }
func (commandHPExpireAtNX) Warning() string                    { return "" }
func (commandHPExpireAtNX) Instead() string                    { return "" }
func (commandHPExpireAtNX) ETC() string                        { return "" }
func (commandHPExpireAtNX) PR(b BaseCmd) IntSliceCmd           { return b.(IntSliceCmd) }
func (commandHPExpireAtNX) P(p Pipeliner) commandHPExpireAtNXP { return commandHPExpireAtNXP{p} }
func (b commandHPExpireAtNXP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireAtNXCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHPExpireAtXX commandHPExpireAtXX

type commandHPExpireAtXX string
type commandHPExpireAtXXP struct{ p Pipeliner }

func (commandHPExpireAtXX) String() string                     { return "HPEXPIREAT XX" }
func (commandHPExpireAtXX) Class() string                      { return "Hash" }
func (commandHPExpireAtXX) RequireVersion() string             { return "7.4.0" }
func (commandHPExpireAtXX) Forbid() bool                       { return false }
func (commandHPExpireAtXX) WarningOnce() bool                  { return false }
func (commandHPExpireAtXX) WarnVersion() string                { return "" }
func (commandHPExpireAtXX) Warning() string                    { return "" }
func (commandHPExpireAtXX) Instead() string                    { return "" }
func (commandHPExpireAtXX) ETC() string                        { return "" }
func (commandHPExpireAtXX) PR(b BaseCmd) IntSliceCmd           { return b.(IntSliceCmd) }
func (commandHPExpireAtXX) P(p Pipeliner) commandHPExpireAtXXP { return commandHPExpireAtXXP{p} }
func (b commandHPExpireAtXXP) Cmd(key string, tm time.Time, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireAtXXCompleted(key, tm, fields...), &intSliceCmd{})
}

var CommandHPExpireGT commandHPExpireGT

type commandHPExpireGT string
type commandHPExpireGTP struct{ p Pipeliner }

func (commandHPExpireGT) String() string                   { return "HPEXPIRE GT" }
func (commandHPExpireGT) Class() string                    { return "Hash" }
func (commandHPExpireGT) RequireVersion() string           { return "7.4.0" }
func (commandHPExpireGT) Forbid() bool                     { return false }
func (commandHPExpireGT) WarningOnce() bool                { return false }
func (commandHPExpireGT) WarnVersion() string              { return "" }
func (commandHPExpireGT) Warning() string                  { return "" }
func (commandHPExpireGT) Instead() string                  { return "" }
func (commandHPExpireGT) ETC() string                      { return "" }
func (commandHPExpireGT) PR(b BaseCmd) IntSliceCmd         { return b.(IntSliceCmd) }
func (commandHPExpireGT) P(p Pipeliner) commandHPExpireGTP { return commandHPExpireGTP{p} }
func (b commandHPExpireGTP) Cmd(key string, milliseconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireGTCompleted(key, milliseconds, fields...), &intSliceCmd{})
}

var CommandHPExpireLT commandHPExpireLT

type commandHPExpireLT string
type commandHPExpireLTP struct{ p Pipeliner }

func (commandHPExpireLT) String() string                   { return "HPEXPIRE LT" }
func (commandHPExpireLT) Class() string                    { return "Hash" }
func (commandHPExpireLT) RequireVersion() string           { return "7.4.0" }
func (commandHPExpireLT) Forbid() bool                     { return false }
func (commandHPExpireLT) WarningOnce() bool                { return false }
func (commandHPExpireLT) WarnVersion() string              { return "" }
func (commandHPExpireLT) Warning() string                  { return "" }
func (commandHPExpireLT) Instead() string                  { return "" }
func (commandHPExpireLT) ETC() string                      { return "" }
func (commandHPExpireLT) PR(b BaseCmd) IntSliceCmd         { return b.(IntSliceCmd) }
func (commandHPExpireLT) P(p Pipeliner) commandHPExpireLTP { return commandHPExpireLTP{p} }
func (b commandHPExpireLTP) Cmd(key string, milliseconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireLTCompleted(key, milliseconds, fields...), &intSliceCmd{})
}

var CommandHPExpireNX commandHPExpireNX

type commandHPExpireNX string
type commandHPExpireNXP struct{ p Pipeliner }

func (commandHPExpireNX) String() string                   { return "HPEXPIRE NX" }
func (commandHPExpireNX) Class() string                    { return "Hash" }
func (commandHPExpireNX) RequireVersion() string           { return "7.4.0" }
func (commandHPExpireNX) Forbid() bool                     { return false }
func (commandHPExpireNX) WarningOnce() bool                { return false }
func (commandHPExpireNX) WarnVersion() string              { return "" }
func (commandHPExpireNX) Warning() string                  { return "" }
func (commandHPExpireNX) Instead() string                  { return "" }
func (commandHPExpireNX) ETC() string                      { return "" }
func (commandHPExpireNX) PR(b BaseCmd) IntSliceCmd         { return b.(IntSliceCmd) }
func (commandHPExpireNX) P(p Pipeliner) commandHPExpireNXP { return commandHPExpireNXP{p} }
func (b commandHPExpireNXP) Cmd(key string, milliseconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireNXCompleted(key, milliseconds, fields...), &intSliceCmd{})
}

var CommandHPExpireTime commandHPExpireTime

type commandHPExpireTime string
type commandHPExpireTimeP struct{ p Pipeliner }

func (commandHPExpireTime) String() string                     { return "HPEXPIRETIME" }
func (commandHPExpireTime) Class() string                      { return "Hash" }
func (commandHPExpireTime) RequireVersion() string             { return "7.4.0" }
func (commandHPExpireTime) Forbid() bool                       { return false }
func (commandHPExpireTime) WarningOnce() bool                  { return false }
func (commandHPExpireTime) WarnVersion() string                { return "" }
func (commandHPExpireTime) Warning() string                    { return "" }
func (commandHPExpireTime) Instead() string                    { return "" }
func (commandHPExpireTime) ETC() string                        { return "" }
func (commandHPExpireTime) PR(b BaseCmd) DurationSliceCmd      { return b.(DurationSliceCmd) }
func (commandHPExpireTime) P(p Pipeliner) commandHPExpireTimeP { return commandHPExpireTimeP{p} }
func (b commandHPExpireTimeP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireTimeCompleted(key, fields...), &durationSliceCmd{})
}

var CommandHPExpireXX commandHPExpireXX

type commandHPExpireXX string
type commandHPExpireXXP struct{ p Pipeliner }

func (commandHPExpireXX) String() string                   { return "HPEXPIRE XX" }
func (commandHPExpireXX) Class() string                    { return "Hash" }
func (commandHPExpireXX) RequireVersion() string           { return "7.4.0" }
func (commandHPExpireXX) Forbid() bool                     { return false }
func (commandHPExpireXX) WarningOnce() bool                { return false }
func (commandHPExpireXX) WarnVersion() string              { return "" }
func (commandHPExpireXX) Warning() string                  { return "" }
func (commandHPExpireXX) Instead() string                  { return "" }
func (commandHPExpireXX) ETC() string                      { return "" }
func (commandHPExpireXX) PR(b BaseCmd) IntSliceCmd         { return b.(IntSliceCmd) }
func (commandHPExpireXX) P(p Pipeliner) commandHPExpireXXP { return commandHPExpireXXP{p} }
func (b commandHPExpireXXP) Cmd(key string, milliseconds time.Duration, fields ...string) {
	b.p.cmd(b.p.builder().HPExpireXXCompleted(key, milliseconds, fields...), &intSliceCmd{})
}

var CommandHPTTL commandHPTTL

type commandHPTTL string
type commandHPTTLP struct{ p Pipeliner }

func (commandHPTTL) String() string                { return "HPTTL" }
func (commandHPTTL) Class() string                 { return "Hash" }
func (commandHPTTL) RequireVersion() string        { return "7.4.0" }
func (commandHPTTL) Forbid() bool                  { return false }
func (commandHPTTL) WarningOnce() bool             { return false }
func (commandHPTTL) WarnVersion() string           { return "" }
func (commandHPTTL) Warning() string               { return "" }
func (commandHPTTL) Instead() string               { return "" }
func (commandHPTTL) ETC() string                   { return "" }
func (commandHPTTL) PR(b BaseCmd) DurationSliceCmd { return b.(DurationSliceCmd) }
func (commandHPTTL) P(p Pipeliner) commandHPTTLP   { return commandHPTTLP{p} }
func (b commandHPTTLP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HPTTLCompleted(key, fields...), &durationSliceCmd{})
}

var CommandHPersist commandHPersist

type commandHPersist string
type commandHPersistP struct{ p Pipeliner }

func (commandHPersist) String() string                 { return "HPERSIST" }
func (commandHPersist) Class() string                  { return "Hash" }
func (commandHPersist) RequireVersion() string         { return "7.4.0" }
func (commandHPersist) Forbid() bool                   { return false }
func (commandHPersist) WarningOnce() bool              { return false }
func (commandHPersist) WarnVersion() string            { return "" }
func (commandHPersist) Warning() string                { return "" }
func (commandHPersist) Instead() string                { return "" }
func (commandHPersist) ETC() string                    { return "" }
func (commandHPersist) PR(b BaseCmd) IntSliceCmd       { return b.(IntSliceCmd) }
func (commandHPersist) P(p Pipeliner) commandHPersistP { return commandHPersistP{p} }
func (b commandHPersistP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HPersistCompleted(key, fields...), &intSliceCmd{})
}

var CommandHRandField commandHRandField

type commandHRandField string
type commandHRandFieldP struct{ p Pipeliner }

func (commandHRandField) String() string                   { return "HRANDFIELD" }
func (commandHRandField) Class() string                    { return "Hash" }
func (commandHRandField) RequireVersion() string           { return "6.2.0" }
func (commandHRandField) Forbid() bool                     { return false }
func (commandHRandField) WarningOnce() bool                { return false }
func (commandHRandField) WarnVersion() string              { return "" }
func (commandHRandField) Warning() string                  { return "" }
func (commandHRandField) Instead() string                  { return "" }
func (commandHRandField) ETC() string                      { return "" }
func (commandHRandField) PR(b BaseCmd) StringSliceCmd      { return b.(StringSliceCmd) }
func (commandHRandField) P(p Pipeliner) commandHRandFieldP { return commandHRandFieldP{p} }
func (b commandHRandFieldP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().HRandFieldCompleted(key, count), &stringSliceCmd{})
}

var CommandHRandFieldWithValues commandHRandFieldWithValues

type commandHRandFieldWithValues string
type commandHRandFieldWithValuesP struct{ p Pipeliner }

func (commandHRandFieldWithValues) String() string                { return "HRANDFIELD WITHVALUES" }
func (commandHRandFieldWithValues) Class() string                 { return "Hash" }
func (commandHRandFieldWithValues) RequireVersion() string        { return "6.2.0" }
func (commandHRandFieldWithValues) Forbid() bool                  { return false }
func (commandHRandFieldWithValues) WarningOnce() bool             { return false }
func (commandHRandFieldWithValues) WarnVersion() string           { return "" }
func (commandHRandFieldWithValues) Warning() string               { return "" }
func (commandHRandFieldWithValues) Instead() string               { return "" }
func (commandHRandFieldWithValues) ETC() string                   { return "" }
func (commandHRandFieldWithValues) PR(b BaseCmd) KeyValueSliceCmd { return b.(KeyValueSliceCmd) }
func (commandHRandFieldWithValues) P(p Pipeliner) commandHRandFieldWithValuesP {
	return commandHRandFieldWithValuesP{p}
}
func (b commandHRandFieldWithValuesP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().HRandFieldWithValuesCompleted(key, count), &keyValueSliceCmd{})
}

var CommandHScan commandHScan

type commandHScan string
type commandHScanP struct{ p Pipeliner }

func (commandHScan) String() string              { return "HSCAN" }
func (commandHScan) Class() string               { return "Hash" }
func (commandHScan) RequireVersion() string      { return "2.8.0" }
func (commandHScan) Forbid() bool                { return false }
func (commandHScan) WarningOnce() bool           { return false }
func (commandHScan) WarnVersion() string         { return "" }
func (commandHScan) Warning() string             { return "" }
func (commandHScan) Instead() string             { return "" }
func (commandHScan) ETC() string                 { return "" }
func (commandHScan) PR(b BaseCmd) ScanCmd        { return b.(ScanCmd) }
func (commandHScan) P(p Pipeliner) commandHScanP { return commandHScanP{p} }
func (b commandHScanP) Cmd(key string, cursor uint64, match string, count int64) {
	b.p.cmd(b.p.builder().HScanCompleted(key, cursor, match, count), &scanCmd{})
}

var CommandHSet commandHSet

type commandHSet string
type commandHSetP struct{ p Pipeliner }

func (commandHSet) String() string             { return "HSET" }
func (commandHSet) Class() string              { return "Hash" }
func (commandHSet) RequireVersion() string     { return "2.8.0" }
func (commandHSet) Forbid() bool               { return false }
func (commandHSet) WarningOnce() bool          { return false }
func (commandHSet) WarnVersion() string        { return "" }
func (commandHSet) Warning() string            { return "" }
func (commandHSet) Instead() string            { return "" }
func (commandHSet) ETC() string                { return "" }
func (commandHSet) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandHSet) P(p Pipeliner) commandHSetP { return commandHSetP{p} }
func (b commandHSetP) Cmd(key string, field string, value any) {
	b.p.cmd(b.p.builder().HSetCompleted(key, field, value), &intCmd{})
}

var CommandHSetNX commandHSetNX

type commandHSetNX string
type commandHSetNXP struct{ p Pipeliner }

func (commandHSetNX) String() string               { return "HSETNX" }
func (commandHSetNX) Class() string                { return "Hash" }
func (commandHSetNX) RequireVersion() string       { return "2.0.0" }
func (commandHSetNX) Forbid() bool                 { return false }
func (commandHSetNX) WarningOnce() bool            { return false }
func (commandHSetNX) WarnVersion() string          { return "" }
func (commandHSetNX) Warning() string              { return "" }
func (commandHSetNX) Instead() string              { return "" }
func (commandHSetNX) ETC() string                  { return "" }
func (commandHSetNX) PR(b BaseCmd) BoolCmd         { return b.(BoolCmd) }
func (commandHSetNX) P(p Pipeliner) commandHSetNXP { return commandHSetNXP{p} }
func (b commandHSetNXP) Cmd(key string, field string, value any) {
	b.p.cmd(b.p.builder().HSetNXCompleted(key, field, value), &boolCmd{})
}

var CommandHStrLen commandHStrLen

type commandHStrLen string
type commandHStrLenP struct{ p Pipeliner }

func (commandHStrLen) String() string                { return "HSTRLEN" }
func (commandHStrLen) Class() string                 { return "Hash" }
func (commandHStrLen) RequireVersion() string        { return "3.2.0" }
func (commandHStrLen) Forbid() bool                  { return false }
func (commandHStrLen) WarningOnce() bool             { return false }
func (commandHStrLen) WarnVersion() string           { return "" }
func (commandHStrLen) Warning() string               { return "" }
func (commandHStrLen) Instead() string               { return "" }
func (commandHStrLen) ETC() string                   { return "" }
func (commandHStrLen) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandHStrLen) P(p Pipeliner) commandHStrLenP { return commandHStrLenP{p} }
func (b commandHStrLenP) Cmd(key string, field string) {
	b.p.cmd(b.p.builder().HStrLenCompleted(key, field), &intCmd{})
}

var CommandHTTL commandHTTL

type commandHTTL string
type commandHTTLP struct{ p Pipeliner }

func (commandHTTL) String() string                { return "HTTL" }
func (commandHTTL) Class() string                 { return "Hash" }
func (commandHTTL) RequireVersion() string        { return "7.4.0" }
func (commandHTTL) Forbid() bool                  { return false }
func (commandHTTL) WarningOnce() bool             { return false }
func (commandHTTL) WarnVersion() string           { return "" }
func (commandHTTL) Warning() string               { return "" }
func (commandHTTL) Instead() string               { return "" }
func (commandHTTL) ETC() string                   { return "" }
func (commandHTTL) PR(b BaseCmd) DurationSliceCmd { return b.(DurationSliceCmd) }
func (commandHTTL) P(p Pipeliner) commandHTTLP    { return commandHTTLP{p} }
func (b commandHTTLP) Cmd(key string, fields ...string) {
	b.p.cmd(b.p.builder().HTTLCompleted(key, fields...), &durationSliceCmd{})
}

var CommandHVals commandHVals

type commandHVals string
type commandHValsP struct{ p Pipeliner }

func (commandHVals) String() string              { return "HVALS" }
func (commandHVals) Class() string               { return "Hash" }
func (commandHVals) RequireVersion() string      { return "2.0.0" }
func (commandHVals) Forbid() bool                { return false }
func (commandHVals) WarningOnce() bool           { return false }
func (commandHVals) WarnVersion() string         { return "" }
func (commandHVals) Warning() string             { return "" }
func (commandHVals) Instead() string             { return "" }
func (commandHVals) ETC() string                 { return "" }
func (commandHVals) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandHVals) P(p Pipeliner) commandHValsP { return commandHValsP{p} }
func (b commandHValsP) Cmd(key string) {
	b.p.cmd(b.p.builder().HValsCompleted(key), &stringSliceCmd{})
}
