// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandBitCount commandBitCount

type commandBitCount string
type commandBitCountP struct{ p Pipeliner }

func (commandBitCount) String() string                 { return "BITCOUNT" }
func (commandBitCount) Class() string                  { return "Bitmap" }
func (commandBitCount) RequireVersion() string         { return "2.6.0" }
func (commandBitCount) Forbid() bool                   { return false }
func (commandBitCount) WarningOnce() bool              { return false }
func (commandBitCount) WarnVersion() string            { return "" }
func (commandBitCount) Warning() string                { return "" }
func (commandBitCount) Instead() string                { return "" }
func (commandBitCount) ETC() string                    { return "" }
func (commandBitCount) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandBitCount) P(p Pipeliner) commandBitCountP { return commandBitCountP{p} }
func (b commandBitCountP) Cmd(key string, bc *BitCount) {
	b.p.cmd(b.p.builder().BitCountCompleted(key, bc), &intCmd{})
}

var CommandBitCountBit commandBitCountBit

type commandBitCountBit string
type commandBitCountBitP struct{ p Pipeliner }

func (commandBitCountBit) String() string                    { return "BITCOUNT BIT" }
func (commandBitCountBit) Class() string                     { return "Bitmap" }
func (commandBitCountBit) RequireVersion() string            { return "7.0.0" }
func (commandBitCountBit) Forbid() bool                      { return false }
func (commandBitCountBit) WarningOnce() bool                 { return false }
func (commandBitCountBit) WarnVersion() string               { return "" }
func (commandBitCountBit) Warning() string                   { return "" }
func (commandBitCountBit) Instead() string                   { return "" }
func (commandBitCountBit) ETC() string                       { return "" }
func (commandBitCountBit) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandBitCountBit) P(p Pipeliner) commandBitCountBitP { return commandBitCountBitP{p} }
func (b commandBitCountBitP) Cmd(key string, bc *BitCount) {
	b.p.cmd(b.p.builder().BitCountCompleted(key, bc), &intCmd{})
}

var CommandBitCountByte commandBitCountByte

type commandBitCountByte string
type commandBitCountByteP struct{ p Pipeliner }

func (commandBitCountByte) String() string                     { return "BITCOUNT BYTE" }
func (commandBitCountByte) Class() string                      { return "Bitmap" }
func (commandBitCountByte) RequireVersion() string             { return "7.0.0" }
func (commandBitCountByte) Forbid() bool                       { return false }
func (commandBitCountByte) WarningOnce() bool                  { return false }
func (commandBitCountByte) WarnVersion() string                { return "" }
func (commandBitCountByte) Warning() string                    { return "" }
func (commandBitCountByte) Instead() string                    { return "" }
func (commandBitCountByte) ETC() string                        { return "" }
func (commandBitCountByte) PR(b BaseCmd) IntCmd                { return b.(IntCmd) }
func (commandBitCountByte) P(p Pipeliner) commandBitCountByteP { return commandBitCountByteP{p} }
func (b commandBitCountByteP) Cmd(key string, bc *BitCount) {
	b.p.cmd(b.p.builder().BitCountCompleted(key, bc), &intCmd{})
}

var CommandBitField commandBitField

type commandBitField string
type commandBitFieldP struct{ p Pipeliner }

func (commandBitField) String() string                 { return "BITFIELD" }
func (commandBitField) Class() string                  { return "Bitmap" }
func (commandBitField) RequireVersion() string         { return "3.2.0" }
func (commandBitField) Forbid() bool                   { return false }
func (commandBitField) WarningOnce() bool              { return false }
func (commandBitField) WarnVersion() string            { return "" }
func (commandBitField) Warning() string                { return "" }
func (commandBitField) Instead() string                { return "" }
func (commandBitField) ETC() string                    { return "" }
func (commandBitField) PR(b BaseCmd) IntSliceCmd       { return b.(IntSliceCmd) }
func (commandBitField) P(p Pipeliner) commandBitFieldP { return commandBitFieldP{p} }
func (b commandBitFieldP) Cmd(key string, args ...any) {
	b.p.cmd(b.p.builder().BitFieldCompleted(key, args...), &intSliceCmd{})
}

var CommandBitOpAnd commandBitOpAnd

type commandBitOpAnd string
type commandBitOpAndP struct{ p Pipeliner }

func (commandBitOpAnd) String() string                 { return "BITOP AND" }
func (commandBitOpAnd) Class() string                  { return "Bitmap" }
func (commandBitOpAnd) RequireVersion() string         { return "2.6.0" }
func (commandBitOpAnd) Forbid() bool                   { return false }
func (commandBitOpAnd) WarningOnce() bool              { return false }
func (commandBitOpAnd) WarnVersion() string            { return "" }
func (commandBitOpAnd) Warning() string                { return "" }
func (commandBitOpAnd) Instead() string                { return "" }
func (commandBitOpAnd) ETC() string                    { return "" }
func (commandBitOpAnd) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandBitOpAnd) P(p Pipeliner) commandBitOpAndP { return commandBitOpAndP{p} }
func (b commandBitOpAndP) Cmd(destKey string, keys ...string) {
	b.p.cmd(b.p.builder().BitOpAndCompleted(destKey, keys...), &intCmd{})
}

var CommandBitOpNot commandBitOpNot

type commandBitOpNot string
type commandBitOpNotP struct{ p Pipeliner }

func (commandBitOpNot) String() string                 { return "BITOP NOT" }
func (commandBitOpNot) Class() string                  { return "Bitmap" }
func (commandBitOpNot) RequireVersion() string         { return "2.6.0" }
func (commandBitOpNot) Forbid() bool                   { return false }
func (commandBitOpNot) WarningOnce() bool              { return false }
func (commandBitOpNot) WarnVersion() string            { return "" }
func (commandBitOpNot) Warning() string                { return "" }
func (commandBitOpNot) Instead() string                { return "" }
func (commandBitOpNot) ETC() string                    { return "" }
func (commandBitOpNot) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandBitOpNot) P(p Pipeliner) commandBitOpNotP { return commandBitOpNotP{p} }
func (b commandBitOpNotP) Cmd(destKey string, key string) {
	b.p.cmd(b.p.builder().BitOpNotCompleted(destKey, key), &intCmd{})
}

var CommandBitOpOr commandBitOpOr

type commandBitOpOr string
type commandBitOpOrP struct{ p Pipeliner }

func (commandBitOpOr) String() string                { return "BITOP OR" }
func (commandBitOpOr) Class() string                 { return "Bitmap" }
func (commandBitOpOr) RequireVersion() string        { return "2.6.0" }
func (commandBitOpOr) Forbid() bool                  { return false }
func (commandBitOpOr) WarningOnce() bool             { return false }
func (commandBitOpOr) WarnVersion() string           { return "" }
func (commandBitOpOr) Warning() string               { return "" }
func (commandBitOpOr) Instead() string               { return "" }
func (commandBitOpOr) ETC() string                   { return "" }
func (commandBitOpOr) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandBitOpOr) P(p Pipeliner) commandBitOpOrP { return commandBitOpOrP{p} }
func (b commandBitOpOrP) Cmd(destKey string, keys ...string) {
	b.p.cmd(b.p.builder().BitOpOrCompleted(destKey, keys...), &intCmd{})
}

var CommandBitOpXor commandBitOpXor

type commandBitOpXor string
type commandBitOpXorP struct{ p Pipeliner }

func (commandBitOpXor) String() string                 { return "BITOP XOR" }
func (commandBitOpXor) Class() string                  { return "Bitmap" }
func (commandBitOpXor) RequireVersion() string         { return "2.6.0" }
func (commandBitOpXor) Forbid() bool                   { return false }
func (commandBitOpXor) WarningOnce() bool              { return false }
func (commandBitOpXor) WarnVersion() string            { return "" }
func (commandBitOpXor) Warning() string                { return "" }
func (commandBitOpXor) Instead() string                { return "" }
func (commandBitOpXor) ETC() string                    { return "" }
func (commandBitOpXor) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandBitOpXor) P(p Pipeliner) commandBitOpXorP { return commandBitOpXorP{p} }
func (b commandBitOpXorP) Cmd(destKey string, keys ...string) {
	b.p.cmd(b.p.builder().BitOpXorCompleted(destKey, keys...), &intCmd{})
}

var CommandBitPos commandBitPos

type commandBitPos string
type commandBitPosP struct{ p Pipeliner }

func (commandBitPos) String() string               { return "BITPOS" }
func (commandBitPos) Class() string                { return "Bitmap" }
func (commandBitPos) RequireVersion() string       { return "2.8.7" }
func (commandBitPos) Forbid() bool                 { return false }
func (commandBitPos) WarningOnce() bool            { return false }
func (commandBitPos) WarnVersion() string          { return "" }
func (commandBitPos) Warning() string              { return "" }
func (commandBitPos) Instead() string              { return "" }
func (commandBitPos) ETC() string                  { return "" }
func (commandBitPos) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandBitPos) P(p Pipeliner) commandBitPosP { return commandBitPosP{p} }
func (b commandBitPosP) Cmd(key string, bit int64, pos ...int64) {
	b.p.cmd(b.p.builder().BitPosCompleted(key, bit, pos...), &intCmd{})
}

var CommandBitPosSpan commandBitPosSpan

type commandBitPosSpan string
type commandBitPosSpanP struct{ p Pipeliner }

func (commandBitPosSpan) String() string                   { return "BITPOS BYTE/BIT" }
func (commandBitPosSpan) Class() string                    { return "Bitmap" }
func (commandBitPosSpan) RequireVersion() string           { return "7.0.0" }
func (commandBitPosSpan) Forbid() bool                     { return false }
func (commandBitPosSpan) WarningOnce() bool                { return false }
func (commandBitPosSpan) WarnVersion() string              { return "" }
func (commandBitPosSpan) Warning() string                  { return "" }
func (commandBitPosSpan) Instead() string                  { return "" }
func (commandBitPosSpan) ETC() string                      { return "" }
func (commandBitPosSpan) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandBitPosSpan) P(p Pipeliner) commandBitPosSpanP { return commandBitPosSpanP{p} }
func (b commandBitPosSpanP) Cmd(key string, bit int64, start int64, end int64, span string) {
	b.p.cmd(b.p.builder().BitPosSpanCompleted(key, bit, start, end, span), &intCmd{})
}

var CommandGetBit commandGetBit

type commandGetBit string
type commandGetBitP struct{ p Pipeliner }

func (commandGetBit) String() string               { return "GETBIT" }
func (commandGetBit) Class() string                { return "Bitmap" }
func (commandGetBit) RequireVersion() string       { return "2.2.0" }
func (commandGetBit) Forbid() bool                 { return false }
func (commandGetBit) WarningOnce() bool            { return false }
func (commandGetBit) WarnVersion() string          { return "" }
func (commandGetBit) Warning() string              { return "" }
func (commandGetBit) Instead() string              { return "" }
func (commandGetBit) ETC() string                  { return "" }
func (commandGetBit) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandGetBit) P(p Pipeliner) commandGetBitP { return commandGetBitP{p} }
func (b commandGetBitP) Cmd(key string, offset int64) {
	b.p.cmd(b.p.builder().GetBitCompleted(key, offset), &intCmd{})
}

var CommandSetBit commandSetBit

type commandSetBit string
type commandSetBitP struct{ p Pipeliner }

func (commandSetBit) String() string               { return "SETBIT" }
func (commandSetBit) Class() string                { return "Bitmap" }
func (commandSetBit) RequireVersion() string       { return "2.2.0" }
func (commandSetBit) Forbid() bool                 { return false }
func (commandSetBit) WarningOnce() bool            { return true }
func (commandSetBit) WarnVersion() string          { return "0.0.0" }
func (commandSetBit) Warning() string              { return commandSetBitWarning }
func (commandSetBit) Instead() string              { return "" }
func (commandSetBit) ETC() string                  { return "" }
func (commandSetBit) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandSetBit) P(p Pipeliner) commandSetBitP { return commandSetBitP{p} }
func (b commandSetBitP) Cmd(key string, offset int64, value int64) {
	b.p.cmd(b.p.builder().SetBitCompleted(key, offset, value), &intCmd{})
}
