// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandBLMPop commandBLMPop

type commandBLMPop string

func (commandBLMPop) String() string         { return "BLMPOP" }
func (commandBLMPop) Class() string          { return "List" }
func (commandBLMPop) RequireVersion() string { return "7.0.0" }
func (commandBLMPop) Forbid() bool           { return false }
func (commandBLMPop) WarningOnce() bool      { return false }
func (commandBLMPop) WarnVersion() string    { return "" }
func (commandBLMPop) Warning() string        { return "" }
func (commandBLMPop) Instead() string        { return "" }
func (commandBLMPop) ETC() string            { return "" }

var CommandBLMove commandBLMove

type commandBLMove string

func (commandBLMove) String() string         { return "BLMOVE" }
func (commandBLMove) Class() string          { return "List" }
func (commandBLMove) RequireVersion() string { return "6.2.0" }
func (commandBLMove) Forbid() bool           { return false }
func (commandBLMove) WarningOnce() bool      { return false }
func (commandBLMove) WarnVersion() string    { return "" }
func (commandBLMove) Warning() string        { return "" }
func (commandBLMove) Instead() string        { return "" }
func (commandBLMove) ETC() string            { return "" }

var CommandBLPop commandBLPop

type commandBLPop string

func (commandBLPop) String() string         { return "BLPOP" }
func (commandBLPop) Class() string          { return "List" }
func (commandBLPop) RequireVersion() string { return "2.0.0" }
func (commandBLPop) Forbid() bool           { return false }
func (commandBLPop) WarningOnce() bool      { return false }
func (commandBLPop) WarnVersion() string    { return "" }
func (commandBLPop) Warning() string        { return "" }
func (commandBLPop) Instead() string        { return "" }
func (commandBLPop) ETC() string            { return "" }

var CommandBRPop commandBRPop

type commandBRPop string

func (commandBRPop) String() string         { return "BRPOP" }
func (commandBRPop) Class() string          { return "List" }
func (commandBRPop) RequireVersion() string { return "2.0.0" }
func (commandBRPop) Forbid() bool           { return false }
func (commandBRPop) WarningOnce() bool      { return false }
func (commandBRPop) WarnVersion() string    { return "" }
func (commandBRPop) Warning() string        { return "" }
func (commandBRPop) Instead() string        { return "" }
func (commandBRPop) ETC() string            { return "" }

var CommandBRPopLPush commandBRPopLPush

type commandBRPopLPush string

func (commandBRPopLPush) String() string         { return "BRPOPLPUSH" }
func (commandBRPopLPush) Class() string          { return "List" }
func (commandBRPopLPush) RequireVersion() string { return "2.2.0" }
func (commandBRPopLPush) Forbid() bool           { return false }
func (commandBRPopLPush) WarningOnce() bool      { return false }
func (commandBRPopLPush) WarnVersion() string    { return "" }
func (commandBRPopLPush) Warning() string        { return "" }
func (commandBRPopLPush) Instead() string        { return "" }
func (commandBRPopLPush) ETC() string            { return "" }

var CommandLIndex commandLIndex

type commandLIndex string
type commandLIndexP struct{ p Pipeliner }

func (commandLIndex) String() string               { return "LINDEX" }
func (commandLIndex) Class() string                { return "List" }
func (commandLIndex) RequireVersion() string       { return "1.0.0" }
func (commandLIndex) Forbid() bool                 { return false }
func (commandLIndex) WarningOnce() bool            { return false }
func (commandLIndex) WarnVersion() string          { return "" }
func (commandLIndex) Warning() string              { return "" }
func (commandLIndex) Instead() string              { return "" }
func (commandLIndex) ETC() string                  { return "" }
func (commandLIndex) PR(b BaseCmd) StringCmd       { return b.(StringCmd) }
func (commandLIndex) P(p Pipeliner) commandLIndexP { return commandLIndexP{p} }
func (b commandLIndexP) Cmd(key string, index int64) {
	b.p.cmd(b.p.builder().LIndexCompleted(key, index), &stringCmd{})
}

var CommandLInsert commandLInsert

type commandLInsert string
type commandLInsertP struct{ p Pipeliner }

func (commandLInsert) String() string                { return "LINSERT" }
func (commandLInsert) Class() string                 { return "List" }
func (commandLInsert) RequireVersion() string        { return "2.2.0" }
func (commandLInsert) Forbid() bool                  { return false }
func (commandLInsert) WarningOnce() bool             { return false }
func (commandLInsert) WarnVersion() string           { return "" }
func (commandLInsert) Warning() string               { return "" }
func (commandLInsert) Instead() string               { return "" }
func (commandLInsert) ETC() string                   { return "" }
func (commandLInsert) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandLInsert) P(p Pipeliner) commandLInsertP { return commandLInsertP{p} }
func (b commandLInsertP) Cmd(key string, op string, pivot any, element any) {
	b.p.cmd(b.p.builder().LInsertCompleted(key, op, pivot, element), &intCmd{})
}

var CommandLInsertAfter commandLInsertAfter

type commandLInsertAfter string
type commandLInsertAfterP struct{ p Pipeliner }

func (commandLInsertAfter) String() string                     { return "LINSERT AFTER" }
func (commandLInsertAfter) Class() string                      { return "List" }
func (commandLInsertAfter) RequireVersion() string             { return "2.2.0" }
func (commandLInsertAfter) Forbid() bool                       { return false }
func (commandLInsertAfter) WarningOnce() bool                  { return false }
func (commandLInsertAfter) WarnVersion() string                { return "" }
func (commandLInsertAfter) Warning() string                    { return "" }
func (commandLInsertAfter) Instead() string                    { return "" }
func (commandLInsertAfter) ETC() string                        { return "" }
func (commandLInsertAfter) PR(b BaseCmd) IntCmd                { return b.(IntCmd) }
func (commandLInsertAfter) P(p Pipeliner) commandLInsertAfterP { return commandLInsertAfterP{p} }
func (b commandLInsertAfterP) Cmd(key string, pivot any, element any) {
	b.p.cmd(b.p.builder().LInsertAfterCompleted(key, pivot, element), &intCmd{})
}

var CommandLInsertBefore commandLInsertBefore

type commandLInsertBefore string
type commandLInsertBeforeP struct{ p Pipeliner }

func (commandLInsertBefore) String() string                      { return "LINSERT BEFORE" }
func (commandLInsertBefore) Class() string                       { return "List" }
func (commandLInsertBefore) RequireVersion() string              { return "2.2.0" }
func (commandLInsertBefore) Forbid() bool                        { return false }
func (commandLInsertBefore) WarningOnce() bool                   { return false }
func (commandLInsertBefore) WarnVersion() string                 { return "" }
func (commandLInsertBefore) Warning() string                     { return "" }
func (commandLInsertBefore) Instead() string                     { return "" }
func (commandLInsertBefore) ETC() string                         { return "" }
func (commandLInsertBefore) PR(b BaseCmd) IntCmd                 { return b.(IntCmd) }
func (commandLInsertBefore) P(p Pipeliner) commandLInsertBeforeP { return commandLInsertBeforeP{p} }
func (b commandLInsertBeforeP) Cmd(key string, pivot any, element any) {
	b.p.cmd(b.p.builder().LInsertBeforeCompleted(key, pivot, element), &intCmd{})
}

var CommandLLen commandLLen

type commandLLen string
type commandLLenP struct{ p Pipeliner }

func (commandLLen) String() string             { return "LLEN" }
func (commandLLen) Class() string              { return "List" }
func (commandLLen) RequireVersion() string     { return "1.0.0" }
func (commandLLen) Forbid() bool               { return false }
func (commandLLen) WarningOnce() bool          { return false }
func (commandLLen) WarnVersion() string        { return "" }
func (commandLLen) Warning() string            { return "" }
func (commandLLen) Instead() string            { return "" }
func (commandLLen) ETC() string                { return "" }
func (commandLLen) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandLLen) P(p Pipeliner) commandLLenP { return commandLLenP{p} }
func (b commandLLenP) Cmd(key string) {
	b.p.cmd(b.p.builder().LLenCompleted(key), &intCmd{})
}

var CommandLMPop commandLMPop

type commandLMPop string
type commandLMPopP struct{ p Pipeliner }

func (commandLMPop) String() string              { return "LMPOP" }
func (commandLMPop) Class() string               { return "List" }
func (commandLMPop) RequireVersion() string      { return "7.0.0" }
func (commandLMPop) Forbid() bool                { return false }
func (commandLMPop) WarningOnce() bool           { return false }
func (commandLMPop) WarnVersion() string         { return "" }
func (commandLMPop) Warning() string             { return "" }
func (commandLMPop) Instead() string             { return "" }
func (commandLMPop) ETC() string                 { return "" }
func (commandLMPop) PR(b BaseCmd) KeyValuesCmd   { return b.(KeyValuesCmd) }
func (commandLMPop) P(p Pipeliner) commandLMPopP { return commandLMPopP{p} }
func (b commandLMPopP) Cmd(direction string, count int64, keys ...string) {
	b.p.cmd(b.p.builder().LMPopCompleted(direction, count, keys...), &keyValuesCmd{})
}

var CommandLMPush commandLMPush

type commandLMPush string
type commandLMPushP struct{ p Pipeliner }

func (commandLMPush) String() string               { return "LPUSH" }
func (commandLMPush) Class() string                { return "List" }
func (commandLMPush) RequireVersion() string       { return "2.4.0" }
func (commandLMPush) Forbid() bool                 { return false }
func (commandLMPush) WarningOnce() bool            { return false }
func (commandLMPush) WarnVersion() string          { return "" }
func (commandLMPush) Warning() string              { return "" }
func (commandLMPush) Instead() string              { return "" }
func (commandLMPush) ETC() string                  { return "" }
func (commandLMPush) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandLMPush) P(p Pipeliner) commandLMPushP { return commandLMPushP{p} }
func (b commandLMPushP) Cmd(key string, elements ...any) {
	b.p.cmd(b.p.builder().LMPushCompleted(key, elements...), &intCmd{})
}

var CommandLMPushX commandLMPushX

type commandLMPushX string
type commandLMPushXP struct{ p Pipeliner }

func (commandLMPushX) String() string                { return "LPUSHX" }
func (commandLMPushX) Class() string                 { return "List" }
func (commandLMPushX) RequireVersion() string        { return "4.0.0" }
func (commandLMPushX) Forbid() bool                  { return false }
func (commandLMPushX) WarningOnce() bool             { return false }
func (commandLMPushX) WarnVersion() string           { return "" }
func (commandLMPushX) Warning() string               { return "" }
func (commandLMPushX) Instead() string               { return "" }
func (commandLMPushX) ETC() string                   { return "" }
func (commandLMPushX) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandLMPushX) P(p Pipeliner) commandLMPushXP { return commandLMPushXP{p} }
func (b commandLMPushXP) Cmd(key string, elements ...any) {
	b.p.cmd(b.p.builder().LMPushXCompleted(key, elements...), &intCmd{})
}

var CommandLMove commandLMove

type commandLMove string
type commandLMoveP struct{ p Pipeliner }

func (commandLMove) String() string              { return "LMOVE" }
func (commandLMove) Class() string               { return "List" }
func (commandLMove) RequireVersion() string      { return "6.2.0" }
func (commandLMove) Forbid() bool                { return false }
func (commandLMove) WarningOnce() bool           { return false }
func (commandLMove) WarnVersion() string         { return "" }
func (commandLMove) Warning() string             { return "" }
func (commandLMove) Instead() string             { return "" }
func (commandLMove) ETC() string                 { return "" }
func (commandLMove) PR(b BaseCmd) StringCmd      { return b.(StringCmd) }
func (commandLMove) P(p Pipeliner) commandLMoveP { return commandLMoveP{p} }
func (b commandLMoveP) Cmd(source string, destination string, srcpos string, destpos string) {
	b.p.cmd(b.p.builder().LMoveCompleted(source, destination, srcpos, destpos), &stringCmd{})
}

var CommandLPop commandLPop

type commandLPop string
type commandLPopP struct{ p Pipeliner }

func (commandLPop) String() string             { return "LPOP" }
func (commandLPop) Class() string              { return "List" }
func (commandLPop) RequireVersion() string     { return "1.0.0" }
func (commandLPop) Forbid() bool               { return false }
func (commandLPop) WarningOnce() bool          { return false }
func (commandLPop) WarnVersion() string        { return "" }
func (commandLPop) Warning() string            { return "" }
func (commandLPop) Instead() string            { return "" }
func (commandLPop) ETC() string                { return "" }
func (commandLPop) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandLPop) P(p Pipeliner) commandLPopP { return commandLPopP{p} }
func (b commandLPopP) Cmd(key string) {
	b.p.cmd(b.p.builder().LPopCompleted(key), &stringCmd{})
}

var CommandLPopCount commandLPopCount

type commandLPopCount string
type commandLPopCountP struct{ p Pipeliner }

func (commandLPopCount) String() string                  { return "LPOP COUNT" }
func (commandLPopCount) Class() string                   { return "List" }
func (commandLPopCount) RequireVersion() string          { return "6.2.0" }
func (commandLPopCount) Forbid() bool                    { return false }
func (commandLPopCount) WarningOnce() bool               { return false }
func (commandLPopCount) WarnVersion() string             { return "" }
func (commandLPopCount) Warning() string                 { return "" }
func (commandLPopCount) Instead() string                 { return "" }
func (commandLPopCount) ETC() string                     { return "" }
func (commandLPopCount) PR(b BaseCmd) StringSliceCmd     { return b.(StringSliceCmd) }
func (commandLPopCount) P(p Pipeliner) commandLPopCountP { return commandLPopCountP{p} }
func (b commandLPopCountP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().LPopCountCompleted(key, count), &stringSliceCmd{})
}

var CommandLPos commandLPos

type commandLPos string
type commandLPosP struct{ p Pipeliner }

func (commandLPos) String() string             { return "LPOS" }
func (commandLPos) Class() string              { return "List" }
func (commandLPos) RequireVersion() string     { return "6.0.6" }
func (commandLPos) Forbid() bool               { return false }
func (commandLPos) WarningOnce() bool          { return false }
func (commandLPos) WarnVersion() string        { return "" }
func (commandLPos) Warning() string            { return "" }
func (commandLPos) Instead() string            { return "" }
func (commandLPos) ETC() string                { return "" }
func (commandLPos) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandLPos) P(p Pipeliner) commandLPosP { return commandLPosP{p} }
func (b commandLPosP) Cmd(key string, element string, a LPosArgs) {
	b.p.cmd(b.p.builder().LPosCompleted(key, element, a), &intCmd{})
}

var CommandLPosCount commandLPosCount

type commandLPosCount string
type commandLPosCountP struct{ p Pipeliner }

func (commandLPosCount) String() string                  { return "LPOS COUNT" }
func (commandLPosCount) Class() string                   { return "List" }
func (commandLPosCount) RequireVersion() string          { return "6.0.6" }
func (commandLPosCount) Forbid() bool                    { return false }
func (commandLPosCount) WarningOnce() bool               { return false }
func (commandLPosCount) WarnVersion() string             { return "" }
func (commandLPosCount) Warning() string                 { return "" }
func (commandLPosCount) Instead() string                 { return "" }
func (commandLPosCount) ETC() string                     { return "" }
func (commandLPosCount) PR(b BaseCmd) IntSliceCmd        { return b.(IntSliceCmd) }
func (commandLPosCount) P(p Pipeliner) commandLPosCountP { return commandLPosCountP{p} }
func (b commandLPosCountP) Cmd(key string, element string, count int64, a LPosArgs) {
	b.p.cmd(b.p.builder().LPosCountCompleted(key, element, count, a), &intSliceCmd{})
}

var CommandLPush commandLPush

type commandLPush string
type commandLPushP struct{ p Pipeliner }

func (commandLPush) String() string              { return "LPUSH" }
func (commandLPush) Class() string               { return "List" }
func (commandLPush) RequireVersion() string      { return "1.0.0" }
func (commandLPush) Forbid() bool                { return false }
func (commandLPush) WarningOnce() bool           { return false }
func (commandLPush) WarnVersion() string         { return "" }
func (commandLPush) Warning() string             { return "" }
func (commandLPush) Instead() string             { return "" }
func (commandLPush) ETC() string                 { return "" }
func (commandLPush) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandLPush) P(p Pipeliner) commandLPushP { return commandLPushP{p} }
func (b commandLPushP) Cmd(key string, element any) {
	b.p.cmd(b.p.builder().LPushCompleted(key, element), &intCmd{})
}

var CommandLPushX commandLPushX

type commandLPushX string
type commandLPushXP struct{ p Pipeliner }

func (commandLPushX) String() string               { return "LPUSHX" }
func (commandLPushX) Class() string                { return "List" }
func (commandLPushX) RequireVersion() string       { return "2.2.0" }
func (commandLPushX) Forbid() bool                 { return false }
func (commandLPushX) WarningOnce() bool            { return false }
func (commandLPushX) WarnVersion() string          { return "" }
func (commandLPushX) Warning() string              { return "" }
func (commandLPushX) Instead() string              { return "" }
func (commandLPushX) ETC() string                  { return "" }
func (commandLPushX) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandLPushX) P(p Pipeliner) commandLPushXP { return commandLPushXP{p} }
func (b commandLPushXP) Cmd(key string, element any) {
	b.p.cmd(b.p.builder().LPushXCompleted(key, element), &intCmd{})
}

var CommandLRange commandLRange

type commandLRange string
type commandLRangeP struct{ p Pipeliner }

func (commandLRange) String() string               { return "LRANGE" }
func (commandLRange) Class() string                { return "List" }
func (commandLRange) RequireVersion() string       { return "1.0.0" }
func (commandLRange) Forbid() bool                 { return false }
func (commandLRange) WarningOnce() bool            { return false }
func (commandLRange) WarnVersion() string          { return "" }
func (commandLRange) Warning() string              { return "" }
func (commandLRange) Instead() string              { return "" }
func (commandLRange) ETC() string                  { return "" }
func (commandLRange) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandLRange) P(p Pipeliner) commandLRangeP { return commandLRangeP{p} }
func (b commandLRangeP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().LRangeCompleted(key, start, stop), &stringSliceCmd{})
}

var CommandLRem commandLRem

type commandLRem string
type commandLRemP struct{ p Pipeliner }

func (commandLRem) String() string             { return "LREM" }
func (commandLRem) Class() string              { return "List" }
func (commandLRem) RequireVersion() string     { return "1.0.0" }
func (commandLRem) Forbid() bool               { return false }
func (commandLRem) WarningOnce() bool          { return false }
func (commandLRem) WarnVersion() string        { return "" }
func (commandLRem) Warning() string            { return "" }
func (commandLRem) Instead() string            { return "" }
func (commandLRem) ETC() string                { return "" }
func (commandLRem) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandLRem) P(p Pipeliner) commandLRemP { return commandLRemP{p} }
func (b commandLRemP) Cmd(key string, count int64, element any) {
	b.p.cmd(b.p.builder().LRemCompleted(key, count, element), &intCmd{})
}

var CommandLSet commandLSet

type commandLSet string
type commandLSetP struct{ p Pipeliner }

func (commandLSet) String() string             { return "LSET" }
func (commandLSet) Class() string              { return "List" }
func (commandLSet) RequireVersion() string     { return "1.0.0" }
func (commandLSet) Forbid() bool               { return false }
func (commandLSet) WarningOnce() bool          { return false }
func (commandLSet) WarnVersion() string        { return "" }
func (commandLSet) Warning() string            { return "" }
func (commandLSet) Instead() string            { return "" }
func (commandLSet) ETC() string                { return "" }
func (commandLSet) PR(b BaseCmd) StatusCmd     { return b.(StatusCmd) }
func (commandLSet) P(p Pipeliner) commandLSetP { return commandLSetP{p} }
func (b commandLSetP) Cmd(key string, index int64, element any) {
	b.p.cmd(b.p.builder().LSetCompleted(key, index, element), &statusCmd{})
}

var CommandLTrim commandLTrim

type commandLTrim string
type commandLTrimP struct{ p Pipeliner }

func (commandLTrim) String() string              { return "LTRIM" }
func (commandLTrim) Class() string               { return "List" }
func (commandLTrim) RequireVersion() string      { return "1.0.0" }
func (commandLTrim) Forbid() bool                { return false }
func (commandLTrim) WarningOnce() bool           { return false }
func (commandLTrim) WarnVersion() string         { return "" }
func (commandLTrim) Warning() string             { return "" }
func (commandLTrim) Instead() string             { return "" }
func (commandLTrim) ETC() string                 { return "" }
func (commandLTrim) PR(b BaseCmd) StatusCmd      { return b.(StatusCmd) }
func (commandLTrim) P(p Pipeliner) commandLTrimP { return commandLTrimP{p} }
func (b commandLTrimP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().LTrimCompleted(key, start, stop), &statusCmd{})
}

var CommandRMPush commandRMPush

type commandRMPush string
type commandRMPushP struct{ p Pipeliner }

func (commandRMPush) String() string               { return "RPUSH" }
func (commandRMPush) Class() string                { return "List" }
func (commandRMPush) RequireVersion() string       { return "2.4.0" }
func (commandRMPush) Forbid() bool                 { return false }
func (commandRMPush) WarningOnce() bool            { return false }
func (commandRMPush) WarnVersion() string          { return "" }
func (commandRMPush) Warning() string              { return "" }
func (commandRMPush) Instead() string              { return "" }
func (commandRMPush) ETC() string                  { return "" }
func (commandRMPush) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandRMPush) P(p Pipeliner) commandRMPushP { return commandRMPushP{p} }
func (b commandRMPushP) Cmd(key string, elements ...any) {
	b.p.cmd(b.p.builder().RMPushCompleted(key, elements...), &intCmd{})
}

var CommandRMPushX commandRMPushX

type commandRMPushX string
type commandRMPushXP struct{ p Pipeliner }

func (commandRMPushX) String() string                { return "RPUSHX" }
func (commandRMPushX) Class() string                 { return "List" }
func (commandRMPushX) RequireVersion() string        { return "4.0.0" }
func (commandRMPushX) Forbid() bool                  { return false }
func (commandRMPushX) WarningOnce() bool             { return false }
func (commandRMPushX) WarnVersion() string           { return "" }
func (commandRMPushX) Warning() string               { return "" }
func (commandRMPushX) Instead() string               { return "" }
func (commandRMPushX) ETC() string                   { return "" }
func (commandRMPushX) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandRMPushX) P(p Pipeliner) commandRMPushXP { return commandRMPushXP{p} }
func (b commandRMPushXP) Cmd(key string, elements ...any) {
	b.p.cmd(b.p.builder().RMPushXCompleted(key, elements...), &intCmd{})
}

var CommandRPop commandRPop

type commandRPop string
type commandRPopP struct{ p Pipeliner }

func (commandRPop) String() string             { return "RPOP" }
func (commandRPop) Class() string              { return "List" }
func (commandRPop) RequireVersion() string     { return "1.0.0" }
func (commandRPop) Forbid() bool               { return false }
func (commandRPop) WarningOnce() bool          { return false }
func (commandRPop) WarnVersion() string        { return "" }
func (commandRPop) Warning() string            { return "" }
func (commandRPop) Instead() string            { return "" }
func (commandRPop) ETC() string                { return "" }
func (commandRPop) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandRPop) P(p Pipeliner) commandRPopP { return commandRPopP{p} }
func (b commandRPopP) Cmd(key string) {
	b.p.cmd(b.p.builder().RPopCompleted(key), &stringCmd{})
}

var CommandRPopCount commandRPopCount

type commandRPopCount string
type commandRPopCountP struct{ p Pipeliner }

func (commandRPopCount) String() string                  { return "RPOP" }
func (commandRPopCount) Class() string                   { return "List" }
func (commandRPopCount) RequireVersion() string          { return "6.2.0" }
func (commandRPopCount) Forbid() bool                    { return false }
func (commandRPopCount) WarningOnce() bool               { return false }
func (commandRPopCount) WarnVersion() string             { return "" }
func (commandRPopCount) Warning() string                 { return "" }
func (commandRPopCount) Instead() string                 { return "" }
func (commandRPopCount) ETC() string                     { return "" }
func (commandRPopCount) PR(b BaseCmd) StringSliceCmd     { return b.(StringSliceCmd) }
func (commandRPopCount) P(p Pipeliner) commandRPopCountP { return commandRPopCountP{p} }
func (b commandRPopCountP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().RPopCountCompleted(key, count), &stringSliceCmd{})
}

var CommandRPopLPush commandRPopLPush

type commandRPopLPush string
type commandRPopLPushP struct{ p Pipeliner }

func (commandRPopLPush) String() string         { return "RPOPLPUSH" }
func (commandRPopLPush) Class() string          { return "List" }
func (commandRPopLPush) RequireVersion() string { return "1.2.0" }
func (commandRPopLPush) Forbid() bool           { return false }
func (commandRPopLPush) WarningOnce() bool      { return false }
func (commandRPopLPush) WarnVersion() string    { return "6.2.0" }
func (commandRPopLPush) Warning() string        { return commandRPopLPushWarning }
func (commandRPopLPush) Instead() string        { return "LMove" }
func (commandRPopLPush) ETC() string {
	return "client.LMove(ctx, source, destination, redisson.RIGHT, redisson.LEFT)"
}
func (commandRPopLPush) PR(b BaseCmd) StringCmd          { return b.(StringCmd) }
func (commandRPopLPush) P(p Pipeliner) commandRPopLPushP { return commandRPopLPushP{p} }
func (b commandRPopLPushP) Cmd(source string, destination string) {
	b.p.cmd(b.p.builder().RPopLPushCompleted(source, destination), &stringCmd{})
}

var CommandRPush commandRPush

type commandRPush string
type commandRPushP struct{ p Pipeliner }

func (commandRPush) String() string              { return "RPUSH" }
func (commandRPush) Class() string               { return "List" }
func (commandRPush) RequireVersion() string      { return "1.0.0" }
func (commandRPush) Forbid() bool                { return false }
func (commandRPush) WarningOnce() bool           { return false }
func (commandRPush) WarnVersion() string         { return "" }
func (commandRPush) Warning() string             { return "" }
func (commandRPush) Instead() string             { return "" }
func (commandRPush) ETC() string                 { return "" }
func (commandRPush) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandRPush) P(p Pipeliner) commandRPushP { return commandRPushP{p} }
func (b commandRPushP) Cmd(key string, element any) {
	b.p.cmd(b.p.builder().RPushCompleted(key, element), &intCmd{})
}

var CommandRPushX commandRPushX

type commandRPushX string
type commandRPushXP struct{ p Pipeliner }

func (commandRPushX) String() string               { return "RPUSHX" }
func (commandRPushX) Class() string                { return "List" }
func (commandRPushX) RequireVersion() string       { return "2.2.0" }
func (commandRPushX) Forbid() bool                 { return false }
func (commandRPushX) WarningOnce() bool            { return false }
func (commandRPushX) WarnVersion() string          { return "" }
func (commandRPushX) Warning() string              { return "" }
func (commandRPushX) Instead() string              { return "" }
func (commandRPushX) ETC() string                  { return "" }
func (commandRPushX) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandRPushX) P(p Pipeliner) commandRPushXP { return commandRPushXP{p} }
func (b commandRPushXP) Cmd(key string, element any) {
	b.p.cmd(b.p.builder().RPushXCompleted(key, element), &intCmd{})
}
