// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandEval commandEval

type commandEval string

func (commandEval) String() string         { return "EVAL" }
func (commandEval) Class() string          { return "Scripting" }
func (commandEval) RequireVersion() string { return "2.6.0" }
func (commandEval) Forbid() bool           { return false }
func (commandEval) WarningOnce() bool      { return false }
func (commandEval) WarnVersion() string    { return "" }
func (commandEval) Warning() string        { return "" }
func (commandEval) Instead() string        { return "" }
func (commandEval) ETC() string            { return "" }

var CommandEvalRO commandEvalRO

type commandEvalRO string

func (commandEvalRO) String() string         { return "EVAL_RO" }
func (commandEvalRO) Class() string          { return "Scripting" }
func (commandEvalRO) RequireVersion() string { return "7.0.0" }
func (commandEvalRO) Forbid() bool           { return false }
func (commandEvalRO) WarningOnce() bool      { return false }
func (commandEvalRO) WarnVersion() string    { return "" }
func (commandEvalRO) Warning() string        { return "" }
func (commandEvalRO) Instead() string        { return "" }
func (commandEvalRO) ETC() string            { return "" }

var CommandEvalSha commandEvalSha

type commandEvalSha string

func (commandEvalSha) String() string         { return "EVALSHA" }
func (commandEvalSha) Class() string          { return "Scripting" }
func (commandEvalSha) RequireVersion() string { return "2.6.0" }
func (commandEvalSha) Forbid() bool           { return false }
func (commandEvalSha) WarningOnce() bool      { return false }
func (commandEvalSha) WarnVersion() string    { return "" }
func (commandEvalSha) Warning() string        { return "" }
func (commandEvalSha) Instead() string        { return "" }
func (commandEvalSha) ETC() string            { return "" }

var CommandEvalShaRO commandEvalShaRO

type commandEvalShaRO string

func (commandEvalShaRO) String() string         { return "EVALSHA_RO" }
func (commandEvalShaRO) Class() string          { return "Scripting" }
func (commandEvalShaRO) RequireVersion() string { return "7.0.0" }
func (commandEvalShaRO) Forbid() bool           { return false }
func (commandEvalShaRO) WarningOnce() bool      { return false }
func (commandEvalShaRO) WarnVersion() string    { return "" }
func (commandEvalShaRO) Warning() string        { return "" }
func (commandEvalShaRO) Instead() string        { return "" }
func (commandEvalShaRO) ETC() string            { return "" }

var CommandFCall commandFCall

type commandFCall string

func (commandFCall) String() string         { return "FCALL" }
func (commandFCall) Class() string          { return "Scripting" }
func (commandFCall) RequireVersion() string { return "7.0.0" }
func (commandFCall) Forbid() bool           { return false }
func (commandFCall) WarningOnce() bool      { return false }
func (commandFCall) WarnVersion() string    { return "" }
func (commandFCall) Warning() string        { return "" }
func (commandFCall) Instead() string        { return "" }
func (commandFCall) ETC() string            { return "" }

var CommandFCallRO commandFCallRO

type commandFCallRO string

func (commandFCallRO) String() string         { return "FCALL_RO" }
func (commandFCallRO) Class() string          { return "Scripting" }
func (commandFCallRO) RequireVersion() string { return "7.0.0" }
func (commandFCallRO) Forbid() bool           { return false }
func (commandFCallRO) WarningOnce() bool      { return false }
func (commandFCallRO) WarnVersion() string    { return "" }
func (commandFCallRO) Warning() string        { return "" }
func (commandFCallRO) Instead() string        { return "" }
func (commandFCallRO) ETC() string            { return "" }

var CommandFunctionDelete commandFunctionDelete

type commandFunctionDelete string

func (commandFunctionDelete) String() string         { return "FUNCTION DELETE" }
func (commandFunctionDelete) Class() string          { return "Scripting" }
func (commandFunctionDelete) RequireVersion() string { return "7.0.0" }
func (commandFunctionDelete) Forbid() bool           { return false }
func (commandFunctionDelete) WarningOnce() bool      { return false }
func (commandFunctionDelete) WarnVersion() string    { return "" }
func (commandFunctionDelete) Warning() string        { return "" }
func (commandFunctionDelete) Instead() string        { return "" }
func (commandFunctionDelete) ETC() string            { return "" }

var CommandFunctionDump commandFunctionDump

type commandFunctionDump string

func (commandFunctionDump) String() string         { return "FUNCTION DUMP" }
func (commandFunctionDump) Class() string          { return "Scripting" }
func (commandFunctionDump) RequireVersion() string { return "7.0.0" }
func (commandFunctionDump) Forbid() bool           { return false }
func (commandFunctionDump) WarningOnce() bool      { return false }
func (commandFunctionDump) WarnVersion() string    { return "" }
func (commandFunctionDump) Warning() string        { return "" }
func (commandFunctionDump) Instead() string        { return "" }
func (commandFunctionDump) ETC() string            { return "" }

var CommandFunctionFlush commandFunctionFlush

type commandFunctionFlush string

func (commandFunctionFlush) String() string         { return "FUNCTION FLUSH" }
func (commandFunctionFlush) Class() string          { return "Scripting" }
func (commandFunctionFlush) RequireVersion() string { return "7.0.0" }
func (commandFunctionFlush) Forbid() bool           { return false }
func (commandFunctionFlush) WarningOnce() bool      { return false }
func (commandFunctionFlush) WarnVersion() string    { return "" }
func (commandFunctionFlush) Warning() string        { return "" }
func (commandFunctionFlush) Instead() string        { return "" }
func (commandFunctionFlush) ETC() string            { return "" }

var CommandFunctionFlushAsync commandFunctionFlushAsync

type commandFunctionFlushAsync string

func (commandFunctionFlushAsync) String() string         { return "FUNCTION FLUSH ASYNC" }
func (commandFunctionFlushAsync) Class() string          { return "Scripting" }
func (commandFunctionFlushAsync) RequireVersion() string { return "7.0.0" }
func (commandFunctionFlushAsync) Forbid() bool           { return false }
func (commandFunctionFlushAsync) WarningOnce() bool      { return false }
func (commandFunctionFlushAsync) WarnVersion() string    { return "" }
func (commandFunctionFlushAsync) Warning() string        { return "" }
func (commandFunctionFlushAsync) Instead() string        { return "" }
func (commandFunctionFlushAsync) ETC() string            { return "" }

var CommandFunctionKill commandFunctionKill

type commandFunctionKill string

func (commandFunctionKill) String() string         { return "FUNCTION KILL" }
func (commandFunctionKill) Class() string          { return "Scripting" }
func (commandFunctionKill) RequireVersion() string { return "7.0.0" }
func (commandFunctionKill) Forbid() bool           { return false }
func (commandFunctionKill) WarningOnce() bool      { return false }
func (commandFunctionKill) WarnVersion() string    { return "" }
func (commandFunctionKill) Warning() string        { return "" }
func (commandFunctionKill) Instead() string        { return "" }
func (commandFunctionKill) ETC() string            { return "" }

var CommandFunctionList commandFunctionList

type commandFunctionList string

func (commandFunctionList) String() string         { return "FUNCTION LIST" }
func (commandFunctionList) Class() string          { return "Scripting" }
func (commandFunctionList) RequireVersion() string { return "7.0.0" }
func (commandFunctionList) Forbid() bool           { return false }
func (commandFunctionList) WarningOnce() bool      { return false }
func (commandFunctionList) WarnVersion() string    { return "" }
func (commandFunctionList) Warning() string        { return "" }
func (commandFunctionList) Instead() string        { return "" }
func (commandFunctionList) ETC() string            { return "" }

var CommandFunctionLoad commandFunctionLoad

type commandFunctionLoad string

func (commandFunctionLoad) String() string         { return "FUNCTION LOAD" }
func (commandFunctionLoad) Class() string          { return "Scripting" }
func (commandFunctionLoad) RequireVersion() string { return "7.0.0" }
func (commandFunctionLoad) Forbid() bool           { return false }
func (commandFunctionLoad) WarningOnce() bool      { return false }
func (commandFunctionLoad) WarnVersion() string    { return "" }
func (commandFunctionLoad) Warning() string        { return "" }
func (commandFunctionLoad) Instead() string        { return "" }
func (commandFunctionLoad) ETC() string            { return "" }

var CommandFunctionLoadReplace commandFunctionLoadReplace

type commandFunctionLoadReplace string

func (commandFunctionLoadReplace) String() string         { return "FUNCTION LOAD REPLACE" }
func (commandFunctionLoadReplace) Class() string          { return "Scripting" }
func (commandFunctionLoadReplace) RequireVersion() string { return "7.0.0" }
func (commandFunctionLoadReplace) Forbid() bool           { return false }
func (commandFunctionLoadReplace) WarningOnce() bool      { return false }
func (commandFunctionLoadReplace) WarnVersion() string    { return "" }
func (commandFunctionLoadReplace) Warning() string        { return "" }
func (commandFunctionLoadReplace) Instead() string        { return "" }
func (commandFunctionLoadReplace) ETC() string            { return "" }

var CommandFunctionRestore commandFunctionRestore

type commandFunctionRestore string

func (commandFunctionRestore) String() string         { return "FUNCTION RESTORE" }
func (commandFunctionRestore) Class() string          { return "Scripting" }
func (commandFunctionRestore) RequireVersion() string { return "7.0.0" }
func (commandFunctionRestore) Forbid() bool           { return false }
func (commandFunctionRestore) WarningOnce() bool      { return false }
func (commandFunctionRestore) WarnVersion() string    { return "" }
func (commandFunctionRestore) Warning() string        { return "" }
func (commandFunctionRestore) Instead() string        { return "" }
func (commandFunctionRestore) ETC() string            { return "" }

var CommandScriptExists commandScriptExists

type commandScriptExists string

func (commandScriptExists) String() string         { return "SCRIPT EXISTS" }
func (commandScriptExists) Class() string          { return "Scripting" }
func (commandScriptExists) RequireVersion() string { return "2.6.0" }
func (commandScriptExists) Forbid() bool           { return false }
func (commandScriptExists) WarningOnce() bool      { return false }
func (commandScriptExists) WarnVersion() string    { return "" }
func (commandScriptExists) Warning() string        { return "" }
func (commandScriptExists) Instead() string        { return "" }
func (commandScriptExists) ETC() string            { return "" }

var CommandScriptFlush commandScriptFlush

type commandScriptFlush string

func (commandScriptFlush) String() string         { return "SCRIPT FLUSH" }
func (commandScriptFlush) Class() string          { return "Scripting" }
func (commandScriptFlush) RequireVersion() string { return "2.6.0" }
func (commandScriptFlush) Forbid() bool           { return false }
func (commandScriptFlush) WarningOnce() bool      { return false }
func (commandScriptFlush) WarnVersion() string    { return "" }
func (commandScriptFlush) Warning() string        { return "" }
func (commandScriptFlush) Instead() string        { return "" }
func (commandScriptFlush) ETC() string            { return "" }

var CommandScriptKill commandScriptKill

type commandScriptKill string

func (commandScriptKill) String() string         { return "SCRIPT KILL" }
func (commandScriptKill) Class() string          { return "Scripting" }
func (commandScriptKill) RequireVersion() string { return "2.6.0" }
func (commandScriptKill) Forbid() bool           { return false }
func (commandScriptKill) WarningOnce() bool      { return false }
func (commandScriptKill) WarnVersion() string    { return "" }
func (commandScriptKill) Warning() string        { return "" }
func (commandScriptKill) Instead() string        { return "" }
func (commandScriptKill) ETC() string            { return "" }

var CommandScriptLoad commandScriptLoad

type commandScriptLoad string

func (commandScriptLoad) String() string         { return "SCRIPT LOAD" }
func (commandScriptLoad) Class() string          { return "Scripting" }
func (commandScriptLoad) RequireVersion() string { return "2.6.0" }
func (commandScriptLoad) Forbid() bool           { return false }
func (commandScriptLoad) WarningOnce() bool      { return false }
func (commandScriptLoad) WarnVersion() string    { return "" }
func (commandScriptLoad) Warning() string        { return "" }
func (commandScriptLoad) Instead() string        { return "" }
func (commandScriptLoad) ETC() string            { return "" }
