// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandClientGetName commandClientGetName

type commandClientGetName string

func (commandClientGetName) String() string         { return "CLIENT GETNAME" }
func (commandClientGetName) Class() string          { return "Connection" }
func (commandClientGetName) RequireVersion() string { return "2.6.9" }
func (commandClientGetName) Forbid() bool           { return false }
func (commandClientGetName) WarningOnce() bool      { return false }
func (commandClientGetName) WarnVersion() string    { return "" }
func (commandClientGetName) Warning() string        { return "" }
func (commandClientGetName) Instead() string        { return "" }
func (commandClientGetName) ETC() string            { return "" }

var CommandClientID commandClientID

type commandClientID string

func (commandClientID) String() string         { return "CLIENT ID" }
func (commandClientID) Class() string          { return "Connection" }
func (commandClientID) RequireVersion() string { return "5.0.0" }
func (commandClientID) Forbid() bool           { return false }
func (commandClientID) WarningOnce() bool      { return false }
func (commandClientID) WarnVersion() string    { return "" }
func (commandClientID) Warning() string        { return "" }
func (commandClientID) Instead() string        { return "" }
func (commandClientID) ETC() string            { return "" }

var CommandClientKill commandClientKill

type commandClientKill string

func (commandClientKill) String() string         { return "CLIENT KILL" }
func (commandClientKill) Class() string          { return "Connection" }
func (commandClientKill) RequireVersion() string { return "2.4.0" }
func (commandClientKill) Forbid() bool           { return true }
func (commandClientKill) WarningOnce() bool      { return false }
func (commandClientKill) WarnVersion() string    { return "" }
func (commandClientKill) Warning() string        { return "" }
func (commandClientKill) Instead() string        { return "" }
func (commandClientKill) ETC() string            { return "" }

var CommandClientKillByFilter commandClientKillByFilter

type commandClientKillByFilter string

func (commandClientKillByFilter) String() string         { return "CLIENT KILL" }
func (commandClientKillByFilter) Class() string          { return "Connection" }
func (commandClientKillByFilter) RequireVersion() string { return "2.8.12" }
func (commandClientKillByFilter) Forbid() bool           { return true }
func (commandClientKillByFilter) WarningOnce() bool      { return false }
func (commandClientKillByFilter) WarnVersion() string    { return "" }
func (commandClientKillByFilter) Warning() string        { return "" }
func (commandClientKillByFilter) Instead() string        { return "" }
func (commandClientKillByFilter) ETC() string            { return "" }

var CommandClientKillByFilterWithLADDR commandClientKillByFilterWithLADDR

type commandClientKillByFilterWithLADDR string

func (commandClientKillByFilterWithLADDR) String() string         { return "CLIENT KILL" }
func (commandClientKillByFilterWithLADDR) Class() string          { return "Connection" }
func (commandClientKillByFilterWithLADDR) RequireVersion() string { return "6.2.0" }
func (commandClientKillByFilterWithLADDR) Forbid() bool           { return true }
func (commandClientKillByFilterWithLADDR) WarningOnce() bool      { return false }
func (commandClientKillByFilterWithLADDR) WarnVersion() string    { return "" }
func (commandClientKillByFilterWithLADDR) Warning() string        { return "" }
func (commandClientKillByFilterWithLADDR) Instead() string        { return "" }
func (commandClientKillByFilterWithLADDR) ETC() string            { return "" }

var CommandClientKillByFilterWithType commandClientKillByFilterWithType

type commandClientKillByFilterWithType string

func (commandClientKillByFilterWithType) String() string         { return "CLIENT KILL" }
func (commandClientKillByFilterWithType) Class() string          { return "Connection" }
func (commandClientKillByFilterWithType) RequireVersion() string { return "3.2.0" }
func (commandClientKillByFilterWithType) Forbid() bool           { return true }
func (commandClientKillByFilterWithType) WarningOnce() bool      { return false }
func (commandClientKillByFilterWithType) WarnVersion() string    { return "" }
func (commandClientKillByFilterWithType) Warning() string        { return "" }
func (commandClientKillByFilterWithType) Instead() string        { return "" }
func (commandClientKillByFilterWithType) ETC() string            { return "" }

var CommandClientList commandClientList

type commandClientList string

func (commandClientList) String() string         { return "CLIENT LIST" }
func (commandClientList) Class() string          { return "Connection" }
func (commandClientList) RequireVersion() string { return "2.4.0" }
func (commandClientList) Forbid() bool           { return true }
func (commandClientList) WarningOnce() bool      { return false }
func (commandClientList) WarnVersion() string    { return "" }
func (commandClientList) Warning() string        { return "" }
func (commandClientList) Instead() string        { return "" }
func (commandClientList) ETC() string            { return "" }

var CommandClientPause commandClientPause

type commandClientPause string

func (commandClientPause) String() string         { return "CLIENT PAUSE" }
func (commandClientPause) Class() string          { return "Connection" }
func (commandClientPause) RequireVersion() string { return "3.0.0" }
func (commandClientPause) Forbid() bool           { return true }
func (commandClientPause) WarningOnce() bool      { return false }
func (commandClientPause) WarnVersion() string    { return "" }
func (commandClientPause) Warning() string        { return "" }
func (commandClientPause) Instead() string        { return "" }
func (commandClientPause) ETC() string            { return "" }

var CommandClientUnblock commandClientUnblock

type commandClientUnblock string

func (commandClientUnblock) String() string         { return "CLIENT UNBLOCK" }
func (commandClientUnblock) Class() string          { return "Connection" }
func (commandClientUnblock) RequireVersion() string { return "5.0.0" }
func (commandClientUnblock) Forbid() bool           { return true }
func (commandClientUnblock) WarningOnce() bool      { return false }
func (commandClientUnblock) WarnVersion() string    { return "" }
func (commandClientUnblock) Warning() string        { return "" }
func (commandClientUnblock) Instead() string        { return "" }
func (commandClientUnblock) ETC() string            { return "" }

var CommandClientUnblockWithError commandClientUnblockWithError

type commandClientUnblockWithError string

func (commandClientUnblockWithError) String() string         { return "CLIENT UNBLOCK" }
func (commandClientUnblockWithError) Class() string          { return "Connection" }
func (commandClientUnblockWithError) RequireVersion() string { return "5.0.0" }
func (commandClientUnblockWithError) Forbid() bool           { return true }
func (commandClientUnblockWithError) WarningOnce() bool      { return false }
func (commandClientUnblockWithError) WarnVersion() string    { return "" }
func (commandClientUnblockWithError) Warning() string        { return "" }
func (commandClientUnblockWithError) Instead() string        { return "" }
func (commandClientUnblockWithError) ETC() string            { return "" }

var CommandClientUnpause commandClientUnpause

type commandClientUnpause string

func (commandClientUnpause) String() string         { return "CLIENT UNPAUSE" }
func (commandClientUnpause) Class() string          { return "Connection" }
func (commandClientUnpause) RequireVersion() string { return "6.2.0" }
func (commandClientUnpause) Forbid() bool           { return true }
func (commandClientUnpause) WarningOnce() bool      { return false }
func (commandClientUnpause) WarnVersion() string    { return "" }
func (commandClientUnpause) Warning() string        { return "" }
func (commandClientUnpause) Instead() string        { return "" }
func (commandClientUnpause) ETC() string            { return "" }

var CommandEcho commandEcho

type commandEcho string
type commandEchoP struct{ p Pipeliner }

func (commandEcho) String() string             { return "ECHO" }
func (commandEcho) Class() string              { return "Connection" }
func (commandEcho) RequireVersion() string     { return "1.0.0" }
func (commandEcho) Forbid() bool               { return false }
func (commandEcho) WarningOnce() bool          { return false }
func (commandEcho) WarnVersion() string        { return "" }
func (commandEcho) Warning() string            { return "" }
func (commandEcho) Instead() string            { return "" }
func (commandEcho) ETC() string                { return "" }
func (commandEcho) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandEcho) P(p Pipeliner) commandEchoP { return commandEchoP{p} }
func (b commandEchoP) Cmd(message any) {
	b.p.cmd(b.p.builder().EchoCompleted(message), &stringCmd{})
}

var CommandPing commandPing

type commandPing string
type commandPingP struct{ p Pipeliner }

func (commandPing) String() string             { return "PING" }
func (commandPing) Class() string              { return "Connection" }
func (commandPing) RequireVersion() string     { return "1.0.0" }
func (commandPing) Forbid() bool               { return false }
func (commandPing) WarningOnce() bool          { return false }
func (commandPing) WarnVersion() string        { return "" }
func (commandPing) Warning() string            { return "" }
func (commandPing) Instead() string            { return "" }
func (commandPing) ETC() string                { return "" }
func (commandPing) PR(b BaseCmd) StatusCmd     { return b.(StatusCmd) }
func (commandPing) P(p Pipeliner) commandPingP { return commandPingP{p} }
func (b commandPingP) Cmd() {
	b.p.cmd(b.p.builder().PingCompleted(), &statusCmd{})
}

var CommandQuit commandQuit

type commandQuit string

func (commandQuit) String() string         { return "QUIT" }
func (commandQuit) Class() string          { return "Connection" }
func (commandQuit) RequireVersion() string { return "1.0.0" }
func (commandQuit) Forbid() bool           { return false }
func (commandQuit) WarningOnce() bool      { return false }
func (commandQuit) WarnVersion() string    { return "7.2.0" }
func (commandQuit) Warning() string        { return commandQuitWarning }
func (commandQuit) Instead() string        { return "" }
func (commandQuit) ETC() string            { return "" }
