// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandPFAdd commandPFAdd

type commandPFAdd string
type commandPFAddP struct{ p Pipeliner }

func (commandPFAdd) String() string              { return "PFADD" }
func (commandPFAdd) Class() string               { return "HyperLog" }
func (commandPFAdd) RequireVersion() string      { return "2.8.9" }
func (commandPFAdd) Forbid() bool                { return false }
func (commandPFAdd) WarningOnce() bool           { return false }
func (commandPFAdd) WarnVersion() string         { return "" }
func (commandPFAdd) Warning() string             { return "" }
func (commandPFAdd) Instead() string             { return "" }
func (commandPFAdd) ETC() string                 { return "" }
func (commandPFAdd) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandPFAdd) P(p Pipeliner) commandPFAddP { return commandPFAddP{p} }
func (b commandPFAddP) Cmd(key string, els ...any) {
	b.p.cmd(b.p.builder().PFAddCompleted(key, els...), &intCmd{})
}

var CommandPFCount commandPFCount

type commandPFCount string
type commandPFCountP struct{ p Pipeliner }

func (commandPFCount) String() string                { return "PFCOUNT" }
func (commandPFCount) Class() string                 { return "HyperLog" }
func (commandPFCount) RequireVersion() string        { return "2.8.9" }
func (commandPFCount) Forbid() bool                  { return false }
func (commandPFCount) WarningOnce() bool             { return false }
func (commandPFCount) WarnVersion() string           { return "" }
func (commandPFCount) Warning() string               { return "" }
func (commandPFCount) Instead() string               { return "" }
func (commandPFCount) ETC() string                   { return "" }
func (commandPFCount) PR(b BaseCmd) IntCmd           { return b.(IntCmd) }
func (commandPFCount) P(p Pipeliner) commandPFCountP { return commandPFCountP{p} }
func (b commandPFCountP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().PFCountCompleted(keys...), &intCmd{})
}

var CommandPFMerge commandPFMerge

type commandPFMerge string
type commandPFMergeP struct{ p Pipeliner }

func (commandPFMerge) String() string                { return "PFMERGE" }
func (commandPFMerge) Class() string                 { return "HyperLog" }
func (commandPFMerge) RequireVersion() string        { return "2.8.9" }
func (commandPFMerge) Forbid() bool                  { return false }
func (commandPFMerge) WarningOnce() bool             { return false }
func (commandPFMerge) WarnVersion() string           { return "" }
func (commandPFMerge) Warning() string               { return "" }
func (commandPFMerge) Instead() string               { return "" }
func (commandPFMerge) ETC() string                   { return "" }
func (commandPFMerge) PR(b BaseCmd) StatusCmd        { return b.(StatusCmd) }
func (commandPFMerge) P(p Pipeliner) commandPFMergeP { return commandPFMergeP{p} }
func (b commandPFMergeP) Cmd(dest string, keys ...string) {
	b.p.cmd(b.p.builder().PFMergeCompleted(dest, keys...), &statusCmd{})
}
