// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandXAck commandXAck

type commandXAck string
type commandXAckP struct{ p Pipeliner }

func (commandXAck) String() string             { return "XACK" }
func (commandXAck) Class() string              { return "Stream" }
func (commandXAck) RequireVersion() string     { return "5.0.0" }
func (commandXAck) Forbid() bool               { return false }
func (commandXAck) WarningOnce() bool          { return false }
func (commandXAck) WarnVersion() string        { return "" }
func (commandXAck) Warning() string            { return "" }
func (commandXAck) Instead() string            { return "" }
func (commandXAck) ETC() string                { return "" }
func (commandXAck) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandXAck) P(p Pipeliner) commandXAckP { return commandXAckP{p} }
func (b commandXAckP) Cmd(stream string, group string, ids ...string) {
	b.p.cmd(b.p.builder().XAckCompleted(stream, group, ids...), &intCmd{})
}

var CommandXAdd commandXAdd

type commandXAdd string
type commandXAddP struct{ p Pipeliner }

func (commandXAdd) String() string             { return "XADD" }
func (commandXAdd) Class() string              { return "Stream" }
func (commandXAdd) RequireVersion() string     { return "5.0.0" }
func (commandXAdd) Forbid() bool               { return false }
func (commandXAdd) WarningOnce() bool          { return false }
func (commandXAdd) WarnVersion() string        { return "" }
func (commandXAdd) Warning() string            { return "" }
func (commandXAdd) Instead() string            { return "" }
func (commandXAdd) ETC() string                { return "" }
func (commandXAdd) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandXAdd) P(p Pipeliner) commandXAddP { return commandXAddP{p} }
func (b commandXAddP) Cmd(a XAddArgs) {
	b.p.cmd(b.p.builder().XAddCompleted(a), &stringCmd{})
}

var CommandXAddLimit commandXAddLimit

type commandXAddLimit string

func (commandXAddLimit) String() string         { return "XADD LIMIT" }
func (commandXAddLimit) Class() string          { return "Stream" }
func (commandXAddLimit) RequireVersion() string { return "6.2.0" }
func (commandXAddLimit) Forbid() bool           { return false }
func (commandXAddLimit) WarningOnce() bool      { return false }
func (commandXAddLimit) WarnVersion() string    { return "" }
func (commandXAddLimit) Warning() string        { return "" }
func (commandXAddLimit) Instead() string        { return "" }
func (commandXAddLimit) ETC() string            { return "" }

var CommandXAddMaxLen commandXAddMaxLen

type commandXAddMaxLen string

func (commandXAddMaxLen) String() string         { return "XADD MAXLEN" }
func (commandXAddMaxLen) Class() string          { return "Stream" }
func (commandXAddMaxLen) RequireVersion() string { return "6.2.0" }
func (commandXAddMaxLen) Forbid() bool           { return false }
func (commandXAddMaxLen) WarningOnce() bool      { return false }
func (commandXAddMaxLen) WarnVersion() string    { return "" }
func (commandXAddMaxLen) Warning() string        { return "" }
func (commandXAddMaxLen) Instead() string        { return "" }
func (commandXAddMaxLen) ETC() string            { return "" }

var CommandXAddMinID commandXAddMinID

type commandXAddMinID string

func (commandXAddMinID) String() string         { return "XADD MINID" }
func (commandXAddMinID) Class() string          { return "Stream" }
func (commandXAddMinID) RequireVersion() string { return "6.2.0" }
func (commandXAddMinID) Forbid() bool           { return false }
func (commandXAddMinID) WarningOnce() bool      { return false }
func (commandXAddMinID) WarnVersion() string    { return "" }
func (commandXAddMinID) Warning() string        { return "" }
func (commandXAddMinID) Instead() string        { return "" }
func (commandXAddMinID) ETC() string            { return "" }

var CommandXAddNoMKStream commandXAddNoMKStream

type commandXAddNoMKStream string

func (commandXAddNoMKStream) String() string         { return "XADD NOMKSTREAM" }
func (commandXAddNoMKStream) Class() string          { return "Stream" }
func (commandXAddNoMKStream) RequireVersion() string { return "6.2.0" }
func (commandXAddNoMKStream) Forbid() bool           { return false }
func (commandXAddNoMKStream) WarningOnce() bool      { return false }
func (commandXAddNoMKStream) WarnVersion() string    { return "" }
func (commandXAddNoMKStream) Warning() string        { return "" }
func (commandXAddNoMKStream) Instead() string        { return "" }
func (commandXAddNoMKStream) ETC() string            { return "" }

var CommandXAutoClaim commandXAutoClaim

type commandXAutoClaim string
type commandXAutoClaimP struct{ p Pipeliner }

func (commandXAutoClaim) String() string                   { return "XAUTOCLAIM" }
func (commandXAutoClaim) Class() string                    { return "Stream" }
func (commandXAutoClaim) RequireVersion() string           { return "6.2.0" }
func (commandXAutoClaim) Forbid() bool                     { return false }
func (commandXAutoClaim) WarningOnce() bool                { return false }
func (commandXAutoClaim) WarnVersion() string              { return "" }
func (commandXAutoClaim) Warning() string                  { return "" }
func (commandXAutoClaim) Instead() string                  { return "" }
func (commandXAutoClaim) ETC() string                      { return "" }
func (commandXAutoClaim) PR(b BaseCmd) XAutoClaimCmd       { return b.(XAutoClaimCmd) }
func (commandXAutoClaim) P(p Pipeliner) commandXAutoClaimP { return commandXAutoClaimP{p} }
func (b commandXAutoClaimP) Cmd(a XAutoClaimArgs) {
	b.p.cmd(b.p.builder().XAutoClaimCompleted(a), &xAutoClaimCmd{})
}

var CommandXAutoClaimJustID commandXAutoClaimJustID

type commandXAutoClaimJustID string
type commandXAutoClaimJustIDP struct{ p Pipeliner }

func (commandXAutoClaimJustID) String() string                   { return "XAUTOCLAIM JUSTID" }
func (commandXAutoClaimJustID) Class() string                    { return "Stream" }
func (commandXAutoClaimJustID) RequireVersion() string           { return "6.2.0" }
func (commandXAutoClaimJustID) Forbid() bool                     { return false }
func (commandXAutoClaimJustID) WarningOnce() bool                { return false }
func (commandXAutoClaimJustID) WarnVersion() string              { return "" }
func (commandXAutoClaimJustID) Warning() string                  { return "" }
func (commandXAutoClaimJustID) Instead() string                  { return "" }
func (commandXAutoClaimJustID) ETC() string                      { return "" }
func (commandXAutoClaimJustID) PR(b BaseCmd) XAutoClaimJustIDCmd { return b.(XAutoClaimJustIDCmd) }
func (commandXAutoClaimJustID) P(p Pipeliner) commandXAutoClaimJustIDP {
	return commandXAutoClaimJustIDP{p}
}
func (b commandXAutoClaimJustIDP) Cmd(a XAutoClaimArgs) {
	b.p.cmd(b.p.builder().XAutoClaimJustIDCompleted(a), &xAutoClaimJustIDCmd{})
}

var CommandXClaim commandXClaim

type commandXClaim string
type commandXClaimP struct{ p Pipeliner }

func (commandXClaim) String() string                { return "XCLAIM" }
func (commandXClaim) Class() string                 { return "Stream" }
func (commandXClaim) RequireVersion() string        { return "5.0.0" }
func (commandXClaim) Forbid() bool                  { return false }
func (commandXClaim) WarningOnce() bool             { return false }
func (commandXClaim) WarnVersion() string           { return "" }
func (commandXClaim) Warning() string               { return "" }
func (commandXClaim) Instead() string               { return "" }
func (commandXClaim) ETC() string                   { return "" }
func (commandXClaim) PR(b BaseCmd) XMessageSliceCmd { return b.(XMessageSliceCmd) }
func (commandXClaim) P(p Pipeliner) commandXClaimP  { return commandXClaimP{p} }
func (b commandXClaimP) Cmd(a XClaimArgs) {
	b.p.cmd(b.p.builder().XClaimCompleted(a), &xMessageSliceCmd{})
}

var CommandXClaimJustID commandXClaimJustID

type commandXClaimJustID string
type commandXClaimJustIDP struct{ p Pipeliner }

func (commandXClaimJustID) String() string                     { return "XCLAIM JUSTID" }
func (commandXClaimJustID) Class() string                      { return "Stream" }
func (commandXClaimJustID) RequireVersion() string             { return "5.0.0" }
func (commandXClaimJustID) Forbid() bool                       { return false }
func (commandXClaimJustID) WarningOnce() bool                  { return false }
func (commandXClaimJustID) WarnVersion() string                { return "" }
func (commandXClaimJustID) Warning() string                    { return "" }
func (commandXClaimJustID) Instead() string                    { return "" }
func (commandXClaimJustID) ETC() string                        { return "" }
func (commandXClaimJustID) PR(b BaseCmd) StringSliceCmd        { return b.(StringSliceCmd) }
func (commandXClaimJustID) P(p Pipeliner) commandXClaimJustIDP { return commandXClaimJustIDP{p} }
func (b commandXClaimJustIDP) Cmd(a XClaimArgs) {
	b.p.cmd(b.p.builder().XClaimJustIDCompleted(a), &stringSliceCmd{})
}

var CommandXDel commandXDel

type commandXDel string
type commandXDelP struct{ p Pipeliner }

func (commandXDel) String() string             { return "XDEL" }
func (commandXDel) Class() string              { return "Stream" }
func (commandXDel) RequireVersion() string     { return "5.0.0" }
func (commandXDel) Forbid() bool               { return false }
func (commandXDel) WarningOnce() bool          { return false }
func (commandXDel) WarnVersion() string        { return "" }
func (commandXDel) Warning() string            { return "" }
func (commandXDel) Instead() string            { return "" }
func (commandXDel) ETC() string                { return "" }
func (commandXDel) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandXDel) P(p Pipeliner) commandXDelP { return commandXDelP{p} }
func (b commandXDelP) Cmd(stream string, ids ...string) {
	b.p.cmd(b.p.builder().XDelCompleted(stream, ids...), &intCmd{})
}

var CommandXGroupCreate commandXGroupCreate

type commandXGroupCreate string
type commandXGroupCreateP struct{ p Pipeliner }

func (commandXGroupCreate) String() string                     { return "XGROUP CREATE" }
func (commandXGroupCreate) Class() string                      { return "Stream" }
func (commandXGroupCreate) RequireVersion() string             { return "5.0.0" }
func (commandXGroupCreate) Forbid() bool                       { return false }
func (commandXGroupCreate) WarningOnce() bool                  { return false }
func (commandXGroupCreate) WarnVersion() string                { return "" }
func (commandXGroupCreate) Warning() string                    { return "" }
func (commandXGroupCreate) Instead() string                    { return "" }
func (commandXGroupCreate) ETC() string                        { return "" }
func (commandXGroupCreate) PR(b BaseCmd) StatusCmd             { return b.(StatusCmd) }
func (commandXGroupCreate) P(p Pipeliner) commandXGroupCreateP { return commandXGroupCreateP{p} }
func (b commandXGroupCreateP) Cmd(stream string, group string, start string) {
	b.p.cmd(b.p.builder().XGroupCreateCompleted(stream, group, start), &statusCmd{})
}

var CommandXGroupCreateConsumer commandXGroupCreateConsumer

type commandXGroupCreateConsumer string
type commandXGroupCreateConsumerP struct{ p Pipeliner }

func (commandXGroupCreateConsumer) String() string         { return "XGROUP CREATECONSUMER" }
func (commandXGroupCreateConsumer) Class() string          { return "Stream" }
func (commandXGroupCreateConsumer) RequireVersion() string { return "6.2.0" }
func (commandXGroupCreateConsumer) Forbid() bool           { return false }
func (commandXGroupCreateConsumer) WarningOnce() bool      { return false }
func (commandXGroupCreateConsumer) WarnVersion() string    { return "" }
func (commandXGroupCreateConsumer) Warning() string        { return "" }
func (commandXGroupCreateConsumer) Instead() string        { return "" }
func (commandXGroupCreateConsumer) ETC() string            { return "" }
func (commandXGroupCreateConsumer) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandXGroupCreateConsumer) P(p Pipeliner) commandXGroupCreateConsumerP {
	return commandXGroupCreateConsumerP{p}
}
func (b commandXGroupCreateConsumerP) Cmd(stream string, group string, consumer string) {
	b.p.cmd(b.p.builder().XGroupCreateConsumerCompleted(stream, group, consumer), &intCmd{})
}

var CommandXGroupCreateMkStream commandXGroupCreateMkStream

type commandXGroupCreateMkStream string
type commandXGroupCreateMkStreamP struct{ p Pipeliner }

func (commandXGroupCreateMkStream) String() string         { return "XGROUP CREATE MKSTREAM" }
func (commandXGroupCreateMkStream) Class() string          { return "Stream" }
func (commandXGroupCreateMkStream) RequireVersion() string { return "5.0.0" }
func (commandXGroupCreateMkStream) Forbid() bool           { return false }
func (commandXGroupCreateMkStream) WarningOnce() bool      { return false }
func (commandXGroupCreateMkStream) WarnVersion() string    { return "" }
func (commandXGroupCreateMkStream) Warning() string        { return "" }
func (commandXGroupCreateMkStream) Instead() string        { return "" }
func (commandXGroupCreateMkStream) ETC() string            { return "" }
func (commandXGroupCreateMkStream) PR(b BaseCmd) StatusCmd { return b.(StatusCmd) }
func (commandXGroupCreateMkStream) P(p Pipeliner) commandXGroupCreateMkStreamP {
	return commandXGroupCreateMkStreamP{p}
}
func (b commandXGroupCreateMkStreamP) Cmd(stream string, group string, start string) {
	b.p.cmd(b.p.builder().XGroupCreateMkStreamCompleted(stream, group, start), &statusCmd{})
}

var CommandXGroupDelConsumer commandXGroupDelConsumer

type commandXGroupDelConsumer string
type commandXGroupDelConsumerP struct{ p Pipeliner }

func (commandXGroupDelConsumer) String() string         { return "XGROUP DELCONSUMER" }
func (commandXGroupDelConsumer) Class() string          { return "Stream" }
func (commandXGroupDelConsumer) RequireVersion() string { return "5.0.0" }
func (commandXGroupDelConsumer) Forbid() bool           { return false }
func (commandXGroupDelConsumer) WarningOnce() bool      { return false }
func (commandXGroupDelConsumer) WarnVersion() string    { return "" }
func (commandXGroupDelConsumer) Warning() string        { return "" }
func (commandXGroupDelConsumer) Instead() string        { return "" }
func (commandXGroupDelConsumer) ETC() string            { return "" }
func (commandXGroupDelConsumer) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandXGroupDelConsumer) P(p Pipeliner) commandXGroupDelConsumerP {
	return commandXGroupDelConsumerP{p}
}
func (b commandXGroupDelConsumerP) Cmd(stream string, group string, consumer string) {
	b.p.cmd(b.p.builder().XGroupDelConsumerCompleted(stream, group, consumer), &intCmd{})
}

var CommandXGroupDestroy commandXGroupDestroy

type commandXGroupDestroy string
type commandXGroupDestroyP struct{ p Pipeliner }

func (commandXGroupDestroy) String() string                      { return "XGROUP DESTROY" }
func (commandXGroupDestroy) Class() string                       { return "Stream" }
func (commandXGroupDestroy) RequireVersion() string              { return "5.0.0" }
func (commandXGroupDestroy) Forbid() bool                        { return false }
func (commandXGroupDestroy) WarningOnce() bool                   { return false }
func (commandXGroupDestroy) WarnVersion() string                 { return "" }
func (commandXGroupDestroy) Warning() string                     { return "" }
func (commandXGroupDestroy) Instead() string                     { return "" }
func (commandXGroupDestroy) ETC() string                         { return "" }
func (commandXGroupDestroy) PR(b BaseCmd) IntCmd                 { return b.(IntCmd) }
func (commandXGroupDestroy) P(p Pipeliner) commandXGroupDestroyP { return commandXGroupDestroyP{p} }
func (b commandXGroupDestroyP) Cmd(stream string, group string) {
	b.p.cmd(b.p.builder().XGroupDestroyCompleted(stream, group), &intCmd{})
}

var CommandXGroupSetID commandXGroupSetID

type commandXGroupSetID string
type commandXGroupSetIDP struct{ p Pipeliner }

func (commandXGroupSetID) String() string                    { return "XGROUP SETID" }
func (commandXGroupSetID) Class() string                     { return "Stream" }
func (commandXGroupSetID) RequireVersion() string            { return "5.0.0" }
func (commandXGroupSetID) Forbid() bool                      { return false }
func (commandXGroupSetID) WarningOnce() bool                 { return false }
func (commandXGroupSetID) WarnVersion() string               { return "" }
func (commandXGroupSetID) Warning() string                   { return "" }
func (commandXGroupSetID) Instead() string                   { return "" }
func (commandXGroupSetID) ETC() string                       { return "" }
func (commandXGroupSetID) PR(b BaseCmd) StatusCmd            { return b.(StatusCmd) }
func (commandXGroupSetID) P(p Pipeliner) commandXGroupSetIDP { return commandXGroupSetIDP{p} }
func (b commandXGroupSetIDP) Cmd(stream string, group string, start string) {
	b.p.cmd(b.p.builder().XGroupSetIDCompleted(stream, group, start), &statusCmd{})
}

var CommandXInfoConsumers commandXInfoConsumers

type commandXInfoConsumers string
type commandXInfoConsumersP struct{ p Pipeliner }

func (commandXInfoConsumers) String() string                       { return "XINFO CONSUMERS" }
func (commandXInfoConsumers) Class() string                        { return "Stream" }
func (commandXInfoConsumers) RequireVersion() string               { return "5.0.0" }
func (commandXInfoConsumers) Forbid() bool                         { return false }
func (commandXInfoConsumers) WarningOnce() bool                    { return false }
func (commandXInfoConsumers) WarnVersion() string                  { return "" }
func (commandXInfoConsumers) Warning() string                      { return "" }
func (commandXInfoConsumers) Instead() string                      { return "" }
func (commandXInfoConsumers) ETC() string                          { return "" }
func (commandXInfoConsumers) PR(b BaseCmd) XInfoConsumersCmd       { return b.(XInfoConsumersCmd) }
func (commandXInfoConsumers) P(p Pipeliner) commandXInfoConsumersP { return commandXInfoConsumersP{p} }
func (b commandXInfoConsumersP) Cmd(key string, group string) {
	b.p.cmd(b.p.builder().XInfoConsumersCompleted(key, group), &xInfoConsumersCmd{})
}

var CommandXInfoGroups commandXInfoGroups

type commandXInfoGroups string
type commandXInfoGroupsP struct{ p Pipeliner }

func (commandXInfoGroups) String() string                    { return "XINFO GROUPS" }
func (commandXInfoGroups) Class() string                     { return "Stream" }
func (commandXInfoGroups) RequireVersion() string            { return "5.0.0" }
func (commandXInfoGroups) Forbid() bool                      { return false }
func (commandXInfoGroups) WarningOnce() bool                 { return false }
func (commandXInfoGroups) WarnVersion() string               { return "" }
func (commandXInfoGroups) Warning() string                   { return "" }
func (commandXInfoGroups) Instead() string                   { return "" }
func (commandXInfoGroups) ETC() string                       { return "" }
func (commandXInfoGroups) PR(b BaseCmd) XInfoGroupsCmd       { return b.(XInfoGroupsCmd) }
func (commandXInfoGroups) P(p Pipeliner) commandXInfoGroupsP { return commandXInfoGroupsP{p} }
func (b commandXInfoGroupsP) Cmd(key string) {
	b.p.cmd(b.p.builder().XInfoGroupsCompleted(key), &xInfoGroupsCmd{})
}

var CommandXInfoStream commandXInfoStream

type commandXInfoStream string
type commandXInfoStreamP struct{ p Pipeliner }

func (commandXInfoStream) String() string                    { return "XINFO STREAM" }
func (commandXInfoStream) Class() string                     { return "Stream" }
func (commandXInfoStream) RequireVersion() string            { return "5.0.0" }
func (commandXInfoStream) Forbid() bool                      { return false }
func (commandXInfoStream) WarningOnce() bool                 { return false }
func (commandXInfoStream) WarnVersion() string               { return "" }
func (commandXInfoStream) Warning() string                   { return "" }
func (commandXInfoStream) Instead() string                   { return "" }
func (commandXInfoStream) ETC() string                       { return "" }
func (commandXInfoStream) PR(b BaseCmd) XInfoStreamCmd       { return b.(XInfoStreamCmd) }
func (commandXInfoStream) P(p Pipeliner) commandXInfoStreamP { return commandXInfoStreamP{p} }
func (b commandXInfoStreamP) Cmd(key string) {
	b.p.cmd(b.p.builder().XInfoStreamCompleted(key), &xInfoStreamCmd{})
}

var CommandXInfoStreamFull commandXInfoStreamFull

type commandXInfoStreamFull string
type commandXInfoStreamFullP struct{ p Pipeliner }

func (commandXInfoStreamFull) String() string              { return "XINFO STREAM FULL" }
func (commandXInfoStreamFull) Class() string               { return "Stream" }
func (commandXInfoStreamFull) RequireVersion() string      { return "6.0.0" }
func (commandXInfoStreamFull) Forbid() bool                { return false }
func (commandXInfoStreamFull) WarningOnce() bool           { return false }
func (commandXInfoStreamFull) WarnVersion() string         { return "" }
func (commandXInfoStreamFull) Warning() string             { return "" }
func (commandXInfoStreamFull) Instead() string             { return "" }
func (commandXInfoStreamFull) ETC() string                 { return "" }
func (commandXInfoStreamFull) PR(b BaseCmd) XInfoStreamCmd { return b.(XInfoStreamCmd) }
func (commandXInfoStreamFull) P(p Pipeliner) commandXInfoStreamFullP {
	return commandXInfoStreamFullP{p}
}
func (b commandXInfoStreamFullP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().XInfoStreamFullCompleted(key, count), &xInfoStreamCmd{})
}

var CommandXLen commandXLen

type commandXLen string
type commandXLenP struct{ p Pipeliner }

func (commandXLen) String() string             { return "XLEN" }
func (commandXLen) Class() string              { return "Stream" }
func (commandXLen) RequireVersion() string     { return "5.0.0" }
func (commandXLen) Forbid() bool               { return false }
func (commandXLen) WarningOnce() bool          { return false }
func (commandXLen) WarnVersion() string        { return "" }
func (commandXLen) Warning() string            { return "" }
func (commandXLen) Instead() string            { return "" }
func (commandXLen) ETC() string                { return "" }
func (commandXLen) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandXLen) P(p Pipeliner) commandXLenP { return commandXLenP{p} }
func (b commandXLenP) Cmd(stream string) {
	b.p.cmd(b.p.builder().XLenCompleted(stream), &intCmd{})
}

var CommandXPending commandXPending

type commandXPending string
type commandXPendingP struct{ p Pipeliner }

func (commandXPending) String() string                 { return "XPENDING" }
func (commandXPending) Class() string                  { return "Stream" }
func (commandXPending) RequireVersion() string         { return "5.0.0" }
func (commandXPending) Forbid() bool                   { return false }
func (commandXPending) WarningOnce() bool              { return false }
func (commandXPending) WarnVersion() string            { return "" }
func (commandXPending) Warning() string                { return "" }
func (commandXPending) Instead() string                { return "" }
func (commandXPending) ETC() string                    { return "" }
func (commandXPending) PR(b BaseCmd) XPendingCmd       { return b.(XPendingCmd) }
func (commandXPending) P(p Pipeliner) commandXPendingP { return commandXPendingP{p} }
func (b commandXPendingP) Cmd(stream string, group string) {
	b.p.cmd(b.p.builder().XPendingCompleted(stream, group), &xPendingCmd{})
}

var CommandXPendingExt commandXPendingExt

type commandXPendingExt string
type commandXPendingExtP struct{ p Pipeliner }

func (commandXPendingExt) String() string                    { return "XPENDING" }
func (commandXPendingExt) Class() string                     { return "Stream" }
func (commandXPendingExt) RequireVersion() string            { return "6.2.0" }
func (commandXPendingExt) Forbid() bool                      { return false }
func (commandXPendingExt) WarningOnce() bool                 { return false }
func (commandXPendingExt) WarnVersion() string               { return "" }
func (commandXPendingExt) Warning() string                   { return "" }
func (commandXPendingExt) Instead() string                   { return "" }
func (commandXPendingExt) ETC() string                       { return "" }
func (commandXPendingExt) PR(b BaseCmd) XPendingExtCmd       { return b.(XPendingExtCmd) }
func (commandXPendingExt) P(p Pipeliner) commandXPendingExtP { return commandXPendingExtP{p} }
func (b commandXPendingExtP) Cmd(a XPendingExtArgs) {
	b.p.cmd(b.p.builder().XPendingExtCompleted(a), &xPendingExtCmd{})
}

var CommandXRange commandXRange

type commandXRange string
type commandXRangeP struct{ p Pipeliner }

func (commandXRange) String() string                { return "XRANGE" }
func (commandXRange) Class() string                 { return "Stream" }
func (commandXRange) RequireVersion() string        { return "5.0.0" }
func (commandXRange) Forbid() bool                  { return false }
func (commandXRange) WarningOnce() bool             { return false }
func (commandXRange) WarnVersion() string           { return "" }
func (commandXRange) Warning() string               { return "" }
func (commandXRange) Instead() string               { return "" }
func (commandXRange) ETC() string                   { return "" }
func (commandXRange) PR(b BaseCmd) XMessageSliceCmd { return b.(XMessageSliceCmd) }
func (commandXRange) P(p Pipeliner) commandXRangeP  { return commandXRangeP{p} }
func (b commandXRangeP) Cmd(stream string, start string, stop string) {
	b.p.cmd(b.p.builder().XRangeCompleted(stream, start, stop), &xMessageSliceCmd{})
}

var CommandXRangeN commandXRangeN

type commandXRangeN string
type commandXRangeNP struct{ p Pipeliner }

func (commandXRangeN) String() string                { return "XRANGE COUNT" }
func (commandXRangeN) Class() string                 { return "Stream" }
func (commandXRangeN) RequireVersion() string        { return "6.2.0" }
func (commandXRangeN) Forbid() bool                  { return false }
func (commandXRangeN) WarningOnce() bool             { return false }
func (commandXRangeN) WarnVersion() string           { return "" }
func (commandXRangeN) Warning() string               { return "" }
func (commandXRangeN) Instead() string               { return "" }
func (commandXRangeN) ETC() string                   { return "" }
func (commandXRangeN) PR(b BaseCmd) XMessageSliceCmd { return b.(XMessageSliceCmd) }
func (commandXRangeN) P(p Pipeliner) commandXRangeNP { return commandXRangeNP{p} }
func (b commandXRangeNP) Cmd(stream string, start string, stop string, count int64) {
	b.p.cmd(b.p.builder().XRangeNCompleted(stream, start, stop, count), &xMessageSliceCmd{})
}

var CommandXRead commandXRead

type commandXRead string

func (commandXRead) String() string         { return "XREAD STREAMS" }
func (commandXRead) Class() string          { return "Stream" }
func (commandXRead) RequireVersion() string { return "5.0.0" }
func (commandXRead) Forbid() bool           { return false }
func (commandXRead) WarningOnce() bool      { return false }
func (commandXRead) WarnVersion() string    { return "" }
func (commandXRead) Warning() string        { return "" }
func (commandXRead) Instead() string        { return "" }
func (commandXRead) ETC() string            { return "" }

var CommandXReadGroup commandXReadGroup

type commandXReadGroup string

func (commandXReadGroup) String() string         { return "XREADGROUP GROUP" }
func (commandXReadGroup) Class() string          { return "Stream" }
func (commandXReadGroup) RequireVersion() string { return "5.0.0" }
func (commandXReadGroup) Forbid() bool           { return false }
func (commandXReadGroup) WarningOnce() bool      { return false }
func (commandXReadGroup) WarnVersion() string    { return "" }
func (commandXReadGroup) Warning() string        { return "" }
func (commandXReadGroup) Instead() string        { return "" }
func (commandXReadGroup) ETC() string            { return "" }

var CommandXRevRange commandXRevRange

type commandXRevRange string
type commandXRevRangeP struct{ p Pipeliner }

func (commandXRevRange) String() string                  { return "XREVRANGE" }
func (commandXRevRange) Class() string                   { return "Stream" }
func (commandXRevRange) RequireVersion() string          { return "5.0.0" }
func (commandXRevRange) Forbid() bool                    { return false }
func (commandXRevRange) WarningOnce() bool               { return false }
func (commandXRevRange) WarnVersion() string             { return "" }
func (commandXRevRange) Warning() string                 { return "" }
func (commandXRevRange) Instead() string                 { return "" }
func (commandXRevRange) ETC() string                     { return "" }
func (commandXRevRange) PR(b BaseCmd) XMessageSliceCmd   { return b.(XMessageSliceCmd) }
func (commandXRevRange) P(p Pipeliner) commandXRevRangeP { return commandXRevRangeP{p} }
func (b commandXRevRangeP) Cmd(stream string, stop string, start string) {
	b.p.cmd(b.p.builder().XRevRangeCompleted(stream, start, stop), &xMessageSliceCmd{})
}

var CommandXRevRangeN commandXRevRangeN

type commandXRevRangeN string
type commandXRevRangeNP struct{ p Pipeliner }

func (commandXRevRangeN) String() string                   { return "XREVRANGE COUNT" }
func (commandXRevRangeN) Class() string                    { return "Stream" }
func (commandXRevRangeN) RequireVersion() string           { return "6.2.0" }
func (commandXRevRangeN) Forbid() bool                     { return false }
func (commandXRevRangeN) WarningOnce() bool                { return false }
func (commandXRevRangeN) WarnVersion() string              { return "" }
func (commandXRevRangeN) Warning() string                  { return "" }
func (commandXRevRangeN) Instead() string                  { return "" }
func (commandXRevRangeN) ETC() string                      { return "" }
func (commandXRevRangeN) PR(b BaseCmd) XMessageSliceCmd    { return b.(XMessageSliceCmd) }
func (commandXRevRangeN) P(p Pipeliner) commandXRevRangeNP { return commandXRevRangeNP{p} }
func (b commandXRevRangeNP) Cmd(stream string, stop string, start string, count int64) {
	b.p.cmd(b.p.builder().XRevRangeNCompleted(stream, start, stop, count), &xMessageSliceCmd{})
}

var CommandXTrim commandXTrim

type commandXTrim string
type commandXTrimP struct{ p Pipeliner }

func (commandXTrim) String() string              { return "XTRIM" }
func (commandXTrim) Class() string               { return "Stream" }
func (commandXTrim) RequireVersion() string      { return "5.0.0" }
func (commandXTrim) Forbid() bool                { return false }
func (commandXTrim) WarningOnce() bool           { return false }
func (commandXTrim) WarnVersion() string         { return "" }
func (commandXTrim) Warning() string             { return "" }
func (commandXTrim) Instead() string             { return "" }
func (commandXTrim) ETC() string                 { return "" }
func (commandXTrim) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandXTrim) P(p Pipeliner) commandXTrimP { return commandXTrimP{p} }
func (b commandXTrimP) Cmd(key string, maxLen int64) {
	b.p.cmd(b.p.builder().XTrimCompleted(key, maxLen), &intCmd{})
}

var CommandXTrimMaxLenApprox commandXTrimMaxLenApprox

type commandXTrimMaxLenApprox string
type commandXTrimMaxLenApproxP struct{ p Pipeliner }

func (commandXTrimMaxLenApprox) String() string         { return "XTRIM LIMIT" }
func (commandXTrimMaxLenApprox) Class() string          { return "Stream" }
func (commandXTrimMaxLenApprox) RequireVersion() string { return "6.2.0" }
func (commandXTrimMaxLenApprox) Forbid() bool           { return false }
func (commandXTrimMaxLenApprox) WarningOnce() bool      { return false }
func (commandXTrimMaxLenApprox) WarnVersion() string    { return "" }
func (commandXTrimMaxLenApprox) Warning() string        { return "" }
func (commandXTrimMaxLenApprox) Instead() string        { return "" }
func (commandXTrimMaxLenApprox) ETC() string            { return "" }
func (commandXTrimMaxLenApprox) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandXTrimMaxLenApprox) P(p Pipeliner) commandXTrimMaxLenApproxP {
	return commandXTrimMaxLenApproxP{p}
}
func (b commandXTrimMaxLenApproxP) Cmd(key string, maxLen int64, limit int64) {
	b.p.cmd(b.p.builder().XTrimMaxLenApproxCompleted(key, maxLen, limit), &intCmd{})
}

var CommandXTrimMinID commandXTrimMinID

type commandXTrimMinID string
type commandXTrimMinIDP struct{ p Pipeliner }

func (commandXTrimMinID) String() string                   { return "XTRIM MINID" }
func (commandXTrimMinID) Class() string                    { return "Stream" }
func (commandXTrimMinID) RequireVersion() string           { return "6.2.0" }
func (commandXTrimMinID) Forbid() bool                     { return false }
func (commandXTrimMinID) WarningOnce() bool                { return false }
func (commandXTrimMinID) WarnVersion() string              { return "" }
func (commandXTrimMinID) Warning() string                  { return "" }
func (commandXTrimMinID) Instead() string                  { return "" }
func (commandXTrimMinID) ETC() string                      { return "" }
func (commandXTrimMinID) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandXTrimMinID) P(p Pipeliner) commandXTrimMinIDP { return commandXTrimMinIDP{p} }
func (b commandXTrimMinIDP) Cmd(key string, minID string) {
	b.p.cmd(b.p.builder().XTrimMinIDCompleted(key, minID), &intCmd{})
}

var CommandXTrimMinIDApprox commandXTrimMinIDApprox

type commandXTrimMinIDApprox string
type commandXTrimMinIDApproxP struct{ p Pipeliner }

func (commandXTrimMinIDApprox) String() string         { return "XTRIM MINID LIMIT" }
func (commandXTrimMinIDApprox) Class() string          { return "Stream" }
func (commandXTrimMinIDApprox) RequireVersion() string { return "6.2.0" }
func (commandXTrimMinIDApprox) Forbid() bool           { return false }
func (commandXTrimMinIDApprox) WarningOnce() bool      { return false }
func (commandXTrimMinIDApprox) WarnVersion() string    { return "" }
func (commandXTrimMinIDApprox) Warning() string        { return "" }
func (commandXTrimMinIDApprox) Instead() string        { return "" }
func (commandXTrimMinIDApprox) ETC() string            { return "" }
func (commandXTrimMinIDApprox) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandXTrimMinIDApprox) P(p Pipeliner) commandXTrimMinIDApproxP {
	return commandXTrimMinIDApproxP{p}
}
func (b commandXTrimMinIDApproxP) Cmd(key string, minID string, limit int64) {
	b.p.cmd(b.p.builder().XTrimMinIDApproxCompleted(key, minID, limit), &intCmd{})
}
