// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandSAdd commandSAdd

type commandSAdd string
type commandSAddP struct{ p Pipeliner }

func (commandSAdd) String() string             { return "SADD" }
func (commandSAdd) Class() string              { return "Set" }
func (commandSAdd) RequireVersion() string     { return "1.0.0" }
func (commandSAdd) Forbid() bool               { return false }
func (commandSAdd) WarningOnce() bool          { return false }
func (commandSAdd) WarnVersion() string        { return "" }
func (commandSAdd) Warning() string            { return "" }
func (commandSAdd) Instead() string            { return "" }
func (commandSAdd) ETC() string                { return "" }
func (commandSAdd) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandSAdd) P(p Pipeliner) commandSAddP { return commandSAddP{p} }
func (b commandSAddP) Cmd(key string, member any) {
	b.p.cmd(b.p.builder().SAddCompleted(key, member), &intCmd{})
}

var CommandSCard commandSCard

type commandSCard string
type commandSCardP struct{ p Pipeliner }

func (commandSCard) String() string              { return "SCARD" }
func (commandSCard) Class() string               { return "Set" }
func (commandSCard) RequireVersion() string      { return "1.0.0" }
func (commandSCard) Forbid() bool                { return false }
func (commandSCard) WarningOnce() bool           { return false }
func (commandSCard) WarnVersion() string         { return "" }
func (commandSCard) Warning() string             { return "" }
func (commandSCard) Instead() string             { return "" }
func (commandSCard) ETC() string                 { return "" }
func (commandSCard) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandSCard) P(p Pipeliner) commandSCardP { return commandSCardP{p} }
func (b commandSCardP) Cmd(key string) {
	b.p.cmd(b.p.builder().SCardCompleted(key), &intCmd{})
}

var CommandSDiff commandSDiff

type commandSDiff string
type commandSDiffP struct{ p Pipeliner }

func (commandSDiff) String() string              { return "SDIFF" }
func (commandSDiff) Class() string               { return "Set" }
func (commandSDiff) RequireVersion() string      { return "1.0.0" }
func (commandSDiff) Forbid() bool                { return false }
func (commandSDiff) WarningOnce() bool           { return false }
func (commandSDiff) WarnVersion() string         { return "" }
func (commandSDiff) Warning() string             { return "" }
func (commandSDiff) Instead() string             { return "" }
func (commandSDiff) ETC() string                 { return "" }
func (commandSDiff) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandSDiff) P(p Pipeliner) commandSDiffP { return commandSDiffP{p} }
func (b commandSDiffP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().SDiffCompleted(keys...), &stringSliceCmd{})
}

var CommandSDiffStore commandSDiffStore

type commandSDiffStore string
type commandSDiffStoreP struct{ p Pipeliner }

func (commandSDiffStore) String() string                   { return "SDIFFSTORE" }
func (commandSDiffStore) Class() string                    { return "Set" }
func (commandSDiffStore) RequireVersion() string           { return "1.0.0" }
func (commandSDiffStore) Forbid() bool                     { return false }
func (commandSDiffStore) WarningOnce() bool                { return false }
func (commandSDiffStore) WarnVersion() string              { return "" }
func (commandSDiffStore) Warning() string                  { return "" }
func (commandSDiffStore) Instead() string                  { return "" }
func (commandSDiffStore) ETC() string                      { return "" }
func (commandSDiffStore) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandSDiffStore) P(p Pipeliner) commandSDiffStoreP { return commandSDiffStoreP{p} }
func (b commandSDiffStoreP) Cmd(destination string, keys ...string) {
	b.p.cmd(b.p.builder().SDiffStoreCompleted(destination, keys...), &intCmd{})
}

var CommandSInter commandSInter

type commandSInter string
type commandSInterP struct{ p Pipeliner }

func (commandSInter) String() string               { return "SINTER" }
func (commandSInter) Class() string                { return "Set" }
func (commandSInter) RequireVersion() string       { return "1.0.0" }
func (commandSInter) Forbid() bool                 { return false }
func (commandSInter) WarningOnce() bool            { return false }
func (commandSInter) WarnVersion() string          { return "" }
func (commandSInter) Warning() string              { return "" }
func (commandSInter) Instead() string              { return "" }
func (commandSInter) ETC() string                  { return "" }
func (commandSInter) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandSInter) P(p Pipeliner) commandSInterP { return commandSInterP{p} }
func (b commandSInterP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().SInterCompleted(keys...), &stringSliceCmd{})
}

var CommandSInterCard commandSInterCard

type commandSInterCard string
type commandSInterCardP struct{ p Pipeliner }

func (commandSInterCard) String() string                   { return "SINTERCARD" }
func (commandSInterCard) Class() string                    { return "Set" }
func (commandSInterCard) RequireVersion() string           { return "7.0.0" }
func (commandSInterCard) Forbid() bool                     { return false }
func (commandSInterCard) WarningOnce() bool                { return false }
func (commandSInterCard) WarnVersion() string              { return "" }
func (commandSInterCard) Warning() string                  { return "" }
func (commandSInterCard) Instead() string                  { return "" }
func (commandSInterCard) ETC() string                      { return "" }
func (commandSInterCard) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandSInterCard) P(p Pipeliner) commandSInterCardP { return commandSInterCardP{p} }
func (b commandSInterCardP) Cmd(limit int64, keys ...string) {
	b.p.cmd(b.p.builder().SInterCardCompleted(limit, keys...), &intCmd{})
}

var CommandSInterStore commandSInterStore

type commandSInterStore string
type commandSInterStoreP struct{ p Pipeliner }

func (commandSInterStore) String() string                    { return "SINTERSTORE" }
func (commandSInterStore) Class() string                     { return "Set" }
func (commandSInterStore) RequireVersion() string            { return "1.0.0" }
func (commandSInterStore) Forbid() bool                      { return false }
func (commandSInterStore) WarningOnce() bool                 { return false }
func (commandSInterStore) WarnVersion() string               { return "" }
func (commandSInterStore) Warning() string                   { return "" }
func (commandSInterStore) Instead() string                   { return "" }
func (commandSInterStore) ETC() string                       { return "" }
func (commandSInterStore) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandSInterStore) P(p Pipeliner) commandSInterStoreP { return commandSInterStoreP{p} }
func (b commandSInterStoreP) Cmd(destination string, keys ...string) {
	b.p.cmd(b.p.builder().SInterStoreCompleted(destination, keys...), &intCmd{})
}

var CommandSIsMember commandSIsMember

type commandSIsMember string
type commandSIsMemberP struct{ p Pipeliner }

func (commandSIsMember) String() string                  { return "SISMEMBER" }
func (commandSIsMember) Class() string                   { return "Set" }
func (commandSIsMember) RequireVersion() string          { return "1.0.0" }
func (commandSIsMember) Forbid() bool                    { return false }
func (commandSIsMember) WarningOnce() bool               { return false }
func (commandSIsMember) WarnVersion() string             { return "" }
func (commandSIsMember) Warning() string                 { return "" }
func (commandSIsMember) Instead() string                 { return "" }
func (commandSIsMember) ETC() string                     { return "" }
func (commandSIsMember) PR(b BaseCmd) BoolCmd            { return b.(BoolCmd) }
func (commandSIsMember) P(p Pipeliner) commandSIsMemberP { return commandSIsMemberP{p} }
func (b commandSIsMemberP) Cmd(key string, member any) {
	b.p.cmd(b.p.builder().SIsMemberCompleted(key, member), &boolCmd{})
}

var CommandSMAdd commandSMAdd

type commandSMAdd string
type commandSMAddP struct{ p Pipeliner }

func (commandSMAdd) String() string              { return "SADD" }
func (commandSMAdd) Class() string               { return "Set" }
func (commandSMAdd) RequireVersion() string      { return "2.4.0" }
func (commandSMAdd) Forbid() bool                { return false }
func (commandSMAdd) WarningOnce() bool           { return false }
func (commandSMAdd) WarnVersion() string         { return "" }
func (commandSMAdd) Warning() string             { return "" }
func (commandSMAdd) Instead() string             { return "" }
func (commandSMAdd) ETC() string                 { return "" }
func (commandSMAdd) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandSMAdd) P(p Pipeliner) commandSMAddP { return commandSMAddP{p} }
func (b commandSMAddP) Cmd(key string, members ...any) {
	b.p.cmd(b.p.builder().SAddCompleted(key, members...), &intCmd{})
}

var CommandSMIsMember commandSMIsMember

type commandSMIsMember string
type commandSMIsMemberP struct{ p Pipeliner }

func (commandSMIsMember) String() string                   { return "SMISMEMBER" }
func (commandSMIsMember) Class() string                    { return "Set" }
func (commandSMIsMember) RequireVersion() string           { return "6.2.0" }
func (commandSMIsMember) Forbid() bool                     { return false }
func (commandSMIsMember) WarningOnce() bool                { return false }
func (commandSMIsMember) WarnVersion() string              { return "" }
func (commandSMIsMember) Warning() string                  { return "" }
func (commandSMIsMember) Instead() string                  { return "" }
func (commandSMIsMember) ETC() string                      { return "" }
func (commandSMIsMember) PR(b BaseCmd) BoolSliceCmd        { return b.(BoolSliceCmd) }
func (commandSMIsMember) P(p Pipeliner) commandSMIsMemberP { return commandSMIsMemberP{p} }
func (b commandSMIsMemberP) Cmd(key string, members ...any) {
	b.p.cmd(b.p.builder().SMIsMemberCompleted(key, members...), &boolSliceCmd{})
}

var CommandSMRem commandSMRem

type commandSMRem string
type commandSMRemP struct{ p Pipeliner }

func (commandSMRem) String() string              { return "SREM" }
func (commandSMRem) Class() string               { return "Set" }
func (commandSMRem) RequireVersion() string      { return "2.4.0" }
func (commandSMRem) Forbid() bool                { return false }
func (commandSMRem) WarningOnce() bool           { return false }
func (commandSMRem) WarnVersion() string         { return "" }
func (commandSMRem) Warning() string             { return "" }
func (commandSMRem) Instead() string             { return "" }
func (commandSMRem) ETC() string                 { return "" }
func (commandSMRem) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandSMRem) P(p Pipeliner) commandSMRemP { return commandSMRemP{p} }
func (b commandSMRemP) Cmd(key string, members ...any) {
	b.p.cmd(b.p.builder().SRemCompleted(key, members...), &intCmd{})
}

var CommandSMembers commandSMembers

type commandSMembers string
type commandSMembersP struct{ p Pipeliner }

func (commandSMembers) String() string                 { return "SMEMBERS" }
func (commandSMembers) Class() string                  { return "Set" }
func (commandSMembers) RequireVersion() string         { return "1.0.0" }
func (commandSMembers) Forbid() bool                   { return false }
func (commandSMembers) WarningOnce() bool              { return false }
func (commandSMembers) WarnVersion() string            { return "" }
func (commandSMembers) Warning() string                { return "" }
func (commandSMembers) Instead() string                { return "" }
func (commandSMembers) ETC() string                    { return "" }
func (commandSMembers) PR(b BaseCmd) StringSliceCmd    { return b.(StringSliceCmd) }
func (commandSMembers) P(p Pipeliner) commandSMembersP { return commandSMembersP{p} }
func (b commandSMembersP) Cmd(key string) {
	b.p.cmd(b.p.builder().SMembersCompleted(key), &stringSliceCmd{})
}

var CommandSMove commandSMove

type commandSMove string
type commandSMoveP struct{ p Pipeliner }

func (commandSMove) String() string              { return "SMOVE" }
func (commandSMove) Class() string               { return "Set" }
func (commandSMove) RequireVersion() string      { return "1.0.0" }
func (commandSMove) Forbid() bool                { return false }
func (commandSMove) WarningOnce() bool           { return false }
func (commandSMove) WarnVersion() string         { return "" }
func (commandSMove) Warning() string             { return "" }
func (commandSMove) Instead() string             { return "" }
func (commandSMove) ETC() string                 { return "" }
func (commandSMove) PR(b BaseCmd) BoolCmd        { return b.(BoolCmd) }
func (commandSMove) P(p Pipeliner) commandSMoveP { return commandSMoveP{p} }
func (b commandSMoveP) Cmd(source string, destination string, member any) {
	b.p.cmd(b.p.builder().SMoveCompleted(source, destination, member), &boolCmd{})
}

var CommandSPop commandSPop

type commandSPop string
type commandSPopP struct{ p Pipeliner }

func (commandSPop) String() string             { return "SPOP" }
func (commandSPop) Class() string              { return "Set" }
func (commandSPop) RequireVersion() string     { return "1.0.0" }
func (commandSPop) Forbid() bool               { return false }
func (commandSPop) WarningOnce() bool          { return false }
func (commandSPop) WarnVersion() string        { return "" }
func (commandSPop) Warning() string            { return "" }
func (commandSPop) Instead() string            { return "" }
func (commandSPop) ETC() string                { return "" }
func (commandSPop) PR(b BaseCmd) StringCmd     { return b.(StringCmd) }
func (commandSPop) P(p Pipeliner) commandSPopP { return commandSPopP{p} }
func (b commandSPopP) Cmd(key string) {
	b.p.cmd(b.p.builder().SPopCompleted(key), &stringCmd{})
}

var CommandSPopN commandSPopN

type commandSPopN string
type commandSPopNP struct{ p Pipeliner }

func (commandSPopN) String() string              { return "SPOP" }
func (commandSPopN) Class() string               { return "Set" }
func (commandSPopN) RequireVersion() string      { return "3.2.0" }
func (commandSPopN) Forbid() bool                { return false }
func (commandSPopN) WarningOnce() bool           { return false }
func (commandSPopN) WarnVersion() string         { return "" }
func (commandSPopN) Warning() string             { return "" }
func (commandSPopN) Instead() string             { return "" }
func (commandSPopN) ETC() string                 { return "" }
func (commandSPopN) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandSPopN) P(p Pipeliner) commandSPopNP { return commandSPopNP{p} }
func (b commandSPopNP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().SPopNCompleted(key, count), &stringSliceCmd{})
}

var CommandSRandMember commandSRandMember

type commandSRandMember string
type commandSRandMemberP struct{ p Pipeliner }

func (commandSRandMember) String() string                    { return "SRANDMEMBER" }
func (commandSRandMember) Class() string                     { return "Set" }
func (commandSRandMember) RequireVersion() string            { return "1.0.0" }
func (commandSRandMember) Forbid() bool                      { return false }
func (commandSRandMember) WarningOnce() bool                 { return false }
func (commandSRandMember) WarnVersion() string               { return "" }
func (commandSRandMember) Warning() string                   { return "" }
func (commandSRandMember) Instead() string                   { return "" }
func (commandSRandMember) ETC() string                       { return "" }
func (commandSRandMember) PR(b BaseCmd) StringCmd            { return b.(StringCmd) }
func (commandSRandMember) P(p Pipeliner) commandSRandMemberP { return commandSRandMemberP{p} }
func (b commandSRandMemberP) Cmd(key string) {
	b.p.cmd(b.p.builder().SRandMemberCompleted(key), &stringCmd{})
}

var CommandSRandMemberN commandSRandMemberN

type commandSRandMemberN string
type commandSRandMemberNP struct{ p Pipeliner }

func (commandSRandMemberN) String() string                     { return "SRANDMEMBER" }
func (commandSRandMemberN) Class() string                      { return "Set" }
func (commandSRandMemberN) RequireVersion() string             { return "2.6.0" }
func (commandSRandMemberN) Forbid() bool                       { return false }
func (commandSRandMemberN) WarningOnce() bool                  { return false }
func (commandSRandMemberN) WarnVersion() string                { return "" }
func (commandSRandMemberN) Warning() string                    { return "" }
func (commandSRandMemberN) Instead() string                    { return "" }
func (commandSRandMemberN) ETC() string                        { return "" }
func (commandSRandMemberN) PR(b BaseCmd) StringSliceCmd        { return b.(StringSliceCmd) }
func (commandSRandMemberN) P(p Pipeliner) commandSRandMemberNP { return commandSRandMemberNP{p} }
func (b commandSRandMemberNP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().SRandMemberNCompleted(key, count), &stringSliceCmd{})
}

var CommandSRem commandSRem

type commandSRem string
type commandSRemP struct{ p Pipeliner }

func (commandSRem) String() string             { return "SREM" }
func (commandSRem) Class() string              { return "Set" }
func (commandSRem) RequireVersion() string     { return "1.0.0" }
func (commandSRem) Forbid() bool               { return false }
func (commandSRem) WarningOnce() bool          { return false }
func (commandSRem) WarnVersion() string        { return "" }
func (commandSRem) Warning() string            { return "" }
func (commandSRem) Instead() string            { return "" }
func (commandSRem) ETC() string                { return "" }
func (commandSRem) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandSRem) P(p Pipeliner) commandSRemP { return commandSRemP{p} }
func (b commandSRemP) Cmd(key string, member any) {
	b.p.cmd(b.p.builder().SRemCompleted(key, member), &intCmd{})
}

var CommandSScan commandSScan

type commandSScan string
type commandSScanP struct{ p Pipeliner }

func (commandSScan) String() string              { return "SSCAN" }
func (commandSScan) Class() string               { return "Set" }
func (commandSScan) RequireVersion() string      { return "2.8.0" }
func (commandSScan) Forbid() bool                { return false }
func (commandSScan) WarningOnce() bool           { return false }
func (commandSScan) WarnVersion() string         { return "" }
func (commandSScan) Warning() string             { return "" }
func (commandSScan) Instead() string             { return "" }
func (commandSScan) ETC() string                 { return "" }
func (commandSScan) PR(b BaseCmd) ScanCmd        { return b.(ScanCmd) }
func (commandSScan) P(p Pipeliner) commandSScanP { return commandSScanP{p} }
func (b commandSScanP) Cmd(key string, cursor uint64, match string, count int64) {
	b.p.cmd(b.p.builder().SScanCompleted(key, cursor, match, count), &scanCmd{})
}

var CommandSUnion commandSUnion

type commandSUnion string
type commandSUnionP struct{ p Pipeliner }

func (commandSUnion) String() string               { return "SUNION" }
func (commandSUnion) Class() string                { return "Set" }
func (commandSUnion) RequireVersion() string       { return "1.0.0" }
func (commandSUnion) Forbid() bool                 { return false }
func (commandSUnion) WarningOnce() bool            { return false }
func (commandSUnion) WarnVersion() string          { return "" }
func (commandSUnion) Warning() string              { return "" }
func (commandSUnion) Instead() string              { return "" }
func (commandSUnion) ETC() string                  { return "" }
func (commandSUnion) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandSUnion) P(p Pipeliner) commandSUnionP { return commandSUnionP{p} }
func (b commandSUnionP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().SUnionCompleted(keys...), &stringSliceCmd{})
}

var CommandSUnionStore commandSUnionStore

type commandSUnionStore string
type commandSUnionStoreP struct{ p Pipeliner }

func (commandSUnionStore) String() string                    { return "SUNIONSTORE" }
func (commandSUnionStore) Class() string                     { return "Set" }
func (commandSUnionStore) RequireVersion() string            { return "1.0.0" }
func (commandSUnionStore) Forbid() bool                      { return false }
func (commandSUnionStore) WarningOnce() bool                 { return false }
func (commandSUnionStore) WarnVersion() string               { return "" }
func (commandSUnionStore) Warning() string                   { return "" }
func (commandSUnionStore) Instead() string                   { return "" }
func (commandSUnionStore) ETC() string                       { return "" }
func (commandSUnionStore) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandSUnionStore) P(p Pipeliner) commandSUnionStoreP { return commandSUnionStoreP{p} }
func (b commandSUnionStoreP) Cmd(destination string, keys ...string) {
	b.p.cmd(b.p.builder().SUnionStoreCompleted(destination, keys...), &intCmd{})
}
