// Code generated by cmd/genmeta. DO NOT EDIT.
package redisson

var CommandBZMPop commandBZMPop

type commandBZMPop string

func (commandBZMPop) String() string         { return "BZMPOP" }
func (commandBZMPop) Class() string          { return "SortedSet" }
func (commandBZMPop) RequireVersion() string { return "7.0.0" }
func (commandBZMPop) Forbid() bool           { return false }
func (commandBZMPop) WarningOnce() bool      { return false }
func (commandBZMPop) WarnVersion() string    { return "" }
func (commandBZMPop) Warning() string        { return "" }
func (commandBZMPop) Instead() string        { return "" }
func (commandBZMPop) ETC() string            { return "" }

var CommandBZPopMax commandBZPopMax

type commandBZPopMax string

func (commandBZPopMax) String() string         { return "BZPOPMAX" }
func (commandBZPopMax) Class() string          { return "SortedSet" }
func (commandBZPopMax) RequireVersion() string { return "5.0.0" }
func (commandBZPopMax) Forbid() bool           { return false }
func (commandBZPopMax) WarningOnce() bool      { return false }
func (commandBZPopMax) WarnVersion() string    { return "" }
func (commandBZPopMax) Warning() string        { return "" }
func (commandBZPopMax) Instead() string        { return "" }
func (commandBZPopMax) ETC() string            { return "" }

var CommandBZPopMin commandBZPopMin

type commandBZPopMin string

func (commandBZPopMin) String() string         { return "BZPOPMIN" }
func (commandBZPopMin) Class() string          { return "SortedSet" }
func (commandBZPopMin) RequireVersion() string { return "5.0.0" }
func (commandBZPopMin) Forbid() bool           { return false }
func (commandBZPopMin) WarningOnce() bool      { return false }
func (commandBZPopMin) WarnVersion() string    { return "" }
func (commandBZPopMin) Warning() string        { return "" }
func (commandBZPopMin) Instead() string        { return "" }
func (commandBZPopMin) ETC() string            { return "" }

var CommandZAdd commandZAdd

type commandZAdd string
type commandZAddP struct{ p Pipeliner }

func (commandZAdd) String() string             { return "ZADD" }
func (commandZAdd) Class() string              { return "SortedSet" }
func (commandZAdd) RequireVersion() string     { return "1.2.0" }
func (commandZAdd) Forbid() bool               { return false }
func (commandZAdd) WarningOnce() bool          { return false }
func (commandZAdd) WarnVersion() string        { return "" }
func (commandZAdd) Warning() string            { return "" }
func (commandZAdd) Instead() string            { return "" }
func (commandZAdd) ETC() string                { return "" }
func (commandZAdd) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandZAdd) P(p Pipeliner) commandZAddP { return commandZAddP{p} }
func (b commandZAddP) Cmd(key string, member Z) {
	b.p.cmd(b.p.builder().ZAddCompleted(key, member), &intCmd{})
}

var CommandZAddArgs commandZAddArgs

type commandZAddArgs string
type commandZAddArgsP struct{ p Pipeliner }

func (commandZAddArgs) String() string                 { return "ZADD" }
func (commandZAddArgs) Class() string                  { return "SortedSet" }
func (commandZAddArgs) RequireVersion() string         { return "6.2.0" }
func (commandZAddArgs) Forbid() bool                   { return false }
func (commandZAddArgs) WarningOnce() bool              { return false }
func (commandZAddArgs) WarnVersion() string            { return "" }
func (commandZAddArgs) Warning() string                { return "" }
func (commandZAddArgs) Instead() string                { return "" }
func (commandZAddArgs) ETC() string                    { return "" }
func (commandZAddArgs) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandZAddArgs) P(p Pipeliner) commandZAddArgsP { return commandZAddArgsP{p} }
func (b commandZAddArgsP) Cmd(key string, args ZAddArgs) {
	b.p.cmd(b.p.builder().ZAddArgsCompleted(key, args), &intCmd{})
}

var CommandZAddArgsIncr commandZAddArgsIncr

type commandZAddArgsIncr string
type commandZAddArgsIncrP struct{ p Pipeliner }

func (commandZAddArgsIncr) String() string                     { return "ZADD INCR" }
func (commandZAddArgsIncr) Class() string                      { return "SortedSet" }
func (commandZAddArgsIncr) RequireVersion() string             { return "3.0.2" }
func (commandZAddArgsIncr) Forbid() bool                       { return false }
func (commandZAddArgsIncr) WarningOnce() bool                  { return false }
func (commandZAddArgsIncr) WarnVersion() string                { return "" }
func (commandZAddArgsIncr) Warning() string                    { return "" }
func (commandZAddArgsIncr) Instead() string                    { return "" }
func (commandZAddArgsIncr) ETC() string                        { return "" }
func (commandZAddArgsIncr) PR(b BaseCmd) FloatCmd              { return b.(FloatCmd) }
func (commandZAddArgsIncr) P(p Pipeliner) commandZAddArgsIncrP { return commandZAddArgsIncrP{p} }
func (b commandZAddArgsIncrP) Cmd(key string, args ZAddArgs) {
	b.p.cmd(b.p.builder().ZAddArgsIncrCompleted(key, args), &floatCmd{})
}

var CommandZAddCh commandZAddCh

type commandZAddCh string
type commandZAddChP struct{ p Pipeliner }

func (commandZAddCh) String() string               { return "ZADD CH" }
func (commandZAddCh) Class() string                { return "SortedSet" }
func (commandZAddCh) RequireVersion() string       { return "3.0.2" }
func (commandZAddCh) Forbid() bool                 { return false }
func (commandZAddCh) WarningOnce() bool            { return false }
func (commandZAddCh) WarnVersion() string          { return "" }
func (commandZAddCh) Warning() string              { return "" }
func (commandZAddCh) Instead() string              { return "" }
func (commandZAddCh) ETC() string                  { return "" }
func (commandZAddCh) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZAddCh) P(p Pipeliner) commandZAddChP { return commandZAddChP{p} }
func (b commandZAddChP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddChCompleted(key, members...), &intCmd{})
}

var CommandZAddGT commandZAddGT

type commandZAddGT string
type commandZAddGTP struct{ p Pipeliner }

func (commandZAddGT) String() string               { return "ZADD GT" }
func (commandZAddGT) Class() string                { return "SortedSet" }
func (commandZAddGT) RequireVersion() string       { return "6.2.0" }
func (commandZAddGT) Forbid() bool                 { return false }
func (commandZAddGT) WarningOnce() bool            { return false }
func (commandZAddGT) WarnVersion() string          { return "" }
func (commandZAddGT) Warning() string              { return "" }
func (commandZAddGT) Instead() string              { return "" }
func (commandZAddGT) ETC() string                  { return "" }
func (commandZAddGT) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZAddGT) P(p Pipeliner) commandZAddGTP { return commandZAddGTP{p} }
func (b commandZAddGTP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddGTCompleted(key, members...), &intCmd{})
}

var CommandZAddIncr commandZAddIncr

type commandZAddIncr string
type commandZAddIncrP struct{ p Pipeliner }

func (commandZAddIncr) String() string                 { return "ZADD INCR" }
func (commandZAddIncr) Class() string                  { return "SortedSet" }
func (commandZAddIncr) RequireVersion() string         { return "3.0.2" }
func (commandZAddIncr) Forbid() bool                   { return false }
func (commandZAddIncr) WarningOnce() bool              { return false }
func (commandZAddIncr) WarnVersion() string            { return "" }
func (commandZAddIncr) Warning() string                { return "" }
func (commandZAddIncr) Instead() string                { return "" }
func (commandZAddIncr) ETC() string                    { return "" }
func (commandZAddIncr) PR(b BaseCmd) FloatCmd          { return b.(FloatCmd) }
func (commandZAddIncr) P(p Pipeliner) commandZAddIncrP { return commandZAddIncrP{p} }
func (b commandZAddIncrP) Cmd(key string, args ZAddArgs) {
	b.p.cmd(b.p.builder().ZAddArgsIncrCompleted(key, args), &floatCmd{})
}

var CommandZAddLT commandZAddLT

type commandZAddLT string
type commandZAddLTP struct{ p Pipeliner }

func (commandZAddLT) String() string               { return "ZADD LT" }
func (commandZAddLT) Class() string                { return "SortedSet" }
func (commandZAddLT) RequireVersion() string       { return "6.2.0" }
func (commandZAddLT) Forbid() bool                 { return false }
func (commandZAddLT) WarningOnce() bool            { return false }
func (commandZAddLT) WarnVersion() string          { return "" }
func (commandZAddLT) Warning() string              { return "" }
func (commandZAddLT) Instead() string              { return "" }
func (commandZAddLT) ETC() string                  { return "" }
func (commandZAddLT) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZAddLT) P(p Pipeliner) commandZAddLTP { return commandZAddLTP{p} }
func (b commandZAddLTP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddLTCompleted(key, members...), &intCmd{})
}

var CommandZAddNX commandZAddNX

type commandZAddNX string
type commandZAddNXP struct{ p Pipeliner }

func (commandZAddNX) String() string               { return "ZADD NX" }
func (commandZAddNX) Class() string                { return "SortedSet" }
func (commandZAddNX) RequireVersion() string       { return "3.0.2" }
func (commandZAddNX) Forbid() bool                 { return false }
func (commandZAddNX) WarningOnce() bool            { return false }
func (commandZAddNX) WarnVersion() string          { return "" }
func (commandZAddNX) Warning() string              { return "" }
func (commandZAddNX) Instead() string              { return "" }
func (commandZAddNX) ETC() string                  { return "" }
func (commandZAddNX) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZAddNX) P(p Pipeliner) commandZAddNXP { return commandZAddNXP{p} }
func (b commandZAddNXP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddNXCompleted(key, members...), &intCmd{})
}

var CommandZAddXX commandZAddXX

type commandZAddXX string
type commandZAddXXP struct{ p Pipeliner }

func (commandZAddXX) String() string               { return "ZADD XX" }
func (commandZAddXX) Class() string                { return "SortedSet" }
func (commandZAddXX) RequireVersion() string       { return "3.0.2" }
func (commandZAddXX) Forbid() bool                 { return false }
func (commandZAddXX) WarningOnce() bool            { return false }
func (commandZAddXX) WarnVersion() string          { return "" }
func (commandZAddXX) Warning() string              { return "" }
func (commandZAddXX) Instead() string              { return "" }
func (commandZAddXX) ETC() string                  { return "" }
func (commandZAddXX) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZAddXX) P(p Pipeliner) commandZAddXXP { return commandZAddXXP{p} }
func (b commandZAddXXP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddXXCompleted(key, members...), &intCmd{})
}

var CommandZCard commandZCard

type commandZCard string
type commandZCardP struct{ p Pipeliner }

func (commandZCard) String() string              { return "ZCARD" }
func (commandZCard) Class() string               { return "SortedSet" }
func (commandZCard) RequireVersion() string      { return "1.2.0" }
func (commandZCard) Forbid() bool                { return false }
func (commandZCard) WarningOnce() bool           { return false }
func (commandZCard) WarnVersion() string         { return "" }
func (commandZCard) Warning() string             { return "" }
func (commandZCard) Instead() string             { return "" }
func (commandZCard) ETC() string                 { return "" }
func (commandZCard) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandZCard) P(p Pipeliner) commandZCardP { return commandZCardP{p} }
func (b commandZCardP) Cmd(key string) {
	b.p.cmd(b.p.builder().ZCardCompleted(key), &intCmd{})
}

var CommandZCount commandZCount

type commandZCount string
type commandZCountP struct{ p Pipeliner }

func (commandZCount) String() string               { return "ZCOUNT" }
func (commandZCount) Class() string                { return "SortedSet" }
func (commandZCount) RequireVersion() string       { return "2.0.0" }
func (commandZCount) Forbid() bool                 { return false }
func (commandZCount) WarningOnce() bool            { return false }
func (commandZCount) WarnVersion() string          { return "" }
func (commandZCount) Warning() string              { return "" }
func (commandZCount) Instead() string              { return "" }
func (commandZCount) ETC() string                  { return "" }
func (commandZCount) PR(b BaseCmd) IntCmd          { return b.(IntCmd) }
func (commandZCount) P(p Pipeliner) commandZCountP { return commandZCountP{p} }
func (b commandZCountP) Cmd(key string, min string, max string) {
	b.p.cmd(b.p.builder().ZCountCompleted(key, min, max), &intCmd{})
}

var CommandZDiff commandZDiff

type commandZDiff string
type commandZDiffP struct{ p Pipeliner }

func (commandZDiff) String() string              { return "ZDIFF" }
func (commandZDiff) Class() string               { return "SortedSet" }
func (commandZDiff) RequireVersion() string      { return "6.2.0" }
func (commandZDiff) Forbid() bool                { return false }
func (commandZDiff) WarningOnce() bool           { return false }
func (commandZDiff) WarnVersion() string         { return "" }
func (commandZDiff) Warning() string             { return "" }
func (commandZDiff) Instead() string             { return "" }
func (commandZDiff) ETC() string                 { return "" }
func (commandZDiff) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandZDiff) P(p Pipeliner) commandZDiffP { return commandZDiffP{p} }
func (b commandZDiffP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().ZDiffCompleted(keys...), &stringSliceCmd{})
}

var CommandZDiffStore commandZDiffStore

type commandZDiffStore string
type commandZDiffStoreP struct{ p Pipeliner }

func (commandZDiffStore) String() string                   { return "ZDIFFSTORE" }
func (commandZDiffStore) Class() string                    { return "SortedSet" }
func (commandZDiffStore) RequireVersion() string           { return "6.2.0" }
func (commandZDiffStore) Forbid() bool                     { return false }
func (commandZDiffStore) WarningOnce() bool                { return false }
func (commandZDiffStore) WarnVersion() string              { return "" }
func (commandZDiffStore) Warning() string                  { return "" }
func (commandZDiffStore) Instead() string                  { return "" }
func (commandZDiffStore) ETC() string                      { return "" }
func (commandZDiffStore) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandZDiffStore) P(p Pipeliner) commandZDiffStoreP { return commandZDiffStoreP{p} }
func (b commandZDiffStoreP) Cmd(destination string, keys ...string) {
	b.p.cmd(b.p.builder().ZDiffStoreCompleted(destination, keys...), &intCmd{})
}

var CommandZDiffWithScores commandZDiffWithScores

type commandZDiffWithScores string
type commandZDiffWithScoresP struct{ p Pipeliner }

func (commandZDiffWithScores) String() string         { return "ZDIFF WITHSCORES" }
func (commandZDiffWithScores) Class() string          { return "SortedSet" }
func (commandZDiffWithScores) RequireVersion() string { return "6.2.0" }
func (commandZDiffWithScores) Forbid() bool           { return false }
func (commandZDiffWithScores) WarningOnce() bool      { return false }
func (commandZDiffWithScores) WarnVersion() string    { return "" }
func (commandZDiffWithScores) Warning() string        { return "" }
func (commandZDiffWithScores) Instead() string        { return "" }
func (commandZDiffWithScores) ETC() string            { return "" }
func (commandZDiffWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZDiffWithScores) P(p Pipeliner) commandZDiffWithScoresP {
	return commandZDiffWithScoresP{p}
}
func (b commandZDiffWithScoresP) Cmd(keys ...string) {
	b.p.cmd(b.p.builder().ZDiffWithScoresCompleted(keys...), &zSliceCmd{})
}

var CommandZIncrBy commandZIncrBy

type commandZIncrBy string
type commandZIncrByP struct{ p Pipeliner }

func (commandZIncrBy) String() string                { return "ZINCRBY" }
func (commandZIncrBy) Class() string                 { return "SortedSet" }
func (commandZIncrBy) RequireVersion() string        { return "1.2.0" }
func (commandZIncrBy) Forbid() bool                  { return false }
func (commandZIncrBy) WarningOnce() bool             { return false }
func (commandZIncrBy) WarnVersion() string           { return "" }
func (commandZIncrBy) Warning() string               { return "" }
func (commandZIncrBy) Instead() string               { return "" }
func (commandZIncrBy) ETC() string                   { return "" }
func (commandZIncrBy) PR(b BaseCmd) FloatCmd         { return b.(FloatCmd) }
func (commandZIncrBy) P(p Pipeliner) commandZIncrByP { return commandZIncrByP{p} }
func (b commandZIncrByP) Cmd(key string, increment float64, member string) {
	b.p.cmd(b.p.builder().ZIncrByCompleted(key, increment, member), &floatCmd{})
}

var CommandZInter commandZInter

type commandZInter string
type commandZInterP struct{ p Pipeliner }

func (commandZInter) String() string               { return "ZINTER" }
func (commandZInter) Class() string                { return "SortedSet" }
func (commandZInter) RequireVersion() string       { return "6.2.0" }
func (commandZInter) Forbid() bool                 { return false }
func (commandZInter) WarningOnce() bool            { return false }
func (commandZInter) WarnVersion() string          { return "" }
func (commandZInter) Warning() string              { return "" }
func (commandZInter) Instead() string              { return "" }
func (commandZInter) ETC() string                  { return "" }
func (commandZInter) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandZInter) P(p Pipeliner) commandZInterP { return commandZInterP{p} }
func (b commandZInterP) Cmd(store ZStore) {
	b.p.cmd(b.p.builder().ZInterCompleted(store), &stringSliceCmd{})
}

var CommandZInterCard commandZInterCard

type commandZInterCard string
type commandZInterCardP struct{ p Pipeliner }

func (commandZInterCard) String() string                   { return "ZINTERCARD" }
func (commandZInterCard) Class() string                    { return "SortedSet" }
func (commandZInterCard) RequireVersion() string           { return "7.0.0" }
func (commandZInterCard) Forbid() bool                     { return false }
func (commandZInterCard) WarningOnce() bool                { return false }
func (commandZInterCard) WarnVersion() string              { return "" }
func (commandZInterCard) Warning() string                  { return "" }
func (commandZInterCard) Instead() string                  { return "" }
func (commandZInterCard) ETC() string                      { return "" }
func (commandZInterCard) PR(b BaseCmd) IntCmd              { return b.(IntCmd) }
func (commandZInterCard) P(p Pipeliner) commandZInterCardP { return commandZInterCardP{p} }
func (b commandZInterCardP) Cmd(limit int64, keys ...string) {
	b.p.cmd(b.p.builder().ZInterCardCompleted(limit, keys...), &intCmd{})
}

var CommandZInterStore commandZInterStore

type commandZInterStore string
type commandZInterStoreP struct{ p Pipeliner }

func (commandZInterStore) String() string                    { return "ZINTERSTORE" }
func (commandZInterStore) Class() string                     { return "SortedSet" }
func (commandZInterStore) RequireVersion() string            { return "2.0.0" }
func (commandZInterStore) Forbid() bool                      { return false }
func (commandZInterStore) WarningOnce() bool                 { return false }
func (commandZInterStore) WarnVersion() string               { return "" }
func (commandZInterStore) Warning() string                   { return "" }
func (commandZInterStore) Instead() string                   { return "" }
func (commandZInterStore) ETC() string                       { return "" }
func (commandZInterStore) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandZInterStore) P(p Pipeliner) commandZInterStoreP { return commandZInterStoreP{p} }
func (b commandZInterStoreP) Cmd(destination string, store ZStore) {
	b.p.cmd(b.p.builder().ZInterStoreCompleted(destination, store), &intCmd{})
}

var CommandZInterWithScores commandZInterWithScores

type commandZInterWithScores string
type commandZInterWithScoresP struct{ p Pipeliner }

func (commandZInterWithScores) String() string         { return "ZINTER WITHSCORES" }
func (commandZInterWithScores) Class() string          { return "SortedSet" }
func (commandZInterWithScores) RequireVersion() string { return "6.2.0" }
func (commandZInterWithScores) Forbid() bool           { return false }
func (commandZInterWithScores) WarningOnce() bool      { return false }
func (commandZInterWithScores) WarnVersion() string    { return "" }
func (commandZInterWithScores) Warning() string        { return "" }
func (commandZInterWithScores) Instead() string        { return "" }
func (commandZInterWithScores) ETC() string            { return "" }
func (commandZInterWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZInterWithScores) P(p Pipeliner) commandZInterWithScoresP {
	return commandZInterWithScoresP{p}
}
func (b commandZInterWithScoresP) Cmd(store ZStore) {
	b.p.cmd(b.p.builder().ZInterWithScoresCompleted(store), &zSliceCmd{})
}

var CommandZLexCount commandZLexCount

type commandZLexCount string
type commandZLexCountP struct{ p Pipeliner }

func (commandZLexCount) String() string                  { return "ZLEXCOUNT" }
func (commandZLexCount) Class() string                   { return "SortedSet" }
func (commandZLexCount) RequireVersion() string          { return "2.8.9" }
func (commandZLexCount) Forbid() bool                    { return false }
func (commandZLexCount) WarningOnce() bool               { return false }
func (commandZLexCount) WarnVersion() string             { return "" }
func (commandZLexCount) Warning() string                 { return "" }
func (commandZLexCount) Instead() string                 { return "" }
func (commandZLexCount) ETC() string                     { return "" }
func (commandZLexCount) PR(b BaseCmd) IntCmd             { return b.(IntCmd) }
func (commandZLexCount) P(p Pipeliner) commandZLexCountP { return commandZLexCountP{p} }
func (b commandZLexCountP) Cmd(key string, min string, max string) {
	b.p.cmd(b.p.builder().ZLexCountCompleted(key, min, max), &intCmd{})
}

var CommandZMAdd commandZMAdd

type commandZMAdd string
type commandZMAddP struct{ p Pipeliner }

func (commandZMAdd) String() string              { return "ZADD" }
func (commandZMAdd) Class() string               { return "SortedSet" }
func (commandZMAdd) RequireVersion() string      { return "2.4.0" }
func (commandZMAdd) Forbid() bool                { return false }
func (commandZMAdd) WarningOnce() bool           { return false }
func (commandZMAdd) WarnVersion() string         { return "" }
func (commandZMAdd) Warning() string             { return "" }
func (commandZMAdd) Instead() string             { return "" }
func (commandZMAdd) ETC() string                 { return "" }
func (commandZMAdd) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandZMAdd) P(p Pipeliner) commandZMAddP { return commandZMAddP{p} }
func (b commandZMAddP) Cmd(key string, members ...Z) {
	b.p.cmd(b.p.builder().ZAddCompleted(key, members...), &intCmd{})
}

var CommandZMPop commandZMPop

type commandZMPop string
type commandZMPopP struct{ p Pipeliner }

func (commandZMPop) String() string                { return "ZMPOP" }
func (commandZMPop) Class() string                 { return "SortedSet" }
func (commandZMPop) RequireVersion() string        { return "7.0.0" }
func (commandZMPop) Forbid() bool                  { return false }
func (commandZMPop) WarningOnce() bool             { return false }
func (commandZMPop) WarnVersion() string           { return "" }
func (commandZMPop) Warning() string               { return "" }
func (commandZMPop) Instead() string               { return "" }
func (commandZMPop) ETC() string                   { return "" }
func (commandZMPop) PR(b BaseCmd) ZSliceWithKeyCmd { return b.(ZSliceWithKeyCmd) }
func (commandZMPop) P(p Pipeliner) commandZMPopP   { return commandZMPopP{p} }
func (b commandZMPopP) Cmd(order string, count int64, keys ...string) {
	b.p.cmd(b.p.builder().ZMPopCompleted(order, count, keys...), &zSliceWithKeyCmd{})
}

var CommandZMRem commandZMRem

type commandZMRem string
type commandZMRemP struct{ p Pipeliner }

func (commandZMRem) String() string              { return "ZREM" }
func (commandZMRem) Class() string               { return "SortedSet" }
func (commandZMRem) RequireVersion() string      { return "2.4.0" }
func (commandZMRem) Forbid() bool                { return false }
func (commandZMRem) WarningOnce() bool           { return false }
func (commandZMRem) WarnVersion() string         { return "" }
func (commandZMRem) Warning() string             { return "" }
func (commandZMRem) Instead() string             { return "" }
func (commandZMRem) ETC() string                 { return "" }
func (commandZMRem) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandZMRem) P(p Pipeliner) commandZMRemP { return commandZMRemP{p} }
func (b commandZMRemP) Cmd(key string, members ...any) {
	b.p.cmd(b.p.builder().ZRemCompleted(key, members...), &intCmd{})
}

var CommandZMScore commandZMScore

type commandZMScore string
type commandZMScoreP struct{ p Pipeliner }

func (commandZMScore) String() string                { return "ZMSCORE" }
func (commandZMScore) Class() string                 { return "SortedSet" }
func (commandZMScore) RequireVersion() string        { return "6.2.0" }
func (commandZMScore) Forbid() bool                  { return false }
func (commandZMScore) WarningOnce() bool             { return false }
func (commandZMScore) WarnVersion() string           { return "" }
func (commandZMScore) Warning() string               { return "" }
func (commandZMScore) Instead() string               { return "" }
func (commandZMScore) ETC() string                   { return "" }
func (commandZMScore) PR(b BaseCmd) FloatSliceCmd    { return b.(FloatSliceCmd) }
func (commandZMScore) P(p Pipeliner) commandZMScoreP { return commandZMScoreP{p} }
func (b commandZMScoreP) Cmd(key string, members ...string) {
	b.p.cmd(b.p.builder().ZMScoreCompleted(key, members...), &floatSliceCmd{})
}

var CommandZPopMax commandZPopMax

type commandZPopMax string
type commandZPopMaxP struct{ p Pipeliner }

func (commandZPopMax) String() string                { return "ZPOPMAX" }
func (commandZPopMax) Class() string                 { return "SortedSet" }
func (commandZPopMax) RequireVersion() string        { return "5.0.0" }
func (commandZPopMax) Forbid() bool                  { return false }
func (commandZPopMax) WarningOnce() bool             { return false }
func (commandZPopMax) WarnVersion() string           { return "" }
func (commandZPopMax) Warning() string               { return "" }
func (commandZPopMax) Instead() string               { return "" }
func (commandZPopMax) ETC() string                   { return "" }
func (commandZPopMax) PR(b BaseCmd) ZSliceCmd        { return b.(ZSliceCmd) }
func (commandZPopMax) P(p Pipeliner) commandZPopMaxP { return commandZPopMaxP{p} }
func (b commandZPopMaxP) Cmd(key string, count ...int64) {
	b.p.cmd(b.p.builder().ZPopMaxCompleted(key, count...), &zSliceCmd{})
}

var CommandZPopMin commandZPopMin

type commandZPopMin string
type commandZPopMinP struct{ p Pipeliner }

func (commandZPopMin) String() string                { return "ZPOPMIN" }
func (commandZPopMin) Class() string                 { return "SortedSet" }
func (commandZPopMin) RequireVersion() string        { return "5.0.0" }
func (commandZPopMin) Forbid() bool                  { return false }
func (commandZPopMin) WarningOnce() bool             { return false }
func (commandZPopMin) WarnVersion() string           { return "" }
func (commandZPopMin) Warning() string               { return "" }
func (commandZPopMin) Instead() string               { return "" }
func (commandZPopMin) ETC() string                   { return "" }
func (commandZPopMin) PR(b BaseCmd) ZSliceCmd        { return b.(ZSliceCmd) }
func (commandZPopMin) P(p Pipeliner) commandZPopMinP { return commandZPopMinP{p} }
func (b commandZPopMinP) Cmd(key string, count ...int64) {
	b.p.cmd(b.p.builder().ZPopMinCompleted(key, count...), &zSliceCmd{})
}

var CommandZRandMember commandZRandMember

type commandZRandMember string
type commandZRandMemberP struct{ p Pipeliner }

func (commandZRandMember) String() string                    { return "ZRANDMEMBER" }
func (commandZRandMember) Class() string                     { return "SortedSet" }
func (commandZRandMember) RequireVersion() string            { return "6.2.0" }
func (commandZRandMember) Forbid() bool                      { return false }
func (commandZRandMember) WarningOnce() bool                 { return false }
func (commandZRandMember) WarnVersion() string               { return "" }
func (commandZRandMember) Warning() string                   { return "" }
func (commandZRandMember) Instead() string                   { return "" }
func (commandZRandMember) ETC() string                       { return "" }
func (commandZRandMember) PR(b BaseCmd) StringSliceCmd       { return b.(StringSliceCmd) }
func (commandZRandMember) P(p Pipeliner) commandZRandMemberP { return commandZRandMemberP{p} }
func (b commandZRandMemberP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().ZRandMemberCompleted(key, count), &stringSliceCmd{})
}

var CommandZRandMemberWithScores commandZRandMemberWithScores

type commandZRandMemberWithScores string
type commandZRandMemberWithScoresP struct{ p Pipeliner }

func (commandZRandMemberWithScores) String() string         { return "ZRANDMEMBER WITHSCORES" }
func (commandZRandMemberWithScores) Class() string          { return "SortedSet" }
func (commandZRandMemberWithScores) RequireVersion() string { return "6.2.0" }
func (commandZRandMemberWithScores) Forbid() bool           { return false }
func (commandZRandMemberWithScores) WarningOnce() bool      { return false }
func (commandZRandMemberWithScores) WarnVersion() string    { return "" }
func (commandZRandMemberWithScores) Warning() string        { return "" }
func (commandZRandMemberWithScores) Instead() string        { return "" }
func (commandZRandMemberWithScores) ETC() string            { return "" }
func (commandZRandMemberWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRandMemberWithScores) P(p Pipeliner) commandZRandMemberWithScoresP {
	return commandZRandMemberWithScoresP{p}
}
func (b commandZRandMemberWithScoresP) Cmd(key string, count int64) {
	b.p.cmd(b.p.builder().ZRandMemberWithScoresCompleted(key, count), &zSliceCmd{})
}

var CommandZRange commandZRange

type commandZRange string
type commandZRangeP struct{ p Pipeliner }

func (commandZRange) String() string               { return "ZRANGE" }
func (commandZRange) Class() string                { return "SortedSet" }
func (commandZRange) RequireVersion() string       { return "1.2.0" }
func (commandZRange) Forbid() bool                 { return false }
func (commandZRange) WarningOnce() bool            { return false }
func (commandZRange) WarnVersion() string          { return "" }
func (commandZRange) Warning() string              { return "" }
func (commandZRange) Instead() string              { return "" }
func (commandZRange) ETC() string                  { return "" }
func (commandZRange) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandZRange) P(p Pipeliner) commandZRangeP { return commandZRangeP{p} }
func (b commandZRangeP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().ZRangeCompleted(key, start, stop), &stringSliceCmd{})
}

var CommandZRangeArgs commandZRangeArgs

type commandZRangeArgs string
type commandZRangeArgsP struct{ p Pipeliner }

func (commandZRangeArgs) String() string                   { return "ZRANGE" }
func (commandZRangeArgs) Class() string                    { return "SortedSet" }
func (commandZRangeArgs) RequireVersion() string           { return "1.2.0" }
func (commandZRangeArgs) Forbid() bool                     { return false }
func (commandZRangeArgs) WarningOnce() bool                { return false }
func (commandZRangeArgs) WarnVersion() string              { return "" }
func (commandZRangeArgs) Warning() string                  { return "" }
func (commandZRangeArgs) Instead() string                  { return "" }
func (commandZRangeArgs) ETC() string                      { return "" }
func (commandZRangeArgs) PR(b BaseCmd) StringSliceCmd      { return b.(StringSliceCmd) }
func (commandZRangeArgs) P(p Pipeliner) commandZRangeArgsP { return commandZRangeArgsP{p} }
func (b commandZRangeArgsP) Cmd(z ZRangeArgs) {
	b.p.cmd(b.p.builder().ZRangeArgsCompleted(z), &stringSliceCmd{})
}

var CommandZRangeArgsWithOption commandZRangeArgsWithOption

type commandZRangeArgsWithOption string
type commandZRangeArgsWithOptionP struct{ p Pipeliner }

func (commandZRangeArgsWithOption) String() string              { return "ZRANGE" }
func (commandZRangeArgsWithOption) Class() string               { return "SortedSet" }
func (commandZRangeArgsWithOption) RequireVersion() string      { return "6.2.0" }
func (commandZRangeArgsWithOption) Forbid() bool                { return false }
func (commandZRangeArgsWithOption) WarningOnce() bool           { return false }
func (commandZRangeArgsWithOption) WarnVersion() string         { return "" }
func (commandZRangeArgsWithOption) Warning() string             { return "" }
func (commandZRangeArgsWithOption) Instead() string             { return "" }
func (commandZRangeArgsWithOption) ETC() string                 { return "" }
func (commandZRangeArgsWithOption) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandZRangeArgsWithOption) P(p Pipeliner) commandZRangeArgsWithOptionP {
	return commandZRangeArgsWithOptionP{p}
}
func (b commandZRangeArgsWithOptionP) Cmd(z ZRangeArgs) {
	b.p.cmd(b.p.builder().ZRangeArgsCompleted(z), &stringSliceCmd{})
}

var CommandZRangeArgsWithScores commandZRangeArgsWithScores

type commandZRangeArgsWithScores string
type commandZRangeArgsWithScoresP struct{ p Pipeliner }

func (commandZRangeArgsWithScores) String() string         { return "ZRANGE WITHSCORES" }
func (commandZRangeArgsWithScores) Class() string          { return "SortedSet" }
func (commandZRangeArgsWithScores) RequireVersion() string { return "1.2.0" }
func (commandZRangeArgsWithScores) Forbid() bool           { return false }
func (commandZRangeArgsWithScores) WarningOnce() bool      { return false }
func (commandZRangeArgsWithScores) WarnVersion() string    { return "" }
func (commandZRangeArgsWithScores) Warning() string        { return "" }
func (commandZRangeArgsWithScores) Instead() string        { return "" }
func (commandZRangeArgsWithScores) ETC() string            { return "" }
func (commandZRangeArgsWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRangeArgsWithScores) P(p Pipeliner) commandZRangeArgsWithScoresP {
	return commandZRangeArgsWithScoresP{p}
}
func (b commandZRangeArgsWithScoresP) Cmd(z ZRangeArgs) {
	b.p.cmd(b.p.builder().ZRangeArgsCompleted(z), &zSliceCmd{})
}

var CommandZRangeArgsWithScoresWithOption commandZRangeArgsWithScoresWithOption

type commandZRangeArgsWithScoresWithOption string
type commandZRangeArgsWithScoresWithOptionP struct{ p Pipeliner }

func (commandZRangeArgsWithScoresWithOption) String() string         { return "ZRANGE WITHSCORES" }
func (commandZRangeArgsWithScoresWithOption) Class() string          { return "SortedSet" }
func (commandZRangeArgsWithScoresWithOption) RequireVersion() string { return "6.2.0" }
func (commandZRangeArgsWithScoresWithOption) Forbid() bool           { return false }
func (commandZRangeArgsWithScoresWithOption) WarningOnce() bool      { return false }
func (commandZRangeArgsWithScoresWithOption) WarnVersion() string    { return "" }
func (commandZRangeArgsWithScoresWithOption) Warning() string        { return "" }
func (commandZRangeArgsWithScoresWithOption) Instead() string        { return "" }
func (commandZRangeArgsWithScoresWithOption) ETC() string            { return "" }
func (commandZRangeArgsWithScoresWithOption) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRangeArgsWithScoresWithOption) P(p Pipeliner) commandZRangeArgsWithScoresWithOptionP {
	return commandZRangeArgsWithScoresWithOptionP{p}
}
func (b commandZRangeArgsWithScoresWithOptionP) Cmd(z ZRangeArgs) {
	b.p.cmd(b.p.builder().ZRangeArgsCompleted(z), &zSliceCmd{})
}

var CommandZRangeByLex commandZRangeByLex

type commandZRangeByLex string
type commandZRangeByLexP struct{ p Pipeliner }

func (commandZRangeByLex) String() string         { return "ZRANGEBYLEX" }
func (commandZRangeByLex) Class() string          { return "SortedSet" }
func (commandZRangeByLex) RequireVersion() string { return "2.8.9" }
func (commandZRangeByLex) Forbid() bool           { return false }
func (commandZRangeByLex) WarningOnce() bool      { return false }
func (commandZRangeByLex) WarnVersion() string    { return "6.2.0" }
func (commandZRangeByLex) Warning() string        { return commandZRangeByLexWarning }
func (commandZRangeByLex) Instead() string        { return "ZRangeArgs" }
func (commandZRangeByLex) ETC() string {
	return "client.ZRangeArgs(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByLex: true})"
}
func (commandZRangeByLex) PR(b BaseCmd) StringSliceCmd       { return b.(StringSliceCmd) }
func (commandZRangeByLex) P(p Pipeliner) commandZRangeByLexP { return commandZRangeByLexP{p} }
func (b commandZRangeByLexP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRangeByLexCompleted(key, opt), &stringSliceCmd{})
}

var CommandZRangeByScore commandZRangeByScore

type commandZRangeByScore string
type commandZRangeByScoreP struct{ p Pipeliner }

func (commandZRangeByScore) String() string         { return "ZRANGEBYSCORE" }
func (commandZRangeByScore) Class() string          { return "SortedSet" }
func (commandZRangeByScore) RequireVersion() string { return "1.0.5" }
func (commandZRangeByScore) Forbid() bool           { return false }
func (commandZRangeByScore) WarningOnce() bool      { return false }
func (commandZRangeByScore) WarnVersion() string    { return "6.2.0" }
func (commandZRangeByScore) Warning() string        { return commandZRangeByScoreWarning }
func (commandZRangeByScore) Instead() string        { return "ZRangeArgs" }
func (commandZRangeByScore) ETC() string {
	return "client.ZRangeArgs(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByScore: true})"
}
func (commandZRangeByScore) PR(b BaseCmd) StringSliceCmd         { return b.(StringSliceCmd) }
func (commandZRangeByScore) P(p Pipeliner) commandZRangeByScoreP { return commandZRangeByScoreP{p} }
func (b commandZRangeByScoreP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRangeByScoreCompleted(key, opt), &stringSliceCmd{})
}

var CommandZRangeByScoreWithScores commandZRangeByScoreWithScores

type commandZRangeByScoreWithScores string
type commandZRangeByScoreWithScoresP struct{ p Pipeliner }

func (commandZRangeByScoreWithScores) String() string         { return "ZRANGEBYSCORE WITHSCORE" }
func (commandZRangeByScoreWithScores) Class() string          { return "SortedSet" }
func (commandZRangeByScoreWithScores) RequireVersion() string { return "2.0.0" }
func (commandZRangeByScoreWithScores) Forbid() bool           { return false }
func (commandZRangeByScoreWithScores) WarningOnce() bool      { return false }
func (commandZRangeByScoreWithScores) WarnVersion() string    { return "6.2.0" }
func (commandZRangeByScoreWithScores) Warning() string        { return commandZRangeByScoreWithScoresWarning }
func (commandZRangeByScoreWithScores) Instead() string        { return "ZRangeArgsWithScores" }
func (commandZRangeByScoreWithScores) ETC() string {
	return "client.ZRangeArgsWithScores(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByScore: true})"
}
func (commandZRangeByScoreWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRangeByScoreWithScores) P(p Pipeliner) commandZRangeByScoreWithScoresP {
	return commandZRangeByScoreWithScoresP{p}
}
func (b commandZRangeByScoreWithScoresP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRangeByScoreWithScoresCompleted(key, opt), &zSliceCmd{})
}

var CommandZRangeStore commandZRangeStore

type commandZRangeStore string
type commandZRangeStoreP struct{ p Pipeliner }

func (commandZRangeStore) String() string                    { return "ZRANGESTORE" }
func (commandZRangeStore) Class() string                     { return "SortedSet" }
func (commandZRangeStore) RequireVersion() string            { return "6.2.0" }
func (commandZRangeStore) Forbid() bool                      { return false }
func (commandZRangeStore) WarningOnce() bool                 { return false }
func (commandZRangeStore) WarnVersion() string               { return "" }
func (commandZRangeStore) Warning() string                   { return "" }
func (commandZRangeStore) Instead() string                   { return "" }
func (commandZRangeStore) ETC() string                       { return "" }
func (commandZRangeStore) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandZRangeStore) P(p Pipeliner) commandZRangeStoreP { return commandZRangeStoreP{p} }
func (b commandZRangeStoreP) Cmd(dst string, z ZRangeArgs) {
	b.p.cmd(b.p.builder().ZRangeStoreCompleted(dst, z), &intCmd{})
}

var CommandZRangeWithScores commandZRangeWithScores

type commandZRangeWithScores string
type commandZRangeWithScoresP struct{ p Pipeliner }

func (commandZRangeWithScores) String() string         { return "ZRANGE WITHSCORE" }
func (commandZRangeWithScores) Class() string          { return "SortedSet" }
func (commandZRangeWithScores) RequireVersion() string { return "1.2.0" }
func (commandZRangeWithScores) Forbid() bool           { return false }
func (commandZRangeWithScores) WarningOnce() bool      { return false }
func (commandZRangeWithScores) WarnVersion() string    { return "" }
func (commandZRangeWithScores) Warning() string        { return "" }
func (commandZRangeWithScores) Instead() string        { return "" }
func (commandZRangeWithScores) ETC() string            { return "" }
func (commandZRangeWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRangeWithScores) P(p Pipeliner) commandZRangeWithScoresP {
	return commandZRangeWithScoresP{p}
}
func (b commandZRangeWithScoresP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().ZRangeWithScoresCompleted(key, start, stop), &zSliceCmd{})
}

var CommandZRank commandZRank

type commandZRank string
type commandZRankP struct{ p Pipeliner }

func (commandZRank) String() string              { return "ZRANK" }
func (commandZRank) Class() string               { return "SortedSet" }
func (commandZRank) RequireVersion() string      { return "2.0.0" }
func (commandZRank) Forbid() bool                { return false }
func (commandZRank) WarningOnce() bool           { return false }
func (commandZRank) WarnVersion() string         { return "" }
func (commandZRank) Warning() string             { return "" }
func (commandZRank) Instead() string             { return "" }
func (commandZRank) ETC() string                 { return "" }
func (commandZRank) PR(b BaseCmd) IntCmd         { return b.(IntCmd) }
func (commandZRank) P(p Pipeliner) commandZRankP { return commandZRankP{p} }
func (b commandZRankP) Cmd(key string, member string) {
	b.p.cmd(b.p.builder().ZRankCompleted(key, member), &intCmd{})
}

var CommandZRankWithScore commandZRankWithScore

type commandZRankWithScore string
type commandZRankWithScoreP struct{ p Pipeliner }

func (commandZRankWithScore) String() string                       { return "ZRANK WITHSCORE" }
func (commandZRankWithScore) Class() string                        { return "SortedSet" }
func (commandZRankWithScore) RequireVersion() string               { return "7.2.0" }
func (commandZRankWithScore) Forbid() bool                         { return false }
func (commandZRankWithScore) WarningOnce() bool                    { return false }
func (commandZRankWithScore) WarnVersion() string                  { return "" }
func (commandZRankWithScore) Warning() string                      { return "" }
func (commandZRankWithScore) Instead() string                      { return "" }
func (commandZRankWithScore) ETC() string                          { return "" }
func (commandZRankWithScore) PR(b BaseCmd) RankWithScoreCmd        { return b.(RankWithScoreCmd) }
func (commandZRankWithScore) P(p Pipeliner) commandZRankWithScoreP { return commandZRankWithScoreP{p} }
func (b commandZRankWithScoreP) Cmd(key string, member string) {
	b.p.cmd(b.p.builder().ZRankWithScoreCompleted(key, member), &rankWithScoreCmd{})
}

var CommandZRem commandZRem

type commandZRem string
type commandZRemP struct{ p Pipeliner }

func (commandZRem) String() string             { return "ZREM" }
func (commandZRem) Class() string              { return "SortedSet" }
func (commandZRem) RequireVersion() string     { return "1.2.0" }
func (commandZRem) Forbid() bool               { return false }
func (commandZRem) WarningOnce() bool          { return false }
func (commandZRem) WarnVersion() string        { return "" }
func (commandZRem) Warning() string            { return "" }
func (commandZRem) Instead() string            { return "" }
func (commandZRem) ETC() string                { return "" }
func (commandZRem) PR(b BaseCmd) IntCmd        { return b.(IntCmd) }
func (commandZRem) P(p Pipeliner) commandZRemP { return commandZRemP{p} }
func (b commandZRemP) Cmd(key string, member any) {
	b.p.cmd(b.p.builder().ZRemCompleted(key, member), &intCmd{})
}

var CommandZRemRangeByLex commandZRemRangeByLex

type commandZRemRangeByLex string
type commandZRemRangeByLexP struct{ p Pipeliner }

func (commandZRemRangeByLex) String() string                       { return "ZREMRANGEBYLEX" }
func (commandZRemRangeByLex) Class() string                        { return "SortedSet" }
func (commandZRemRangeByLex) RequireVersion() string               { return "2.8.9" }
func (commandZRemRangeByLex) Forbid() bool                         { return false }
func (commandZRemRangeByLex) WarningOnce() bool                    { return false }
func (commandZRemRangeByLex) WarnVersion() string                  { return "" }
func (commandZRemRangeByLex) Warning() string                      { return "" }
func (commandZRemRangeByLex) Instead() string                      { return "" }
func (commandZRemRangeByLex) ETC() string                          { return "" }
func (commandZRemRangeByLex) PR(b BaseCmd) IntCmd                  { return b.(IntCmd) }
func (commandZRemRangeByLex) P(p Pipeliner) commandZRemRangeByLexP { return commandZRemRangeByLexP{p} }
func (b commandZRemRangeByLexP) Cmd(key string, min string, max string) {
	b.p.cmd(b.p.builder().ZRemRangeByLexCompleted(key, min, max), &intCmd{})
}

var CommandZRemRangeByRank commandZRemRangeByRank

type commandZRemRangeByRank string
type commandZRemRangeByRankP struct{ p Pipeliner }

func (commandZRemRangeByRank) String() string         { return "ZREMRANGEBYRANK" }
func (commandZRemRangeByRank) Class() string          { return "SortedSet" }
func (commandZRemRangeByRank) RequireVersion() string { return "2.0.0" }
func (commandZRemRangeByRank) Forbid() bool           { return false }
func (commandZRemRangeByRank) WarningOnce() bool      { return false }
func (commandZRemRangeByRank) WarnVersion() string    { return "" }
func (commandZRemRangeByRank) Warning() string        { return "" }
func (commandZRemRangeByRank) Instead() string        { return "" }
func (commandZRemRangeByRank) ETC() string            { return "" }
func (commandZRemRangeByRank) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandZRemRangeByRank) P(p Pipeliner) commandZRemRangeByRankP {
	return commandZRemRangeByRankP{p}
}
func (b commandZRemRangeByRankP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().ZRemRangeByRankCompleted(key, start, stop), &intCmd{})
}

var CommandZRemRangeByScore commandZRemRangeByScore

type commandZRemRangeByScore string
type commandZRemRangeByScoreP struct{ p Pipeliner }

func (commandZRemRangeByScore) String() string         { return "ZREMRANGEBYSCORE" }
func (commandZRemRangeByScore) Class() string          { return "SortedSet" }
func (commandZRemRangeByScore) RequireVersion() string { return "1.2.0" }
func (commandZRemRangeByScore) Forbid() bool           { return false }
func (commandZRemRangeByScore) WarningOnce() bool      { return false }
func (commandZRemRangeByScore) WarnVersion() string    { return "" }
func (commandZRemRangeByScore) Warning() string        { return "" }
func (commandZRemRangeByScore) Instead() string        { return "" }
func (commandZRemRangeByScore) ETC() string            { return "" }
func (commandZRemRangeByScore) PR(b BaseCmd) IntCmd    { return b.(IntCmd) }
func (commandZRemRangeByScore) P(p Pipeliner) commandZRemRangeByScoreP {
	return commandZRemRangeByScoreP{p}
}
func (b commandZRemRangeByScoreP) Cmd(key string, min string, max string) {
	b.p.cmd(b.p.builder().ZRemRangeByScoreCompleted(key, min, max), &intCmd{})
}

var CommandZRevRange commandZRevRange

type commandZRevRange string
type commandZRevRangeP struct{ p Pipeliner }

func (commandZRevRange) String() string         { return "ZREVRANGE" }
func (commandZRevRange) Class() string          { return "SortedSet" }
func (commandZRevRange) RequireVersion() string { return "1.2.0" }
func (commandZRevRange) Forbid() bool           { return false }
func (commandZRevRange) WarningOnce() bool      { return false }
func (commandZRevRange) WarnVersion() string    { return "6.2.0" }
func (commandZRevRange) Warning() string        { return commandZRevRangeWarning }
func (commandZRevRange) Instead() string        { return "ZRangeArgs" }
func (commandZRevRange) ETC() string {
	return "client.ZRangeArgs(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Rev: true})"
}
func (commandZRevRange) PR(b BaseCmd) StringSliceCmd     { return b.(StringSliceCmd) }
func (commandZRevRange) P(p Pipeliner) commandZRevRangeP { return commandZRevRangeP{p} }
func (b commandZRevRangeP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().ZRevRangeCompleted(key, start, stop), &stringSliceCmd{})
}

var CommandZRevRangeByLex commandZRevRangeByLex

type commandZRevRangeByLex string
type commandZRevRangeByLexP struct{ p Pipeliner }

func (commandZRevRangeByLex) String() string         { return "ZREVRANGEBYLEX" }
func (commandZRevRangeByLex) Class() string          { return "SortedSet" }
func (commandZRevRangeByLex) RequireVersion() string { return "2.8.9" }
func (commandZRevRangeByLex) Forbid() bool           { return false }
func (commandZRevRangeByLex) WarningOnce() bool      { return false }
func (commandZRevRangeByLex) WarnVersion() string    { return "6.2.0" }
func (commandZRevRangeByLex) Warning() string        { return commandZRevRangeByLexWarning }
func (commandZRevRangeByLex) Instead() string        { return "ZRangeArgs" }
func (commandZRevRangeByLex) ETC() string {
	return "client.ZRangeArgs(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByLex: true, Rev: true})"
}
func (commandZRevRangeByLex) PR(b BaseCmd) StringSliceCmd          { return b.(StringSliceCmd) }
func (commandZRevRangeByLex) P(p Pipeliner) commandZRevRangeByLexP { return commandZRevRangeByLexP{p} }
func (b commandZRevRangeByLexP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRevRangeByLexCompleted(key, opt), &stringSliceCmd{})
}

var CommandZRevRangeByScore commandZRevRangeByScore

type commandZRevRangeByScore string
type commandZRevRangeByScoreP struct{ p Pipeliner }

func (commandZRevRangeByScore) String() string         { return "ZREVRANGEBYSCORE" }
func (commandZRevRangeByScore) Class() string          { return "SortedSet" }
func (commandZRevRangeByScore) RequireVersion() string { return "2.2.0" }
func (commandZRevRangeByScore) Forbid() bool           { return false }
func (commandZRevRangeByScore) WarningOnce() bool      { return false }
func (commandZRevRangeByScore) WarnVersion() string    { return "6.2.0" }
func (commandZRevRangeByScore) Warning() string        { return commandZRevRangeByScoreWarning }
func (commandZRevRangeByScore) Instead() string        { return "ZRangeArgs" }
func (commandZRevRangeByScore) ETC() string {
	return "client.ZRangeArgs(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByScore: true, Rev: true})"
}
func (commandZRevRangeByScore) PR(b BaseCmd) StringSliceCmd { return b.(StringSliceCmd) }
func (commandZRevRangeByScore) P(p Pipeliner) commandZRevRangeByScoreP {
	return commandZRevRangeByScoreP{p}
}
func (b commandZRevRangeByScoreP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRevRangeByScoreCompleted(key, opt), &stringSliceCmd{})
}

var CommandZRevRangeByScoreWithScores commandZRevRangeByScoreWithScores

type commandZRevRangeByScoreWithScores string
type commandZRevRangeByScoreWithScoresP struct{ p Pipeliner }

func (commandZRevRangeByScoreWithScores) String() string         { return "ZREVRANGEBYSCORE WITHSCORE" }
func (commandZRevRangeByScoreWithScores) Class() string          { return "SortedSet" }
func (commandZRevRangeByScoreWithScores) RequireVersion() string { return "2.2.0" }
func (commandZRevRangeByScoreWithScores) Forbid() bool           { return false }
func (commandZRevRangeByScoreWithScores) WarningOnce() bool      { return false }
func (commandZRevRangeByScoreWithScores) WarnVersion() string    { return "6.2.0" }
func (commandZRevRangeByScoreWithScores) Warning() string {
	return commandZRevRangeByScoreWithScoresWarning
}
func (commandZRevRangeByScoreWithScores) Instead() string { return "ZRangeArgsWithScores" }
func (commandZRevRangeByScoreWithScores) ETC() string {
	return "client.ZRangeArgsWithScores(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Offset: offset, Count: count, ByScore: true, Rev: true})"
}
func (commandZRevRangeByScoreWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRevRangeByScoreWithScores) P(p Pipeliner) commandZRevRangeByScoreWithScoresP {
	return commandZRevRangeByScoreWithScoresP{p}
}
func (b commandZRevRangeByScoreWithScoresP) Cmd(key string, opt ZRangeBy) {
	b.p.cmd(b.p.builder().ZRevRangeByScoreWithScoresCompleted(key, opt), &zSliceCmd{})
}

var CommandZRevRangeWithScores commandZRevRangeWithScores

type commandZRevRangeWithScores string
type commandZRevRangeWithScoresP struct{ p Pipeliner }

func (commandZRevRangeWithScores) String() string         { return "ZREVRANGE WITHSCORE" }
func (commandZRevRangeWithScores) Class() string          { return "SortedSet" }
func (commandZRevRangeWithScores) RequireVersion() string { return "1.2.0" }
func (commandZRevRangeWithScores) Forbid() bool           { return false }
func (commandZRevRangeWithScores) WarningOnce() bool      { return false }
func (commandZRevRangeWithScores) WarnVersion() string    { return "6.2.0" }
func (commandZRevRangeWithScores) Warning() string        { return commandZRevRangeWithScoresWarning }
func (commandZRevRangeWithScores) Instead() string        { return "ZRangeArgsWithScores" }
func (commandZRevRangeWithScores) ETC() string {
	return "client.ZRangeArgsWithScores(ctx, redisson.ZRangeArgs{Key: key, Start: start, Stop: stop, Rev: true})"
}
func (commandZRevRangeWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZRevRangeWithScores) P(p Pipeliner) commandZRevRangeWithScoresP {
	return commandZRevRangeWithScoresP{p}
}
func (b commandZRevRangeWithScoresP) Cmd(key string, start int64, stop int64) {
	b.p.cmd(b.p.builder().ZRevRangeWithScoresCompleted(key, start, stop), &zSliceCmd{})
}

var CommandZRevRank commandZRevRank

type commandZRevRank string
type commandZRevRankP struct{ p Pipeliner }

func (commandZRevRank) String() string                 { return "ZREVRANK" }
func (commandZRevRank) Class() string                  { return "SortedSet" }
func (commandZRevRank) RequireVersion() string         { return "2.0.0" }
func (commandZRevRank) Forbid() bool                   { return false }
func (commandZRevRank) WarningOnce() bool              { return false }
func (commandZRevRank) WarnVersion() string            { return "" }
func (commandZRevRank) Warning() string                { return "" }
func (commandZRevRank) Instead() string                { return "" }
func (commandZRevRank) ETC() string                    { return "" }
func (commandZRevRank) PR(b BaseCmd) IntCmd            { return b.(IntCmd) }
func (commandZRevRank) P(p Pipeliner) commandZRevRankP { return commandZRevRankP{p} }
func (b commandZRevRankP) Cmd(key string, member string) {
	b.p.cmd(b.p.builder().ZRevRankCompleted(key, member), &intCmd{})
}

var CommandZRevRankWithScore commandZRevRankWithScore

type commandZRevRankWithScore string
type commandZRevRankWithScoreP struct{ p Pipeliner }

func (commandZRevRankWithScore) String() string                { return "ZREVRANK WITHSCORE" }
func (commandZRevRankWithScore) Class() string                 { return "SortedSet" }
func (commandZRevRankWithScore) RequireVersion() string        { return "7.2.0" }
func (commandZRevRankWithScore) Forbid() bool                  { return false }
func (commandZRevRankWithScore) WarningOnce() bool             { return false }
func (commandZRevRankWithScore) WarnVersion() string           { return "" }
func (commandZRevRankWithScore) Warning() string               { return "" }
func (commandZRevRankWithScore) Instead() string               { return "" }
func (commandZRevRankWithScore) ETC() string                   { return "" }
func (commandZRevRankWithScore) PR(b BaseCmd) RankWithScoreCmd { return b.(RankWithScoreCmd) }
func (commandZRevRankWithScore) P(p Pipeliner) commandZRevRankWithScoreP {
	return commandZRevRankWithScoreP{p}
}
func (b commandZRevRankWithScoreP) Cmd(key string, member string) {
	b.p.cmd(b.p.builder().ZRevRankWithScoreCompleted(key, member), &rankWithScoreCmd{})
}

var CommandZScan commandZScan

type commandZScan string
type commandZScanP struct{ p Pipeliner }

func (commandZScan) String() string              { return "ZSCAN" }
func (commandZScan) Class() string               { return "SortedSet" }
func (commandZScan) RequireVersion() string      { return "2.8.0" }
func (commandZScan) Forbid() bool                { return false }
func (commandZScan) WarningOnce() bool           { return false }
func (commandZScan) WarnVersion() string         { return "" }
func (commandZScan) Warning() string             { return "" }
func (commandZScan) Instead() string             { return "" }
func (commandZScan) ETC() string                 { return "" }
func (commandZScan) PR(b BaseCmd) ScanCmd        { return b.(ScanCmd) }
func (commandZScan) P(p Pipeliner) commandZScanP { return commandZScanP{p} }
func (b commandZScanP) Cmd(key string, cursor uint64, match string, count int64) {
	b.p.cmd(b.p.builder().ZScanCompleted(key, cursor, match, count), &scanCmd{})
}

var CommandZScore commandZScore

type commandZScore string
type commandZScoreP struct{ p Pipeliner }

func (commandZScore) String() string               { return "ZSCORE" }
func (commandZScore) Class() string                { return "SortedSet" }
func (commandZScore) RequireVersion() string       { return "1.2.0" }
func (commandZScore) Forbid() bool                 { return false }
func (commandZScore) WarningOnce() bool            { return false }
func (commandZScore) WarnVersion() string          { return "" }
func (commandZScore) Warning() string              { return "" }
func (commandZScore) Instead() string              { return "" }
func (commandZScore) ETC() string                  { return "" }
func (commandZScore) PR(b BaseCmd) FloatCmd        { return b.(FloatCmd) }
func (commandZScore) P(p Pipeliner) commandZScoreP { return commandZScoreP{p} }
func (b commandZScoreP) Cmd(key string, member string) {
	b.p.cmd(b.p.builder().ZScoreCompleted(key, member), &floatCmd{})
}

var CommandZUnion commandZUnion

type commandZUnion string
type commandZUnionP struct{ p Pipeliner }

func (commandZUnion) String() string               { return "ZUNION" }
func (commandZUnion) Class() string                { return "SortedSet" }
func (commandZUnion) RequireVersion() string       { return "6.2.0" }
func (commandZUnion) Forbid() bool                 { return false }
func (commandZUnion) WarningOnce() bool            { return false }
func (commandZUnion) WarnVersion() string          { return "" }
func (commandZUnion) Warning() string              { return "" }
func (commandZUnion) Instead() string              { return "" }
func (commandZUnion) ETC() string                  { return "" }
func (commandZUnion) PR(b BaseCmd) StringSliceCmd  { return b.(StringSliceCmd) }
func (commandZUnion) P(p Pipeliner) commandZUnionP { return commandZUnionP{p} }
func (b commandZUnionP) Cmd(store ZStore) {
	b.p.cmd(b.p.builder().ZUnionCompleted(store), &stringSliceCmd{})
}

var CommandZUnionStore commandZUnionStore

type commandZUnionStore string
type commandZUnionStoreP struct{ p Pipeliner }

func (commandZUnionStore) String() string                    { return "ZUNIONSTORE" }
func (commandZUnionStore) Class() string                     { return "SortedSet" }
func (commandZUnionStore) RequireVersion() string            { return "2.0.0" }
func (commandZUnionStore) Forbid() bool                      { return false }
func (commandZUnionStore) WarningOnce() bool                 { return false }
func (commandZUnionStore) WarnVersion() string               { return "" }
func (commandZUnionStore) Warning() string                   { return "" }
func (commandZUnionStore) Instead() string                   { return "" }
func (commandZUnionStore) ETC() string                       { return "" }
func (commandZUnionStore) PR(b BaseCmd) IntCmd               { return b.(IntCmd) }
func (commandZUnionStore) P(p Pipeliner) commandZUnionStoreP { return commandZUnionStoreP{p} }
func (b commandZUnionStoreP) Cmd(dest string, store ZStore) {
	b.p.cmd(b.p.builder().ZUnionStoreCompleted(dest, store), &intCmd{})
}

var CommandZUnionWithScores commandZUnionWithScores

type commandZUnionWithScores string
type commandZUnionWithScoresP struct{ p Pipeliner }

func (commandZUnionWithScores) String() string         { return "ZUNION WITHSCORES" }
func (commandZUnionWithScores) Class() string          { return "SortedSet" }
func (commandZUnionWithScores) RequireVersion() string { return "6.2.0" }
func (commandZUnionWithScores) Forbid() bool           { return false }
func (commandZUnionWithScores) WarningOnce() bool      { return false }
func (commandZUnionWithScores) WarnVersion() string    { return "" }
func (commandZUnionWithScores) Warning() string        { return "" }
func (commandZUnionWithScores) Instead() string        { return "" }
func (commandZUnionWithScores) ETC() string            { return "" }
func (commandZUnionWithScores) PR(b BaseCmd) ZSliceCmd { return b.(ZSliceCmd) }
func (commandZUnionWithScores) P(p Pipeliner) commandZUnionWithScoresP {
	return commandZUnionWithScoresP{p}
}
func (b commandZUnionWithScoresP) Cmd(store ZStore) {
	b.p.cmd(b.p.builder().ZUnionWithScoresCompleted(store), &zSliceCmd{})
}
