// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package redisson

import "time"

// RateLimiterOptions should use newRateLimiterOptions to initialize it
type RateLimiterOptions struct {
	// annotation@KeyPrefix(Prefix for Redis keys used by this limiter)
	KeyPrefix string
	// annotation@Limit(Maximum number of allowed requests per window.)
	Limit int
	// annotation@Window(Time window duration for rate limiting. Must be greater than 1 millisecond.)
	Window time.Duration
}

// newRateLimiterOptions new RateLimiterOptions
func newRateLimiterOptions(opts ...RateLimiterOption) *RateLimiterOptions {
	cc := newDefaultRateLimiterOptions()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogRateLimiterOptions != nil {
		watchDogRateLimiterOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option and return the old ones
// sample:
// old := cc.ApplyOption(WithTimeout(time.Second))
// defer cc.ApplyOption(old...)
func (cc *RateLimiterOptions) ApplyOption(opts ...RateLimiterOption) []RateLimiterOption {
	var previous []RateLimiterOption
	for _, opt := range opts {
		previous = append(previous, opt.Apply(cc))
	}
	return previous
}

// RateLimiterOptionFunc option func
type RateLimiterOption interface {
	Apply(cc *RateLimiterOptions) RateLimiterOption
}

var _ RateLimiterOption = RateLimiterOptionFunc(nil)

type RateLimiterOptionFunc func(cc *RateLimiterOptions) RateLimiterOptionFunc

func (f RateLimiterOptionFunc) Apply(cc *RateLimiterOptions) RateLimiterOption {
	return f(cc)
}

// WithRateLimiterOptionKeyPrefix option func for filed KeyPrefix
func WithRateLimiterOptionKeyPrefix(v string) RateLimiterOptionFunc {
	return func(cc *RateLimiterOptions) RateLimiterOptionFunc {
		previous := cc.KeyPrefix
		cc.KeyPrefix = v
		return WithRateLimiterOptionKeyPrefix(previous)
	}
}

// WithRateLimiterOptionLimit option func for filed Limit
func WithRateLimiterOptionLimit(v int) RateLimiterOptionFunc {
	return func(cc *RateLimiterOptions) RateLimiterOptionFunc {
		previous := cc.Limit
		cc.Limit = v
		return WithRateLimiterOptionLimit(previous)
	}
}

// WithRateLimiterOptionWindow option func for filed Window
func WithRateLimiterOptionWindow(v time.Duration) RateLimiterOptionFunc {
	return func(cc *RateLimiterOptions) RateLimiterOptionFunc {
		previous := cc.Window
		cc.Window = v
		return WithRateLimiterOptionWindow(previous)
	}
}

// InstallRateLimiterOptionsWatchDog the installed func will called when newRateLimiterOptions  called
func InstallRateLimiterOptionsWatchDog(dog func(cc *RateLimiterOptions)) {
	watchDogRateLimiterOptions = dog
}

// watchDogRateLimiterOptions global watch dog
var watchDogRateLimiterOptions func(cc *RateLimiterOptions)

// setRateLimiterOptionsDefaultValue default RateLimiterOptions value
func setRateLimiterOptionsDefaultValue(cc *RateLimiterOptions) {
	for _, opt := range [...]RateLimiterOptionFunc{
		WithRateLimiterOptionKeyPrefix(defaultRateLimiterKeyPrefix),
		WithRateLimiterOptionLimit(0),
		WithRateLimiterOptionWindow(0),
	} {
		opt(cc)
	}
}

// newDefaultRateLimiterOptions new default RateLimiterOptions
func newDefaultRateLimiterOptions() *RateLimiterOptions {
	cc := &RateLimiterOptions{}
	setRateLimiterOptionsDefaultValue(cc)
	return cc
}

// all getter func
func (cc *RateLimiterOptions) GetKeyPrefix() string     { return cc.KeyPrefix }
func (cc *RateLimiterOptions) GetLimit() int            { return cc.Limit }
func (cc *RateLimiterOptions) GetWindow() time.Duration { return cc.Window }

// RateLimiterOptionsVisitor visitor interface for RateLimiterOptions
type RateLimiterOptionsVisitor interface {
	GetKeyPrefix() string
	GetLimit() int
	GetWindow() time.Duration
}

// RateLimiterOptionsInterface visitor + ApplyOption interface for RateLimiterOptions
type RateLimiterOptionsInterface interface {
	RateLimiterOptionsVisitor
	ApplyOption(...RateLimiterOption) []RateLimiterOption
}
