// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package redisson

import "time"

// LockerOptions should use newLockerOptions to initialize it
type LockerOptions struct {
	// annotation@KeyPrefix(KeyPrefix is the prefix of redis key for locks. Default value is defaultKeyPrefix)
	KeyPrefix string
	// annotation@KeyValidity(KeyValidity is the validity duration of locks. The lock holder will renew it periodically inside rueidislock to keep the lock alive. Default value is defaultKeyValidity)
	KeyValidity time.Duration
	// annotation@TryNextAfter(TryNextAfter is the timeout duration before trying the next redis key for locks. Default value is defaultTryNextAfter)
	TryNextAfter time.Duration
	// annotation@KeyMajority(KeyMajority follows Redlock semantics: a lock spans N=KeyMajority*2-1 redis keys (each on its own slot for cluster), and needs at least KeyMajority keys to be acquired to be valid. Set to 1 if a single redis instance is enough. Default value is defaultKeyMajority)
	KeyMajority int32
	// annotation@NoLoopTracking(NoLoopTracking will use NOLOOP in the CLIENT TRACKING command to avoid unnecessary notifications and thus have better performance. This can only be enabled if all your redis nodes >= 7.0.5)
	NoLoopTracking bool
	// annotation@FallbackSETPX(Use SET PX instead of SET PXAT when acquiring locks to be compatible with Redis < 6.2)
	FallbackSETPX bool
}

// newLockerOptions new LockerOptions
func newLockerOptions(opts ...LockerOption) *LockerOptions {
	cc := newDefaultLockerOptions()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogLockerOptions != nil {
		watchDogLockerOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option and return the old ones
// sample:
// old := cc.ApplyOption(WithTimeout(time.Second))
// defer cc.ApplyOption(old...)
func (cc *LockerOptions) ApplyOption(opts ...LockerOption) []LockerOption {
	var previous []LockerOption
	for _, opt := range opts {
		previous = append(previous, opt.Apply(cc))
	}
	return previous
}

// LockerOptionFunc option func
type LockerOption interface {
	Apply(cc *LockerOptions) LockerOption
}

var _ LockerOption = LockerOptionFunc(nil)

type LockerOptionFunc func(cc *LockerOptions) LockerOptionFunc

func (f LockerOptionFunc) Apply(cc *LockerOptions) LockerOption {
	return f(cc)
}

// WithLockerOptionKeyPrefix option func for filed KeyPrefix
func WithLockerOptionKeyPrefix(v string) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.KeyPrefix
		cc.KeyPrefix = v
		return WithLockerOptionKeyPrefix(previous)
	}
}

// WithLockerOptionKeyValidity option func for filed KeyValidity
func WithLockerOptionKeyValidity(v time.Duration) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.KeyValidity
		cc.KeyValidity = v
		return WithLockerOptionKeyValidity(previous)
	}
}

// WithLockerOptionTryNextAfter option func for filed TryNextAfter
func WithLockerOptionTryNextAfter(v time.Duration) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.TryNextAfter
		cc.TryNextAfter = v
		return WithLockerOptionTryNextAfter(previous)
	}
}

// WithLockerOptionKeyMajority option func for filed KeyMajority
func WithLockerOptionKeyMajority(v int32) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.KeyMajority
		cc.KeyMajority = v
		return WithLockerOptionKeyMajority(previous)
	}
}

// WithLockerOptionNoLoopTracking option func for filed NoLoopTracking
func WithLockerOptionNoLoopTracking(v bool) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.NoLoopTracking
		cc.NoLoopTracking = v
		return WithLockerOptionNoLoopTracking(previous)
	}
}

// WithLockerOptionFallbackSETPX option func for filed FallbackSETPX
func WithLockerOptionFallbackSETPX(v bool) LockerOptionFunc {
	return func(cc *LockerOptions) LockerOptionFunc {
		previous := cc.FallbackSETPX
		cc.FallbackSETPX = v
		return WithLockerOptionFallbackSETPX(previous)
	}
}

// InstallLockerOptionsWatchDog the installed func will called when newLockerOptions  called
func InstallLockerOptionsWatchDog(dog func(cc *LockerOptions)) { watchDogLockerOptions = dog }

// watchDogLockerOptions global watch dog
var watchDogLockerOptions func(cc *LockerOptions)

// setLockerOptionsDefaultValue default LockerOptions value
func setLockerOptionsDefaultValue(cc *LockerOptions) {
	for _, opt := range [...]LockerOptionFunc{
		WithLockerOptionKeyPrefix(defaultKeyPrefix),
		WithLockerOptionKeyValidity(defaultKeyValidity),
		WithLockerOptionTryNextAfter(defaultTryNextAfter),
		WithLockerOptionKeyMajority(defaultKeyMajority),
		WithLockerOptionNoLoopTracking(false),
		WithLockerOptionFallbackSETPX(false),
	} {
		opt(cc)
	}
}

// newDefaultLockerOptions new default LockerOptions
func newDefaultLockerOptions() *LockerOptions {
	cc := &LockerOptions{}
	setLockerOptionsDefaultValue(cc)
	return cc
}

// all getter func
func (cc *LockerOptions) GetKeyPrefix() string           { return cc.KeyPrefix }
func (cc *LockerOptions) GetKeyValidity() time.Duration  { return cc.KeyValidity }
func (cc *LockerOptions) GetTryNextAfter() time.Duration { return cc.TryNextAfter }
func (cc *LockerOptions) GetKeyMajority() int32          { return cc.KeyMajority }
func (cc *LockerOptions) GetNoLoopTracking() bool        { return cc.NoLoopTracking }
func (cc *LockerOptions) GetFallbackSETPX() bool         { return cc.FallbackSETPX }

// LockerOptionsVisitor visitor interface for LockerOptions
type LockerOptionsVisitor interface {
	GetKeyPrefix() string
	GetKeyValidity() time.Duration
	GetTryNextAfter() time.Duration
	GetKeyMajority() int32
	GetNoLoopTracking() bool
	GetFallbackSETPX() bool
}

// LockerOptionsInterface visitor + ApplyOption interface for LockerOptions
type LockerOptionsInterface interface {
	LockerOptionsVisitor
	ApplyOption(...LockerOption) []LockerOption
}
