// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package redisson

import (
	"fmt"
	"time"
)

// DelayOptions should use newDelayOptions to initialize it
type DelayOptions struct {
	// annotation@Prefix(延迟队列前缀)
	Prefix string
	// annotation@VisibilityTimeout(任务被 worker 拉走后的可见性超时；worker 在该时间内未 ack 则任务被 reclaim 重新入 delay。建议覆盖业务 callback 实际耗时上限。)
	VisibilityTimeout time.Duration
	// annotation@RetryTimes(comment="重试次数，当业务处理超时，或业务处理返回错误，则重试")
	RetryTimes int `usage:"重试次数，当业务处理超时，或业务处理返回错误，则重试"`
	// annotation@HandleDeadLetter(comment="处理死信，当达到最大重试次数，则为死信")
	HandleDeadLetter func(bs []byte) `usage:"处理死信，当达到最大重试次数，则为死信"`
	// annotation@PollInterval(poll/reclaim ticker 触发间隔；过小会增加 Redis 压力，过大会让到期任务的派发延迟变高。0 表示使用 defaultDelayPollInterval。)
	PollInterval time.Duration
	// annotation@PollBatch(单次 poll/reclaim 处理的最大 item 数；0 表示使用 defaultDelayPollBatch。)
	PollBatch int
	// annotation@RedisOpTimeout(单次 Redis 操作的兜底超时（与 VisibilityTimeout 解耦）；0 表示使用 defaultDelayRedisOpTimeout。)
	RedisOpTimeout time.Duration
	// annotation@RetryBackoff(业务失败后重新可见的间隔；0 表示使用 defaultDelayRetryBackoff。)
	RetryBackoff time.Duration
}

// newDelayOptions new DelayOptions
func newDelayOptions(opts ...DelayOption) *DelayOptions {
	cc := newDefaultDelayOptions()
	for _, opt := range opts {
		opt(cc)
	}
	if watchDogDelayOptions != nil {
		watchDogDelayOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option and return the old ones
// sample:
// old := cc.ApplyOption(WithTimeout(time.Second))
// defer cc.ApplyOption(old...)
func (cc *DelayOptions) ApplyOption(opts ...DelayOption) []DelayOption {
	var previous []DelayOption
	for _, opt := range opts {
		previous = append(previous, opt(cc))
	}
	return previous
}

// DelayOption option func
type DelayOption func(cc *DelayOptions) DelayOption

// WithDelayOptionPrefix option func for filed Prefix
func WithDelayOptionPrefix(v string) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.Prefix
		cc.Prefix = v
		return WithDelayOptionPrefix(previous)
	}
}

// WithDelayOptionVisibilityTimeout option func for filed VisibilityTimeout
func WithDelayOptionVisibilityTimeout(v time.Duration) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.VisibilityTimeout
		cc.VisibilityTimeout = v
		return WithDelayOptionVisibilityTimeout(previous)
	}
}

// WithDelayOptionRetryTimes 重试次数，当业务处理超时，或业务处理返回错误，则重试
func WithDelayOptionRetryTimes(v int) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.RetryTimes
		cc.RetryTimes = v
		return WithDelayOptionRetryTimes(previous)
	}
}

// WithDelayOptionHandleDeadLetter 处理死信，当达到最大重试次数，则为死信
func WithDelayOptionHandleDeadLetter(v func(bs []byte)) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.HandleDeadLetter
		cc.HandleDeadLetter = v
		return WithDelayOptionHandleDeadLetter(previous)
	}
}

// WithDelayOptionPollInterval option func for filed PollInterval
func WithDelayOptionPollInterval(v time.Duration) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.PollInterval
		cc.PollInterval = v
		return WithDelayOptionPollInterval(previous)
	}
}

// WithDelayOptionPollBatch option func for filed PollBatch
func WithDelayOptionPollBatch(v int) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.PollBatch
		cc.PollBatch = v
		return WithDelayOptionPollBatch(previous)
	}
}

// WithDelayOptionRedisOpTimeout option func for filed RedisOpTimeout
func WithDelayOptionRedisOpTimeout(v time.Duration) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.RedisOpTimeout
		cc.RedisOpTimeout = v
		return WithDelayOptionRedisOpTimeout(previous)
	}
}

// WithDelayOptionRetryBackoff option func for filed RetryBackoff
func WithDelayOptionRetryBackoff(v time.Duration) DelayOption {
	return func(cc *DelayOptions) DelayOption {
		previous := cc.RetryBackoff
		cc.RetryBackoff = v
		return WithDelayOptionRetryBackoff(previous)
	}
}

// InstallDelayOptionsWatchDog the installed func will called when newDelayOptions  called
func InstallDelayOptionsWatchDog(dog func(cc *DelayOptions)) { watchDogDelayOptions = dog }

// watchDogDelayOptions global watch dog
var watchDogDelayOptions func(cc *DelayOptions)

// setDelayOptionsDefaultValue default DelayOptions value
func setDelayOptionsDefaultValue(cc *DelayOptions) {
	for _, opt := range [...]DelayOption{
		WithDelayOptionPrefix(""),
		WithDelayOptionVisibilityTimeout(defaultDelayVisibilityTimeout),
		WithDelayOptionRetryTimes(defaultDelayRetryTimes),
		WithDelayOptionHandleDeadLetter(func(bs []byte) {
			warning(fmt.Sprintf("got dead letter, %q", bs))
		}),
		WithDelayOptionPollInterval(0),
		WithDelayOptionPollBatch(0),
		WithDelayOptionRedisOpTimeout(0),
		WithDelayOptionRetryBackoff(0),
	} {
		opt(cc)
	}
}

// newDefaultDelayOptions new default DelayOptions
func newDefaultDelayOptions() *DelayOptions {
	cc := &DelayOptions{}
	setDelayOptionsDefaultValue(cc)
	return cc
}

// all getter func
func (cc *DelayOptions) GetPrefix() string                    { return cc.Prefix }
func (cc *DelayOptions) GetVisibilityTimeout() time.Duration  { return cc.VisibilityTimeout }
func (cc *DelayOptions) GetRetryTimes() int                   { return cc.RetryTimes }
func (cc *DelayOptions) GetHandleDeadLetter() func(bs []byte) { return cc.HandleDeadLetter }
func (cc *DelayOptions) GetPollInterval() time.Duration       { return cc.PollInterval }
func (cc *DelayOptions) GetPollBatch() int                    { return cc.PollBatch }
func (cc *DelayOptions) GetRedisOpTimeout() time.Duration     { return cc.RedisOpTimeout }
func (cc *DelayOptions) GetRetryBackoff() time.Duration       { return cc.RetryBackoff }

// DelayOptionsVisitor visitor interface for DelayOptions
type DelayOptionsVisitor interface {
	GetPrefix() string
	GetVisibilityTimeout() time.Duration
	GetRetryTimes() int
	GetHandleDeadLetter() func(bs []byte)
	GetPollInterval() time.Duration
	GetPollBatch() int
	GetRedisOpTimeout() time.Duration
	GetRetryBackoff() time.Duration
}

// DelayOptionsInterface visitor + ApplyOption interface for DelayOptions
type DelayOptionsInterface interface {
	DelayOptionsVisitor
	ApplyOption(...DelayOption) []DelayOption
}
