package redisson

// Redis 命令关键字（XMODEM 大小写命令字面量）。
// 用作内部 Builder.Arbitrary().Args(...) 的常量参数。
//
// 此前以 XXX_ 前缀命名（容易被误读为 TODO）；新代码请使用 Kw* 名称。
// 旧名仍以 const alias 保留以保持向后兼容（见 keywords_legacy.go）。
const (
	KwBitField            = "BITFIELD"
	KwScan                = "SCAN"
	KwHScan               = "HSCAN"
	KwSScan               = "SSCAN"
	KwZScan               = "ZSCAN"
	KwMatch               = "MATCH"
	KwCount               = "COUNT"
	KwGeoRadiusByMember   = "GEORADIUSBYMEMBER"
	KwGeoRadiusByMemberRO = "GEORADIUSBYMEMBER_RO"
	KwGeoRadius           = "GEORADIUS"
	KwGeoRadiusRO         = "GEORADIUS_RO"
	KwGeoSearch           = "GEOSEARCH"
	KwGeoSearchStore      = "GEOSEARCHSTORE"
	KwStore               = "STORE"
	KwStoreDist           = "STOREDIST"
	KwLMove               = "LMOVE"
	KwLMPop               = "LMPOP"
	KwLPos                = "LPOS"
	KwRank                = "RANK"
	KwMaxLen              = "MAXLEN"
	KwMinID               = "MINID"
	KwFunction            = "FUNCTION"
	KwList                = "LIST"
	KwLibraryName         = "LIBRARYNAME"
	KwWithCode            = "WITHCODE"
	KwXAdd                = "XADD"
	KwNoMkStream          = "NOMKSTREAM"
	KwLimit               = "LIMIT"
	KwXPending            = "XPENDING"
	KwIdle                = "IDLE"
	KwXTrim               = "XTRIM"
	KwSet                 = "SET"
	KwKeepTTL             = "KEEPTTL"
	KwExat                = "EXAT"
	KwPx                  = "PX"
	KwEx                  = "EX"
	KwGet                 = "GET"
	KwZAdd                = "ZADD"
	KwGt                  = "GT"
	KwLt                  = "LT"
	KwCh                  = "CH"
	KwIncr                = "INCR"
	KwZInter              = "ZINTER"
	KwZInterStore         = "ZINTERSTORE"
	KwWeights             = "WEIGHTS"
	KwAggregate           = "AGGREGATE"
	KwWithScores          = "WITHSCORES"
	KwZMPop               = "ZMPOP"
	KwZRange              = "ZRANGE"
	KwZRangeStore         = "ZRANGESTORE"
	KwZUnion              = "ZUNION"
	KwZUnionStore         = "ZUNIONSTORE"
	KwByScore             = "BYSCORE"
	KwBy                  = "BY"
	KwByLex               = "BYLEX"
	KwRev                 = "REV"
	KwByRadius            = "BYRADIUS"
	KwByBox               = "BYBOX"
	KwFromMember          = "FROMMEMBER"
	KwFromLonLat          = "FROMLONLAT"
	KwWithCoord           = "WITHCOORD"
	KwWithDist            = "WITHDIST"
	KwWithHash            = "WITHHASH"
	KwAny                 = "ANY"
	KwServer              = "SERVER"
	KwCluster             = "CLUSTER"
	KwAlpha               = "ALPHA"
	KwBLMove              = "BLMOVE"
)
