// genbuilder 是 redisson 的 builder_*.go 一致性校验器与 spec 工具。
//
// 该工具有三种工作模式（互斥）：
//
//  1. -check（默认）: AST 扫描所有 builder_*.go，验证以下不变式：
//     - receiver 必须为 (b builder)
//     - 公开函数必须以 "Completed" 结尾
//     - 公开 Completed 函数必须返回单一 Completed 类型
//
//  2. -export-spec=path: 把扫描到的所有函数清单导出到 YAML
//     （格式：family/name/params），便于 review 与 cmd_gen.go 对比。
//
//  3. -check-spec=path: 比对当前 builder_*.go 是否覆盖 YAML 中列出的所有名字
//     （家族归属、参数列表、返回类型）；用于跟随 cmd_gen.go 升级的回归保护。
//
// 集成方式:
//   - redisson_builder.go 顶部 //go:generate go run ./cmd/genbuilder -check
//   - CI 中 builder-check job 同时跑 -check + -check-spec
//
// 当前不生成 builder 实现代码——所有 builder_*.go 仍为手写。
// 未来若引入 spec → 生成的工作流，将复用本工具的 AST 解析骨架。
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const builderFilePrefix = "builder_"

type funcInfo struct {
	File     string
	Line     int
	Name     string
	Recv     string // receiver type, e.g. "builder"
	NumParam int
	NumRet   int
	RetType  string
	// Family 是 builder_<family>.go 中提取的命令族名，比如 "string"、"hash"。
	Family string
	// Params 是参数类型列表（按声明顺序），例如 ["string", "int64"]。
	Params []string
}

func main() {
	var (
		root       string
		checkInv   bool
		verbose    bool
		exportSpec string
		checkSpec  string
	)
	flag.StringVar(&root, "root", ".", "package root containing builder_*.go")
	flag.BoolVar(&checkInv, "check", true, "fail (exit 1) if AST invariants are violated")
	flag.BoolVar(&verbose, "v", false, "print all discovered functions")
	flag.StringVar(&exportSpec, "export-spec", "", "write current builder spec to <path> (YAML)")
	flag.StringVar(&checkSpec, "check-spec", "", "verify current code matches the spec at <path>")
	flag.Parse()

	files, err := discover(root)
	if err != nil {
		fail("discover: %v", err)
	}
	if len(files) == 0 {
		fail("no builder_*.go files found under %s", root)
	}

	fset := token.NewFileSet()
	var funcs []funcInfo
	for _, f := range files {
		fi, err := parseFile(fset, f)
		if err != nil {
			fail("parse %s: %v", f, err)
		}
		funcs = append(funcs, fi...)
	}
	sort.Slice(funcs, func(i, j int) bool {
		if funcs[i].Family != funcs[j].Family {
			return funcs[i].Family < funcs[j].Family
		}
		return funcs[i].Name < funcs[j].Name
	})

	if exportSpec != "" {
		if err := writeSpec(exportSpec, funcs); err != nil {
			fail("write spec: %v", err)
		}
		fmt.Fprintf(os.Stderr, "wrote spec with %d funcs to %s\n", countExported(funcs), exportSpec)
	}

	if checkInv {
		if err := runCheck(funcs, verbose, len(files)); err != nil {
			fail("%v", err)
		}
	}

	if checkSpec != "" {
		if err := runSpecCheck(checkSpec, funcs); err != nil {
			fail("spec check: %v", err)
		}
		fmt.Fprintf(os.Stderr, "spec check ok: %s matches current code\n", checkSpec)
	}
}

func runCheck(funcs []funcInfo, verbose bool, fileCount int) error {
	var problems []string
	for _, fi := range funcs {
		if fi.Recv != "builder" {
			problems = append(problems, fmt.Sprintf("%s:%d %s: receiver %q (want builder)", fi.File, fi.Line, fi.Name, fi.Recv))
			continue
		}
		if isExported(fi.Name) {
			if !strings.HasSuffix(fi.Name, "Completed") {
				problems = append(problems, fmt.Sprintf("%s:%d %s: exported builder funcs must end with 'Completed'", fi.File, fi.Line, fi.Name))
			}
			if fi.NumRet != 1 || fi.RetType != "Completed" {
				problems = append(problems, fmt.Sprintf("%s:%d %s: must return single Completed (got %d returns / %q)", fi.File, fi.Line, fi.Name, fi.NumRet, fi.RetType))
			}
		}
	}
	if verbose {
		fmt.Fprintf(os.Stderr, "scanned %d builder funcs across %d files\n", len(funcs), fileCount)
	}
	if len(problems) > 0 {
		for _, p := range problems {
			fmt.Fprintln(os.Stderr, "  - "+p)
		}
		return fmt.Errorf("found %d violation(s)", len(problems))
	}
	fmt.Fprintf(os.Stderr, "ok: %d builder funcs across %d files passed invariants\n", len(funcs), fileCount)
	return nil
}

// writeSpec 输出 YAML 格式 spec：仅包含公开 Completed 函数。
func writeSpec(path string, funcs []funcInfo) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Auto-generated by cmd/genbuilder -export-spec")
	fmt.Fprintln(f, "# 描述当前 builder_*.go 暴露的所有 Completed 函数。")
	fmt.Fprintln(f, "# 用于在 CI 中校验代码与 spec 同步（cmd/genbuilder -check-spec=<path>）。")
	fmt.Fprintln(f, "version: 1")
	fmt.Fprintln(f, "functions:")
	for _, fi := range funcs {
		if !isExported(fi.Name) {
			continue
		}
		fmt.Fprintf(f, "  - name: %s\n", fi.Name)
		fmt.Fprintf(f, "    family: %s\n", fi.Family)
		fmt.Fprintf(f, "    params: [%s]\n", strings.Join(quote(fi.Params), ", "))
		fmt.Fprintf(f, "    returns: %s\n", fi.RetType)
	}
	return nil
}

// runSpecCheck 比对 spec 文件描述的函数清单与当前代码。
//
// 简易 YAML 解析：仅处理 cmd/genbuilder 自身写出的格式，
// 不引入额外 yaml 库依赖。
func runSpecCheck(path string, funcs []funcInfo) error {
	specEntries, err := readSimpleSpec(path)
	if err != nil {
		return err
	}
	current := map[string]funcInfo{}
	for _, fi := range funcs {
		if isExported(fi.Name) {
			current[fi.Name] = fi
		}
	}
	var missing, signatureDrift []string
	for _, sp := range specEntries {
		got, ok := current[sp.Name]
		if !ok {
			missing = append(missing, sp.Name)
			continue
		}
		if got.Family != sp.Family {
			signatureDrift = append(signatureDrift,
				fmt.Sprintf("%s: family %s -> %s", sp.Name, sp.Family, got.Family))
		}
		if !equal(got.Params, sp.Params) {
			signatureDrift = append(signatureDrift,
				fmt.Sprintf("%s: params %v -> %v", sp.Name, sp.Params, got.Params))
		}
		if got.RetType != sp.RetType {
			signatureDrift = append(signatureDrift,
				fmt.Sprintf("%s: returns %s -> %s", sp.Name, sp.RetType, got.RetType))
		}
		delete(current, sp.Name)
	}
	var added []string
	for n := range current {
		added = append(added, n)
	}
	sort.Strings(missing)
	sort.Strings(added)
	sort.Strings(signatureDrift)
	if len(missing)+len(added)+len(signatureDrift) > 0 {
		for _, n := range missing {
			fmt.Fprintf(os.Stderr, "  - MISSING in code: %s\n", n)
		}
		for _, n := range added {
			fmt.Fprintf(os.Stderr, "  - ADDED  in code (not in spec): %s\n", n)
		}
		for _, d := range signatureDrift {
			fmt.Fprintf(os.Stderr, "  - DRIFT  %s\n", d)
		}
		return fmt.Errorf("spec mismatch: %d missing + %d added + %d drift",
			len(missing), len(added), len(signatureDrift))
	}
	return nil
}

type specEntry struct {
	Name    string
	Family  string
	Params  []string
	RetType string
}

func readSimpleSpec(path string) ([]specEntry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out []specEntry
	var cur *specEntry
	for _, line := range strings.Split(string(data), "\n") {
		trim := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(line, "  - name:"):
			if cur != nil {
				out = append(out, *cur)
			}
			cur = &specEntry{Name: strings.TrimSpace(strings.TrimPrefix(trim, "- name:"))}
		case strings.HasPrefix(line, "    family:") && cur != nil:
			cur.Family = strings.TrimSpace(strings.TrimPrefix(trim, "family:"))
		case strings.HasPrefix(line, "    params:") && cur != nil:
			rest := strings.TrimSpace(strings.TrimPrefix(trim, "params:"))
			rest = strings.TrimPrefix(rest, "[")
			rest = strings.TrimSuffix(rest, "]")
			if rest == "" {
				cur.Params = nil
				continue
			}
			parts := strings.Split(rest, ",")
			for _, p := range parts {
				p = strings.TrimSpace(p)
				p = strings.Trim(p, `"`)
				if p != "" {
					cur.Params = append(cur.Params, p)
				}
			}
		case strings.HasPrefix(line, "    returns:") && cur != nil:
			cur.RetType = strings.TrimSpace(strings.TrimPrefix(trim, "returns:"))
		}
	}
	if cur != nil {
		out = append(out, *cur)
	}
	return out, nil
}

func discover(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path == root {
				return nil
			}
			return fs.SkipDir
		}
		name := filepath.Base(path)
		if !strings.HasPrefix(name, builderFilePrefix) || !strings.HasSuffix(name, ".go") {
			return nil
		}
		if strings.HasSuffix(name, "_test.go") {
			return nil
		}
		out = append(out, path)
		return nil
	})
	sort.Strings(out)
	return out, err
}

func parseFile(fset *token.FileSet, path string) ([]funcInfo, error) {
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	family := familyFromPath(path)
	var out []funcInfo
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Recv == nil || len(fn.Recv.List) == 0 {
			continue
		}
		recvType := exprName(fn.Recv.List[0].Type)
		fi := funcInfo{
			File:     path,
			Line:     fset.Position(fn.Pos()).Line,
			Name:     fn.Name.Name,
			Recv:     recvType,
			Family:   family,
			NumParam: countFields(fn.Type.Params),
			Params:   listParamTypes(fn.Type.Params),
		}
		if fn.Type.Results != nil {
			fi.NumRet = countFields(fn.Type.Results)
			if fi.NumRet == 1 {
				fi.RetType = exprName(fn.Type.Results.List[0].Type)
			}
		}
		out = append(out, fi)
	}
	return out, nil
}

// familyFromPath builder_string.go -> "string"
func familyFromPath(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, ".go")
	base = strings.TrimPrefix(base, builderFilePrefix)
	return base
}

func listParamTypes(fl *ast.FieldList) []string {
	if fl == nil {
		return nil
	}
	var out []string
	for _, f := range fl.List {
		t := exprName(f.Type)
		count := len(f.Names)
		if count == 0 {
			count = 1
		}
		for i := 0; i < count; i++ {
			out = append(out, t)
		}
	}
	return out
}

func countExported(funcs []funcInfo) int {
	n := 0
	for _, f := range funcs {
		if isExported(f.Name) {
			n++
		}
	}
	return n
}

func quote(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = `"` + s + `"`
	}
	return out
}

func equal(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func exprName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprName(t.X)
	case *ast.SelectorExpr:
		return exprName(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprName(t.Elt)
	case *ast.Ellipsis:
		return "..." + exprName(t.Elt)
	}
	return fmt.Sprintf("%T", e)
}

func countFields(fl *ast.FieldList) int {
	if fl == nil {
		return 0
	}
	n := 0
	for _, f := range fl.List {
		if len(f.Names) == 0 {
			n++
			continue
		}
		n += len(f.Names)
	}
	return n
}

func isExported(s string) bool {
	if s == "" {
		return false
	}
	c := s[0]
	return c >= 'A' && c <= 'Z'
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genbuilder: "+format+"\n", args...)
	os.Exit(1)
}
